### ISSUE TITLE
Sparrow causing node to shut down

### ISSUE THREAD

**Issue by ZC-pleb** [sparrowwallet/sparrow#1007]
Recently I’ve experienced an issue where my full node running on my Futurebit Apollo shuts down after being connected to sparrow. I’ve attempted running sparrow both locally and remotely, both with the same result. I’ve also tried running previous versions of sparrow which worked in the past. Same issue. Futurebit support says that it’s a known issue so I am adding this ticket to see if there some more info anyone might have/raising the issue if it’s unknown to sparrow.

**Comment by craigraw** [comment]
Not sure if you resolved this, but upgrading to v1.7.7 or later is the answer.

**Comment by ZC-pleb** [comment]
Unfortunately it looks like the problem is persisting.

**Comment by ZC-pleb** [comment]
The connection now works nicely but after a couple hours, my node shuts down.

**Comment by craigraw** [comment]
On the Apollo, please run the following command after the node has been running for a couple of hours, and report the results here:
```
time bitcoin-cli getrawmempool false
```

Can you also confirm you are running v1.7.7?

**Comment by ZC-pleb** [comment]
futurebit@futurebitbtc:~$ time bitcoin-cli getrawmempool false
bash: bitcoin-cli: command not found

real	0m0.010s
user	0m0.001s
sys	0m0.007s

And yes, I can confirm I have updated to 1.7.7. Thanks again, for the assistance.

**Comment by craigraw** [comment]
Unfortunately you are not actually executing anything - see `bash: bitcoin-cli: command not found`. If you run
```
ps aux | grep bitcoind
```
you might see the folder where `bitcoin-cli` is located. You will need to specify the full path to it when you run it.

If you can't find `bitcoin-cli`, the alternative is to run Sparrow with DEBUG logging using the `-l DEBUG` command line flag, then then searching `sparrow.log` in the Sparrow home folder (see FAQ) for log lines with with `BitcoindClient`. This will contain all the communication with Bitcoin Core that Sparrow is making, and should help determine the call that is causing the issue.

**Comment by craigraw** [comment]
Any progress on this?

**Comment by ZC-pleb** [comment]
Unfortunately no. I found the folder with all the other files related to bitcoin core but no bitcoin-cli file. I also tried the -l DEBUG line but it said bash: -l: command not found. Apologies for my lack of technical ability. The machine it's running on only has 4gb of memory so that could be what is causing the issue. If you have any suggestions that would be great but I might be helpless.

**Comment by RequestPrivacy** [comment]
> I also tried the -l DEBUG line but it said bash: -l: command not found.

Can you confirm you tried to start Sparrow from the terminal like `fullPathToSparrowFolder/bin/Sparrow -l DEBUG`?

**Comment by ZC-pleb** [comment]
Is there an easy way to find the full path?

**Comment by RequestPrivacy** [comment]
Ah sorry I thought you'd run Sparrow directly from source and would know its path :D I guess you're on a linux machine? Then it's `/opt/sparrow/bin/Sparrow` if I see correctly. 

So to run in debug mode you'd use `/opt/sparrow/bin/Sparrow -l DEBUG`. Note that once you close the terminal your Sparrow shuts down. You could also try to add the debug level logging to the launcher (try righ-clicking on the Sparrow icon where you normally start. Sometimes there's a menu option like "Edit Application" where you can find the command which is executed once you click on the icon. It will also be `/opt/sparrow/bin/Sparrow`. Add there the -l DEBUG and save. Now if you click on the icon it should run without terminal but also with debug logging.

The log file is under the following directories

| Platform | Location |
|----------| -------- |
| OSX      | ~/.sparrow |
| Linux    | ~/.sparrow |
| Windows  | %APPDATA%/Sparrow |

**Comment by ZC-pleb** [comment]
2023-07-17 21:24:51,529 WARN No response from server, setting read timeout to 34 secs
2023-07-17 21:24:51,782 ERROR Connection error
com.sparrowwallet.sparrow.net.ElectrumServerRpcException: Error getting fee rate histogram
	at com.sparrowwallet.sparrow@1.7.7/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.getFeeRateHistogram(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.7/com.sparrowwallet.sparrow.net.ElectrumServer.getMempoolRateSizes(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.7/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.7/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@1.7.7/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	... 12 common frames omitted
Caused by: java.lang.IllegalStateException: I/O error during a request processing
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeRequest(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeAndConvert(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.7/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.lambda$getFeeRateHistogram$13(Unknown Source)
	... 13 common frames omitted
Caused by: java.io.IOException: No response from server
	at com.sparrowwallet.sparrow@1.7.7/com.sparrowwallet.sparrow.net.TcpTransport.readResponse(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.7/com.sparrowwallet.sparrow.net.TcpTransport.pass(Unknown Source)
	... 17 common frames omitted
DEBUG bwt_jni                           > shutdown signal received
 DEBUG bitcoincore_rpc                   > JSON-RPC request: getblockhash [799156]
 DEBUG bitcoincore_rpc                   > JSON-RPC request: getblockhash [799156]
 DEBUG bitcoincore_rpc                   > JSON-RPC failed parsing reply of getrawmempool: JsonRpc(Transport(HttpErrorCode(503)))
 WARN  bwt::electrum                     > rpc #12 mempool.get_fee_histogram failed: JSON-RPC error: transport error: unexpected HTTP code: 503
 TRACE bwt::electrum                     > rpc #13 <- mempool.get_fee_histogram []
 DEBUG bitcoincore_rpc                   > JSON-RPC request: getrawmempool [true]
 DEBUG bitcoincore_rpc                   > JSON-RPC failed parsing reply of getblockhash: JsonRpc(Transport(SocketError(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })))
 DEBUG bitcoincore_rpc                   > JSON-RPC failed parsing reply of getblockhash: JsonRpc(Transport(SocketError(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })))
 WARN  bwt                               > failed syncing with bitcoind: JSON-RPC error: transport error: Couldn't connect to host: Connection reset by peer (os error 104)
 WARN  bwt                               > failed syncing with bitcoind: JSON-RPC error: transport error: Couldn't connect to host: Connection reset by peer (os error 104)
 DEBUG bitcoincore_rpc                   > JSON-RPC failed parsing reply of getrawmempool: JsonRpc(Transport(SocketError(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })))
 WARN  bwt::electrum                     > rpc #13 mempool.get_fee_histogram failed: JSON-RPC error: transport error: Couldn't connect to host: Connection refused (os error 111)
 WARN  bwt::electrum                     > [127.0.0.1:52996] handling failed: failed to send {"error":"JSON-RPC error: transport error: Couldn't connect to host: Connection refused (os error 111)","id":13,"jsonrpc":"2.0"}
 TRACE bwt::electrum                     > [127.0.0.1:52996] shutting down connection
 INFO  bwt::electrum                     > [127.0.0.1:52996] disconnected peer
 DEBUG bitcoincore_rpc                   > JSON-RPC request: getblockhash [799156]
 TRACE bwt::electrum                     > stop accepting new RPCs
 DEBUG bitcoincore_rpc                   > JSON-RPC failed parsing reply of getblockhash: JsonRpc(Transport(SocketError(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })))
 WARN  bwt                               > failed syncing with bitcoind: JSON-RPC error: transport error: Couldn't connect to host: Connection refused (os error 111)
 TRACE bwt::electrum                     > closing 0 RPC connections
 TRACE bwt::electrum                     > waiting for 0 RPC threads
 TRACE bwt::electrum                     > RPC connections are closed
 TRACE bwt::electrum                     > RPC server is stopped
 DEBUG bwt_jni                           > daemon stopped successfully
 TRACE bwt::electrum                     > acceptor shutting down
 DEBUG bitcoincore_rpc                   > JSON-RPC request: getblockhash [799156]

**Comment by ZC-pleb** [comment]
this of course wasn't the entire return but it was the part right before the node shut down

**Comment by RequestPrivacy** [comment]
This isn't related to your logs (Craig could tell you what's going on) but 
> The machine it's running on only has 4gb of memory so that could be what is causing the issue.

I've had a similar issue with my RPi. Its bitcoind process got killed shortly before running out of memory. 

You could search for such an occurence in your systems log file:

`sudo cat /var/log/syslog | grep -C 10 "Out of memory"`

For me something like the following showed me that the system killed the process
```bash
# /var/log/syslog
Mar 16 13:04:02 debian kernel: [17352780.421814] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=bitcoind,pid=1659642,uid=1001
Mar 16 13:04:02 debian kernel: [17352780.422033] Out of memory: Killed process 1659642 (bitcoind) total-vm:6718536kB, anon-rss:1547428kB, file-rss:0kB, shmem-rss:0kB, UID:1001 pgtables:10384kB oom_score_adj:0
Mar 16 13:04:02 debian kernel: [17352780.723486] oom_reaper: reaped process 1659642 (bitcoind), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by craigraw** [comment]
Ok this is fairly clear now - you need to upgrade your Apollo to use Bitcoin Core v24 or later. Using an older version of Bitcoin Core means Sparrow cannot use it's newer Cormorant library. The BWT library still has the original issue that was fixed in Cormorant with v1.7.7.
