### ISSUE TITLE
HWI related problems accessing Trezor One

### ISSUE THREAD

**Issue by Gilbog** [sparrowwallet/sparrow#1036]
I use a Trezor One in Sparrow on Windows 10 and recently have often difficulties unlocking and accessing the Trezor in Sparrow. Often the 9 digits to unlock don't match between Sparrow and Trezor. I click on the "correct" dots, but the PIN comes out wrong. 

Even plugging the Trezor out and back in doesn't help. But the Trezor works normally in Trezor Suite.

I even switched back to v1.7.7 because I thought this problem might be related to the new version, but it also occurs in v1.7.7.

Here is the log:

Thanks for helping!

```
2023-07-22 08:01:22,306 ERROR [Thread-67] c.s.s.i.Hwi [null:-1] Error executing hwi-2.2.1
java.io.IOException: Traceback (most recent call last):
  File "hwi.py", line 7, in <module>
  File "hwilib\_cli.py", line 304, in main
  File "hwilib\_cli.py", line 270, in process_commands
  File "hwilib\_cli.py", line 63, in enumerate_handler
  File "hwilib\commands.py", line 117, in enumerate
  File "hwilib\devices\trezor.py", line 855, in enumerate
  File "hwilib\devices\trezorlib\transport\webusb.py", line 130, in enumerate
  File "usb1\__init__.py", line 2004, in getProduct
  File "usb1\__init__.py", line 2056, in open
  File "usb1\__init__.py", line 128, in mayRaiseUSBError
  File "usb1\__init__.py", line 120, in raiseUSBError
usb1.USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]
[5000] Failed to execute script 'hwi' due to unhandled exception!

	at com.sparrowwallet.sparrow@1.7.7/com.sparrowwallet.sparrow.io.Hwi.getProcessOutput(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.7/com.sparrowwallet.sparrow.io.Hwi.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.7/com.sparrowwallet.sparrow.io.Hwi.enumerateUsb(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.7/com.sparrowwallet.sparrow.io.Hwi.enumerate(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.7/com.sparrowwallet.sparrow.io.Hwi$EnumerateService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.7/com.sparrowwallet.sparrow.io.Hwi$EnumerateService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by craigraw** [comment]
`LIBUSB_ERROR_ACCESS` means there is some kind of kernel issue accessing the USB device. Try rebooting, don't run Trezor Suite first. The PIN is scrambled intentionally - this is the Trezor design.

**Comment by Gilbog** [comment]
Thanks, I could sign my transactions after a reboot and *not* using Trezor Suite. But I still get occasional HWI errors after entering a passphrase in the signing process, see log below. Signing works when I retry after the error.

```
2023-07-22 21:22:16,923 ERROR [Thread-476] c.s.s.i.Hwi [null:-1] Error executing hwi-2.2.1
java.io.IOException: Traceback (most recent call last):
  File "hwi.py", line 7, in <module>
  File "hwilib\_cli.py", line 304, in main
  File "hwilib\_cli.py", line 270, in process_commands
  File "hwilib\_cli.py", line 63, in enumerate_handler
  File "hwilib\commands.py", line 117, in enumerate
  File "hwilib\devices\trezor.py", line 855, in enumerate
  File "hwilib\devices\trezorlib\transport\webusb.py", line 130, in enumerate
  File "usb1\__init__.py", line 2004, in getProduct
  File "usb1\__init__.py", line 2056, in open
  File "usb1\__init__.py", line 128, in mayRaiseUSBError
  File "usb1\__init__.py", line 120, in raiseUSBError
usb1.USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]
[2824] Failed to execute script 'hwi' due to unhandled exception!

	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.io.Hwi.getProcessOutput(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.io.Hwi.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.io.Hwi.enumerateUsb(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.io.Hwi.enumerate(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.io.Hwi$EnumerateService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.io.Hwi$EnumerateService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-07-22 21:23:00,010 WARN [Thread-481] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 34 secs
```
