### ISSUE TITLE
Freezing on new account settings tab

### ISSUE THREAD

**Issue by tightpoetry113** [sparrowwallet/sparrow#1078]
I was trying to add an account to my BIP39 wallet. I already have all the whirlpool-related accounts added. I added a new account that appeared to be working fine until clicking on the settings tab. Clicking that tab causes Sparrow to freeze and no longer navigate anywhere else. The settings tabs on the whirlpool-related accounts do not cause this issue.  I replicated the issue on both Windows and Ubuntu machines.

**Comment by craigraw** [comment]
Some questions, since I can't reproduce this:
- Does the freeze happen only after adding the account, or even after reloading that wallet (when Sparrow has been restarted)?
- Is there anything unusual about this wallet?
- Can you reproduce the issue on another BIP39 wallet?

If possible, please attach a thread dump of Sparrow after the freeze has occurred. It will be best to do this in Ubuntu:
1. First find the process id of the Sparrow process using `ps aux`.
2. Then enter `kill -3 <PID>`
3. The thread dump will be appended to `sparrow.log` in the Sparrow home folder (`~/.sparrow`). You can attach the whole log, or just an excerpt from the end of it that contains the thread dump information.

**Comment by tightpoetry113** [comment]
- It happens every time I restart Sparrow and navigate to that tab. 
- Not that I know of. The post-mix account is pretty deep.
- I tested it with a new wallet, without the whirlpool-related accounts, and the issue did not occur. So maybe it has something to do with those?

Here are the last lines of the log file after the freeze:

many, many lines of: 

`2023-08-24 19:23:45,175 ERROR [JavaFX Application Thread] c.s.s.SparrowWallet [null:-1] Exception in thread "JavaFX Application Thread"
java.lang.NullPointerException: null
2023-08-24 19:23:45,191 ERROR [JavaFX Application Thread] c.s.s.SparrowWallet [null:-1] Exception in thread "JavaFX Application Thread"
java.lang.NullPointerException: null
`

followed by this at the end:

`2023-08-24 19:23:45,228 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-104] c.s.w.c.m.d.MixSession[1692922859170] [null:-1]  ! connexion lost, reconnecting for a new mix...
2023-08-24 19:23:45,285 ERROR [stop-whirlpoolClient] c.s.w.c.w.WhirlpoolWallet [null:-1] com.samourai.wallet.api.backend.beans.HttpException: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused`

**Comment by craigraw** [comment]
I suspect this might something to do with the wallet file, but I'd like to try dig in to find the actual cause.

Can you try running from source? The steps are fairly simple, and easiest on Ubuntu:

1. Install Java 18 (I use [sdkman.io](https://sdkman.io) to manage Java versions)
2. Clone the repo with `git clone --recursive https://github.com/sparrowwallet/sparrow.git`
3. Enter the sparrow folder with `cd sparrow`
4. Run with `./sparrow`

The logging when running from source is more detailed, and the line with `java.lang.NullPointerException: null` should have a line number which would help to pinpoint this.

**Comment by tightpoetry113** [comment]
Okay I got some more info. 

Upon clicking the tab, I get a single instance of the following error: 

`2023-08-28 19:46:39,265 ERROR [JavaFX Application Thread] c.s.s.SparrowWallet [SparrowDesktop.java:35] Exception in thread "JavaFX Application Thread"
java.lang.IllegalArgumentException: Image must be non-null
	at javafx.graphics@18/com.sun.prism.paint.ImagePattern.<init>(ImagePattern.java:47)
	at javafx.graphics@18/com.sun.prism.paint.ImagePattern.<init>(ImagePattern.java:65)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.createImagePatternPaint(QuantumToolkit.java:965)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.getPaint(Toolkit.java:664)
	at javafx.graphics@18/javafx.scene.paint.ImagePattern.acc_getPlatformPaint(ImagePattern.java:292)
	at javafx.graphics@18/javafx.scene.paint.Paint$1.getPlatformPaint(Paint.java:48)
	at javafx.graphics@18/javafx.scene.shape.Shape.updatePGShape(Shape.java:964)
	at javafx.graphics@18/javafx.scene.shape.Shape.doUpdatePeer(Shape.java:999)
	at javafx.graphics@18/javafx.scene.shape.Shape$1.doUpdatePeer(Shape.java:131)
	at javafx.graphics@18/com.sun.javafx.scene.shape.ShapeHelper.updatePeerImpl(ShapeHelper.java:74)
	at javafx.graphics@18/com.sun.javafx.scene.shape.CircleHelper.updatePeerImpl(CircleHelper.java:64)
	at javafx.graphics@18/com.sun.javafx.scene.NodeHelper.updatePeer(NodeHelper.java:103)
	at javafx.graphics@18/javafx.scene.Node.syncPeer(Node.java:715)
	at javafx.graphics@18/javafx.scene.Scene$ScenePulseListener.synchronizeSceneNodes(Scene.java:2383)
	at javafx.graphics@18/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2529)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:405)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:404)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:434)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:575)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:352)
	at javafx.graphics@18/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
	at java.base/java.lang.Thread.run(Thread.java:833)`

I then get many instances of the following: 

`2023-08-28 19:46:39,272 ERROR [JavaFX Application Thread] c.s.s.SparrowWallet [SparrowDesktop.java:35] Exception in thread "JavaFX Application Thread"
java.lang.NullPointerException: Cannot invoke "javafx.scene.Node.getScene()" because "<local2>" is null
	at javafx.graphics@18/javafx.scene.Scene$ScenePulseListener.synchronizeSceneNodes(Scene.java:2382)
	at javafx.graphics@18/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2529)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:405)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:404)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:434)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:575)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:352)
	at javafx.graphics@18/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
	at java.base/java.lang.Thread.run(Thread.java:833)`

Followed by many instances of: 

`2023-08-28 19:46:42,037 ERROR [JavaFX Application Thread] c.s.s.SparrowWallet [SparrowDesktop.java:35] Exception in thread "JavaFX Application Thread"
java.lang.NullPointerException: null`

I don't know if this helps, but I also noticed that clicking back and forth on wallet tabs changes the title of the application window (e.g. "Sparrow - wallet 1" to "Sparrow - wallet 2"). The application itself, however, does not show any change.

**Comment by craigraw** [comment]
Thanks for the additional info. I'd like to be able to fix this, but unfortunately it seems to be occurring entirely in the JavaFX platform code. 

Can you try recreating this wallet as a new wallet, importing the same seed, add accounts and then (if successful) import/export labels? 

My other suggestion is changing the wallet icon for this wallet (right click on tab label). Don't think this will help, but worth a try.

**Comment by tightpoetry113** [comment]
Recreating the wallet with the same seed did the trick. I can now navigate to that tab without issue. Changing the icon did not work. 

Thank you Craig!

**Comment by craigraw** [comment]
Great! Wish I could say what the cause was, but that will have to wait for another day :)

**Comment by chrisblec** [comment]
I just grappled with the same bug. Was about to submit an issue when I saw this one. Creating a new wallet and using the same seed seems to have worked. Regardless I'll share what I was going to submit in case there's any clues in there:
---

GUI freezing on following behavior running Sparrow 1.7.9 on macOS 14.0 connected to custom server via Tor:

* open user-created software wallet (not Whirlpool) using password & passphrase
* click on account 2 in left column (user previously renamed to custom name)
* click on "settings"
* gui freezes - can still switch between wallet tabs but gui does not update - top menu still works

Happens whether or not transactions have finished loading.

Log: 
```
2023-10-17 22:44:45,803 ERROR [JavaFX Application Thread] c.s.s.SparrowWallet [null:-1] Exception in thread "JavaFX Application Thread"
java.lang.IllegalArgumentException: Image must be non-null
	at javafx.graphics@18/com.sun.prism.paint.ImagePattern.<init>(Unknown Source)
	at javafx.graphics@18/com.sun.prism.paint.ImagePattern.<init>(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.createImagePatternPaint(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.getPaint(Unknown Source)
	at javafx.graphics@18/javafx.scene.paint.ImagePattern.acc_getPlatformPaint(Unknown Source)
	at javafx.graphics@18/javafx.scene.paint.Paint$1.getPlatformPaint(Unknown Source)
	at javafx.graphics@18/javafx.scene.shape.Shape.updatePGShape(Unknown Source)
	at javafx.graphics@18/javafx.scene.shape.Shape.doUpdatePeer(Unknown Source)
	at javafx.graphics@18/javafx.scene.shape.Shape$1.doUpdatePeer(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.scene.shape.ShapeHelper.updatePeerImpl(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.scene.shape.CircleHelper.updatePeerImpl(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.scene.NodeHelper.updatePeer(Unknown Source)
	at javafx.graphics@18/javafx.scene.Node.syncPeer(Unknown Source)
	at javafx.graphics@18/javafx.scene.Scene$ScenePulseListener.synchronizeSceneNodes(Unknown Source)
	at javafx.graphics@18/javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
2023-10-17 22:44:45,807 ERROR [JavaFX Application Thread] c.s.s.SparrowWallet [null:-1] Exception in thread "JavaFX Application Thread"
java.lang.NullPointerException: Cannot invoke "javafx.scene.Node.getScene()" because "<local2>" is null
	at javafx.graphics@18/javafx.scene.Scene$ScenePulseListener.synchronizeSceneNodes(Unknown Source)
	at javafx.graphics@18/javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
```

**Comment by craigraw** [comment]
@chrisblec Did the affected wallet show this behaviour reliably?

**Comment by chrisblec** [comment]
It didn’t present right away (I was able to access xpub if new account immediately after creation) but the next time I opened wallet it began presenting 100% of the time.

**Comment by craigraw** [comment]
Thanks Chris. If this happens to be a test wallet (unlikely I know) it would help immensely to get access to the problematic wallet file. I've spent many hours trying to recreate this puzzling issue without success.

**Comment by chrisblec** [comment]
You can’t have that wallet but I will create a test wallet and try to recreate the issue.
