### ISSUE TITLE
Support Extended Seeds or "Passphrase" or "Hidden Wallet" with Trezor

### ISSUE THREAD

**Issue by f90fwT** [sparrowwallet/sparrow#1098]
Pretty much the title

**Comment by craigraw** [comment]
This is supported for both Trezor One and Trezor T. Note that on the Trezor One you need to toggle this functionality on (see the USB icon in the status bar), and on the Trezor T you need to enter the passphrase on the device (and not in Sparrow).

**Comment by f90fwT** [comment]
@craigraw Thanks for your quick response. I already tried to do that, but this is what happens:
 - When I click the USB icon in the right bottom corner, it shows that my Trezor One is locked, if I click it nothing happens. (I think it should unlock it?)
 - If its already unlocked (by creating a new account in a wallet or something) I get the option "Toggle Passpharse On"! If I click that, it opens a "Do you really want to enable passpharse protection?" screen on my Trezor. But after I click confirm there, nothing happens. Nothing on the computer and nothing on the Trezor.

If you need any specific logs or something let me know, don't really know where to look. Can tell you that I installed Sparrow with the `sparrow-1.7.9-1.x86_64.rpm` file on my Fedora Linux 38 PC.
<details>
  <summary>And this is the log file that I can open from the Sparrow toolbar (From when I just opened Sparrow and tried to click the USB Thing like explained in the first bullet point)(I did it multiple times)</summary>

```

2023-09-14 12:01:29,981 ERROR [Thread-64] c.s.s.i.Hwi [null:-1] Error executing hwi-2.3.1
java.io.IOException: Traceback (most recent call last):
  File "hwi.py", line 7, in <module>
  File "hwilib/_cli.py", line 304, in main
  File "hwilib/_cli.py", line 270, in process_commands
  File "hwilib/_cli.py", line 63, in enumerate_handler
  File "hwilib/commands.py", line 117, in enumerate
  File "hwilib/devices/trezor.py", line 895, in enumerate
  File "hwilib/devices/trezor.py", line 171, in func
  File "hwilib/devices/trezor.py", line 790, in close
  File "hwilib/devices/trezorlib/client.py", line 137, in close
  File "hwilib/devices/trezorlib/transport/protocol.py", line 120, in end_session
  File "hwilib/devices/trezorlib/transport/protocol.py", line 91, in end_session
  File "hwilib/devices/trezorlib/transport/webusb.py", line 61, in close
  File "usb1/__init__.py", line 1155, in releaseInterface
  File "usb1/__init__.py", line 127, in mayRaiseUSBError
  File "usb1/__init__.py", line 119, in raiseUSBError
usb1.USBErrorNotFound: LIBUSB_ERROR_NOT_FOUND [-5]
[19182] Failed to execute script 'hwi' due to unhandled exception!

	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.getProcessOutput(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.enumerateUsb(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.enumerate(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-09-14 12:06:50,270 ERROR [Thread-98] c.s.s.i.Hwi [null:-1] Error executing hwi-2.3.1
java.io.IOException: Traceback (most recent call last):
  File "hwi.py", line 7, in <module>
  File "hwilib/_cli.py", line 304, in main
  File "hwilib/_cli.py", line 270, in process_commands
  File "hwilib/_cli.py", line 63, in enumerate_handler
  File "hwilib/commands.py", line 117, in enumerate
  File "hwilib/devices/trezor.py", line 895, in enumerate
  File "hwilib/devices/trezor.py", line 171, in func
  File "hwilib/devices/trezor.py", line 790, in close
  File "hwilib/devices/trezorlib/client.py", line 137, in close
  File "hwilib/devices/trezorlib/transport/protocol.py", line 120, in end_session
  File "hwilib/devices/trezorlib/transport/protocol.py", line 91, in end_session
  File "hwilib/devices/trezorlib/transport/webusb.py", line 61, in close
  File "usb1/__init__.py", line 1155, in releaseInterface
  File "usb1/__init__.py", line 127, in mayRaiseUSBError
  File "usb1/__init__.py", line 119, in raiseUSBError
usb1.USBErrorNotFound: LIBUSB_ERROR_NOT_FOUND [-5]
[20792] Failed to execute script 'hwi' due to unhandled exception!

	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.getProcessOutput(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.enumerateUsb(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.enumerate(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-09-14 12:07:53,228 ERROR [Thread-104] c.s.s.i.Hwi [null:-1] Error executing hwi-2.3.1
java.io.IOException: Traceback (most recent call last):
  File "hwi.py", line 7, in <module>
  File "hwilib/_cli.py", line 304, in main
  File "hwilib/_cli.py", line 270, in process_commands
  File "hwilib/_cli.py", line 63, in enumerate_handler
  File "hwilib/commands.py", line 117, in enumerate
  File "hwilib/devices/trezor.py", line 895, in enumerate
  File "hwilib/devices/trezor.py", line 171, in func
  File "hwilib/devices/trezor.py", line 790, in close
  File "hwilib/devices/trezorlib/client.py", line 137, in close
  File "hwilib/devices/trezorlib/transport/protocol.py", line 120, in end_session
  File "hwilib/devices/trezorlib/transport/protocol.py", line 91, in end_session
  File "hwilib/devices/trezorlib/transport/webusb.py", line 61, in close
  File "usb1/__init__.py", line 1155, in releaseInterface
  File "usb1/__init__.py", line 127, in mayRaiseUSBError
  File "usb1/__init__.py", line 119, in raiseUSBError
usb1.USBErrorNotFound: LIBUSB_ERROR_NOT_FOUND [-5]
[21069] Failed to execute script 'hwi' due to unhandled exception!

	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.getProcessOutput(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.enumerateUsb(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.enumerate(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-09-14 12:09:04,820 ERROR [Thread-110] c.s.s.i.Hwi [null:-1] Error executing hwi-2.3.1
java.io.IOException: Traceback (most recent call last):
  File "hwi.py", line 7, in <module>
  File "hwilib/_cli.py", line 304, in main
  File "hwilib/_cli.py", line 270, in process_commands
  File "hwilib/_cli.py", line 63, in enumerate_handler
  File "hwilib/commands.py", line 117, in enumerate
  File "hwilib/devices/trezor.py", line 895, in enumerate
  File "hwilib/devices/trezor.py", line 171, in func
  File "hwilib/devices/trezor.py", line 790, in close
  File "hwilib/devices/trezorlib/client.py", line 137, in close
  File "hwilib/devices/trezorlib/transport/protocol.py", line 120, in end_session
  File "hwilib/devices/trezorlib/transport/protocol.py", line 91, in end_session
  File "hwilib/devices/trezorlib/transport/webusb.py", line 61, in close
  File "usb1/__init__.py", line 1155, in releaseInterface
  File "usb1/__init__.py", line 127, in mayRaiseUSBError
  File "usb1/__init__.py", line 119, in raiseUSBError
usb1.USBErrorNotFound: LIBUSB_ERROR_NOT_FOUND [-5]
[21798] Failed to execute script 'hwi' due to unhandled exception!

	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.getProcessOutput(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.enumerateUsb(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.enumerate(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-09-14 12:10:23,095 ERROR [Thread-116] c.s.s.i.Hwi [null:-1] Error executing hwi-2.3.1
java.io.IOException: Traceback (most recent call last):
  File "hwi.py", line 7, in <module>
  File "hwilib/_cli.py", line 304, in main
  File "hwilib/_cli.py", line 270, in process_commands
  File "hwilib/_cli.py", line 63, in enumerate_handler
  File "hwilib/commands.py", line 117, in enumerate
  File "hwilib/devices/trezor.py", line 895, in enumerate
  File "hwilib/devices/trezor.py", line 171, in func
  File "hwilib/devices/trezor.py", line 790, in close
  File "hwilib/devices/trezorlib/client.py", line 137, in close
  File "hwilib/devices/trezorlib/transport/protocol.py", line 120, in end_session
  File "hwilib/devices/trezorlib/transport/protocol.py", line 91, in end_session
  File "hwilib/devices/trezorlib/transport/webusb.py", line 61, in close
  File "usb1/__init__.py", line 1155, in releaseInterface
  File "usb1/__init__.py", line 127, in mayRaiseUSBError
  File "usb1/__init__.py", line 119, in raiseUSBError
usb1.USBErrorNotFound: LIBUSB_ERROR_NOT_FOUND [-5]
[22115] Failed to execute script 'hwi' due to unhandled exception!

	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.getProcessOutput(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.enumerateUsb(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.enumerate(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-09-14 12:10:50,525 ERROR [Thread-9] c.s.s.i.Hwi [null:-1] Error executing hwi-2.3.1
java.io.IOException: Traceback (most recent call last):
  File "hwi.py", line 7, in <module>
  File "hwilib/_cli.py", line 304, in main
  File "hwilib/_cli.py", line 270, in process_commands
  File "hwilib/_cli.py", line 63, in enumerate_handler
  File "hwilib/commands.py", line 117, in enumerate
  File "hwilib/devices/trezor.py", line 895, in enumerate
  File "hwilib/devices/trezor.py", line 171, in func
  File "hwilib/devices/trezor.py", line 790, in close
  File "hwilib/devices/trezorlib/client.py", line 137, in close
  File "hwilib/devices/trezorlib/transport/protocol.py", line 120, in end_session
  File "hwilib/devices/trezorlib/transport/protocol.py", line 91, in end_session
  File "hwilib/devices/trezorlib/transport/webusb.py", line 61, in close
  File "usb1/__init__.py", line 1155, in releaseInterface
  File "usb1/__init__.py", line 127, in mayRaiseUSBError
  File "usb1/__init__.py", line 119, in raiseUSBError
usb1.USBErrorNotFound: LIBUSB_ERROR_NOT_FOUND [-5]
[22632] Failed to execute script 'hwi' due to unhandled exception!

	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.getProcessOutput(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.enumerateUsb(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.enumerate(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
</details>

**Comment by craigraw** [comment]
The passphrase on the Trezor One is a setting stored in the device - after you have enabled it (by approving on the device as per your second bullet point) you should unplug and reconnect the Trezor. Sparrow will then ask you for the passphrase the next time the device is required.

FWIW you can also use `trezorctl` to enable/disable passphrase functionality, a command line utility supplied by Trezor.

**Comment by f90fwT** [comment]
thanks that worked

**Comment by comassky** [comment]
Hi ! How can i enter the phassphrase from Sparrow to the Trezor (passphrase enabled, but ask me to enter on my device) @craigraw

**Comment by craigraw** [comment]
@comassky You can't (unless it's an older device like the Trezor One which doesn't support ondevice passphrase entry). Passphrase entry on other Trezors is specifically disabled for security reasons.

**Comment by comassky** [comment]
Thanks for answers.
