### ISSUE TITLE
Still having few different type of connection issues

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#110]
![image](https://user-images.githubusercontent.com/388716/116342703-164b0f80-a7b1-11eb-916c-324b3082e01d.png)
Is it really connected? Not getting any updates.
What does yellow mean?

![image](https://user-images.githubusercontent.com/388716/116342829-44305400-a7b1-11eb-9b83-7432254986c7.png)
Showing this nonstop for about 5min then it just pretend like it's connected.

Then I try to change server, 
![image](https://user-images.githubusercontent.com/388716/116343035-a426fa80-a7b1-11eb-8afa-19681379f8e6.png)

server section is completely grayed out, I assume because it think it's connected.

![image](https://user-images.githubusercontent.com/388716/116343130-de909780-a7b1-11eb-8558-166ea2212eff.png)

I change server, Testing connection, again nothing at all.

![image](https://user-images.githubusercontent.com/388716/116343179-f831df00-a7b1-11eb-9dfe-ef58a4aa9e81.png)
I turn this on expecting something new

on and off again, 
![image](https://user-images.githubusercontent.com/388716/116343229-0da70900-a7b2-11eb-9ced-967e04e7e157.png)
now it tries to connect...
nothing

```
2021-03-05 18:42:42,262 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
com.sparrowwallet.sparrow.net.ServerException: java.net.ConnectException: Connection refused: connect
	at com.sparrowwallet.sparrow@1.2.0/com.sparrowwallet.sparrow.net.TcpTransport.connect(Unknown Source)
	at com.sparrowwallet.sparrow@1.2.0/com.sparrowwallet.sparrow.net.ElectrumServer.connect(Unknown Source)
	at com.sparrowwallet.sparrow@1.2.0/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.2.0/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.<init>(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketFactoryImpl.createSocket(Unknown Source)
	at com.sparrowwallet.sparrow@1.2.0/com.sparrowwallet.sparrow.net.TcpOverTlsTransport.createSocket(Unknown Source)
	... 12 common frames omitted
```

restarted the app 2-3 times 

Changed servers 

![image](https://user-images.githubusercontent.com/388716/116343570-ab9ad380-a7b2-11eb-8c69-eb804a3efa41.png)
Seems like it's connected for a second.

![image](https://user-images.githubusercontent.com/388716/116343590-b81f2c00-a7b2-11eb-9693-0f207134b311.png)
Not much luck.

```
2021-04-27 23:44:53,719 ERROR [JavaFX Application Thread] c.s.s.w.WalletForm [null:-1] Error retrieving wallet history
com.sparrowwallet.sparrow.net.ServerException: Failed to retrieve references for paths: [m/0/0, m/0/1, m/0/2, m/0/3, m/0/4, m/0/5, m/0/6, m/0/7, m/0/8, m/0/9, m/0/10, ... ... ...
 m/0/1511, m/0/1513, m/0/1514, m/0/1516]
	at com.sparrowwallet.sparrow@1.3.2/com.sparrowwallet.sparrow.net.ElectrumServer.getReferences(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.2/com.sparrowwallet.sparrow.net.ElectrumServer.getHistory(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.2/com.sparrowwallet.sparrow.net.ElectrumServer.getHistory(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.2/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.2/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Cannot deserialize instance of `[Lcom.sparrowwallet.sparrow.net.ScriptHashTx;` out of VALUE_STRING token
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.ObjectMapper._convert(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.ObjectMapper.convertValue(Unknown Source)
	at com.sparrowwallet.merged.module@1.3.2/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.processSingleResponse(Unknown Source)
	at com.sparrowwallet.merged.module@1.3.2/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.processBatchResponse(Unknown Source)
	at com.sparrowwallet.merged.module@1.3.2/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.2/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.2/com.sparrowwallet.sparrow.net.BatchedElectrumServerRpc.getScriptHashHistory(Unknown Source)
	... 13 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `[Lcom.sparrowwallet.sparrow.net.ScriptHashTx;` out of VALUE_STRING token
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.exc.MismatchedInputException.from(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.handleNonArray(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(Unknown Source)
	... 20 common frames omitted
```

![image](https://user-images.githubusercontent.com/388716/116343728-02081200-a7b3-11eb-92d5-326f59c79b11.png)
Now back at trying blockstream server

![image](https://user-images.githubusercontent.com/388716/116343829-37acfb00-a7b3-11eb-966a-495290ac7fb5.png)

App is super slow, No wonder.

Kill procress, restart

![image](https://user-images.githubusercontent.com/388716/116343974-7a6ed300-a7b3-11eb-9272-e52c1ccaa6b7.png)
It showed this for about 10 second then nothing in the status bar.

It made some progress, It now recognize as confirmed a transaction from two months ago, but still there's a few hundreads TX since then that it's not aware of.

Disconect, reconect,

![image](https://user-images.githubusercontent.com/388716/116344386-231d3280-a7b4-11eb-98c2-450aa36e9cec.png)
Shows this for about 5min ,,,

Nothing, 

Close and reopen wallet,

![image](https://user-images.githubusercontent.com/388716/116344532-5f509300-a7b4-11eb-89f7-7b92e2d366cf.png)
Shows this then nothing, still not aware of what happened in last two months.

Really nothing works to get it to connect or get that wallet updated at this point.
and the feedback from the app has been minimal and inconsistent during that whole process.

**Comment by Transisto** [comment]
I tried on a much smaller wallet on another PC, 

This is what I got:
```

2021-04-28 00:05:23,279 ERROR [JavaFX Application Thread] c.s.s.w.WalletForm [null:-1] Error retrieving wallet history
com.sparrowwallet.sparrow.net.ServerException: Failed to retrieve references for paths: [m/0/0, m/0/1, m/0/2, m/0/3, m/0/4, m/0/5, m/0/6, m/0/7, m/0/8, m/0/9, m/0/10, m/0/11, m/0/12, m/0/13, m/0/14, m/0/15, m/0/16, m/0/17, m/0/18, m/0/19, m/0/20, m/0/21, m/0/22, m/0/23, m/0/24, m/0/25, m/0/26, m/0/27, m/0/28, m/0/29, m/0/30, m/0/31, m/0/32, m/0/33, m/0/34, m/0/35, m/0/36, m/0/37, m/0/38, m/0/39, m/0/40, m/0/41, m/0/42, m/0/43, m/0/44, m/0/45, m/0/46, m/0/47, m/0/48, m/0/49, m/0/50, m/0/51, m/0/52, m/0/53, m/0/54, m/0/55, m/0/56, m/0/57, m/0/58, m/0/59, m/0/60, m/0/61, m/0/62, m/0/63, m/0/64, m/0/65, m/0/66, m/0/67, m/0/68, m/0/69, m/0/70, m/0/71, m/0/72, m/0/73, m/0/74, m/0/75, m/0/76, m/0/77, m/0/78, m/0/79, m/0/80, m/0/81, m/0/82, m/0/83, m/0/84, m/0/85, m/0/86, m/0/87, m/0/88, m/0/89, m/0/90, m/0/91, m/0/92, m/0/93, m/0/94, m/0/95, m/0/96, m/0/97, m/0/98, m/0/99, m/0/100, m/0/101, m/0/102, m/0/103, m/0/104, m/0/105, m/0/106, m/0/107, m/0/108, m/0/109, m/0/110, m/0/111, m/0/112, m/0/113, m/0/114]
	at com.sparrowwallet.sparrow@1.3.2/com.sparrowwallet.sparrow.net.ElectrumServer.getReferences(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.2/com.sparrowwallet.sparrow.net.ElectrumServer.getHistory(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.2/com.sparrowwallet.sparrow.net.ElectrumServer.getHistory(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.2/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.2/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Cannot deserialize instance of `[Lcom.sparrowwallet.sparrow.net.ScriptHashTx;` out of VALUE_STRING token
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.ObjectMapper._convert(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.ObjectMapper.convertValue(Unknown Source)
	at com.sparrowwallet.merged.module@1.3.2/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.processSingleResponse(Unknown Source)
	at com.sparrowwallet.merged.module@1.3.2/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.processBatchResponse(Unknown Source)
	at com.sparrowwallet.merged.module@1.3.2/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.2/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.2/com.sparrowwallet.sparrow.net.BatchedElectrumServerRpc.getScriptHashHistory(Unknown Source)
	... 13 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `[Lcom.sparrowwallet.sparrow.net.ScriptHashTx;` out of VALUE_STRING token
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.exc.MismatchedInputException.from(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.handleNonArray(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(Unknown Source)
	... 20 common frames omitted

```

Excuse my ignorance but does that mean the wallet crash as it was checking address m/0/114?

**Comment by craigraw** [comment]
These issues are all due to the three public servers you tried being overloaded. You are connected on a TCP level, but clearly not on an application level, or at least not well enough. Sparrow can certainly do better here.

I've made a number of changes in 6f5ee7c which should improve most of these issues. Sparrow will now try another public server automatically if the one it is connected to fails when loading the wallet history. The bug with the high CPU usage should also be resolved. 

> Excuse my ignorance but does that mean the wallet crash as it was checking address m/0/114?

It means the server request to retrieve on all of the derivation paths has failed to return a response.

**Comment by Transisto** [comment]
Tried loading a very small wallet, about a dozen transactoins.

blockstream server connect, then I get :  
![image](https://user-images.githubusercontent.com/388716/116466386-67541580-a83c-11eb-9e06-06233144334a.png)
Forever

There's no error in the logs,

Sparrow taking 1% cpu but a steady 7% GPU



.....

![image](https://user-images.githubusercontent.com/388716/116466663-c9ad1600-a83c-11eb-9759-ad18446d6c3f.png)

**Comment by craigraw** [comment]
Give 1.4.0 a try. Many issues surrounding public server connections were addressed. Let me know if you see any improvements.

**Comment by Transisto** [comment]
Is there a maximum number of used addresses that sparrow can support?

It's doing the same thing, without any log error messages.

**Comment by craigraw** [comment]
No, but there is probably a maximum number of used addresses that public servers can support. Each one is a subscription to a script hash that takes a certain amount of memory and CPU resource. If you have a large number of used addresses, it's probably time to consider a private server or node connection.

If you run in debug, you'll see log messages (see the FAQ for doing this on different platforms):
```sh
> ./sparrow -l DEBUG
```

**Comment by Transisto** [comment]
checking 4000 addresses takes about 5 seconds on any public electrumx or esplora server.

last I tested it took forever on an electrs server, the only one that wasn't prohibitive to run.

and it just does nothing on Sparrow.

`2021-05-01 01:39:15,709 DEBUG [Thread-7] c.s.s.n.ElectrumServer [null:-1] Subscribe to:        [m/0/1124, m/0/1125, m/0/1126, m/0/1127, m/0/1128, m/0/1129, m/0/1130, m/0/1131, m/0/1132, m/0/1133, m/0/1134, m/0/1135, m/0/1136, m/0/1137, m/0/1138, m/0/1139, m/0/1140, m/0/1141, m/0/1142, m/0/1143]`

Seems to completely hang on that.

**Comment by Transisto** [comment]
Seemed to hang, but after about 10min it loaded the last few months transactions and go up to date.

Still app is missing feedback about what's happening during syncing.

**Comment by craigraw** [comment]
Added a transactions loading log viewer in 438c13f (shows below the transactions table):

<img width="811" alt="Screenshot 2021-05-04 at 15 18 27" src="https://user-images.githubusercontent.com/862166/117009505-1fc20380-acec-11eb-9132-ec5f225fda83.png">

This log viewer is not displayed by default, but can be enabled through the new View > Show Wallet Loading Log menu item.

Closing this off as I believe the issue has now been addressed.
