### ISSUE TITLE
Trouble connecting Sparrow to remote bwt server (as an electrum private server)

### ISSUE THREAD

**Issue by pjv** [sparrowwallet/sparrow#1134]
I have a remote pruned bitcoin-core node (v 25.0.0) on a VPS which is also running bwt (v. 0.2.4). I am connecting from my desktop to it via tailscale. When I connect directly to bitcoin-core from Sparrow all is well.

When I try to connect Sparrow to the remote bwt electrum server (via the “Private Electrum” tab in Sparrow’s server settings) it does not work. Below is what Sparrow logs (redacted) when it tries to connect:

```
2023-10-18 15:14:37,015 WARN [Thread-25] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 8 secs
2023-10-18 15:14:38,054 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
com.sparrowwallet.sparrow.net.ElectrumServerRpcException: Error getting fee rate histogram
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.getFeeRateHistogram(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.net.ElectrumServer.getMempoolRateSizes(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	... 12 common frames omitted
Caused by: java.lang.IllegalStateException: I/O error during a request processing
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeRequest(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeAndConvert(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.lambda$getFeeRateHistogram$13(Unknown Source)
	... 13 common frames omitted
Caused by: java.io.IOException: Error reading response: Could not connect to server at tcp://<tailscale VPS address>:50001
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.net.TcpTransport.readResponse(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.net.TcpTransport.pass(Unknown Source)
	... 17 common frames omitted
Caused by: java.io.IOException: Could not connect to server at tcp://<tailscale VPS address>:50001
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.net.TcpTransport.readInputStream(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	... 1 common frames omitted
````

At the same time, bwt on the vps does log the attempt and throws this error:

````
INFO  bwt::electrum > [<tailscale desktop address>:58150] connected peer
thread 'peer' panicked at 'called `Option::unwrap()` on a `None` value', src/util/mod.rs:33:45
````

Not sure if this is a Sparrow issue or a bwt issue, but when I connect to the same bwt from an electrum wallet on the same desktop it seems to work fine.

**Comment by PrinceOfEgypt** [comment]
It's a bwt issue, I had the same problem. Build bwt from source instead of using the latest binary, as the issue has been fixed in the code but no new release was put out.

**Comment by craigraw** [comment]
Closing as a BWT issue. BWT is no longer maintained afaik - you may be better off using Sparrow's builtin replacement for bwt by connecting it directly to Bitcoin Core.

**Comment by PrinceOfEgypt** [comment]
> Closing as a BWT issue. BWT is no longer maintained afaik - you may be better off using Sparrow's builtin replacement for bwt by connecting it directly to Bitcoin Core.

I tried for several days to get the direct connection to bitcoin core working but I would always have the same issue - sparrow would connect the first time and create the "cormorant" wallet in core, import all of the descriptors and core would rescan. After that is done, nothing I do would ever let sparrow connect - it would freeze on "connecting" for hours and never connect.

**Comment by craigraw** [comment]
Have you tried with v1.7.9? There was a workaround for a Core bug recently added.

**Comment by craigraw** [comment]
Consider opening an issue with the relevant details, including logs from Sparrow and Bitcoin Core. You may need to turn on DEBUG logging.
