### ISSUE TITLE
error message spam on system without usb controller

### ISSUE THREAD

**Issue by Hoernchen** [sparrowwallet/sparrow#1153]
The system has no usb controller and therefore no usb devices, this leads to this log "spam":

```2023-11-08 07:52:17,279 ERROR Error executing hwi-2.3.1
  java.io.IOException: Traceback (most recent call last):
  File "hwi.py", line 7, in <module>
  File "hwilib/_cli.py", line 304, in main
  File "hwilib/_cli.py", line 270, in process_commands
  File "hwilib/_cli.py", line 63, in enumerate_handler
  File "hwilib/commands.py", line 117, in enumerate
  File "hwilib/devices/trezor.py", line 855, in enumerate
  File "hwilib/devices/trezorlib/transport/webusb.py", line 115, in enumerate
  File "usb1/__init__.py", line 2176, in open
  File "usb1/__init__.py", line 127, in mayRaiseUSBError
  File "usb1/__init__.py", line 119, in raiseUSBError
  usb1.USBErrorOther: LIBUSB_ERROR_OTHER [-99]
  [7763] Failed to execute script 'hwi' due to unhandled exception!
  
  at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.getProcessOutput(Unknown Source)
  at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.execute(Unknown Source)
  at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.enumerateUsb(Unknown Source)
  at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi.enumerate(Unknown Source)
  at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
  at com.sparrowwallet.sparrow@1.7.9/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
  at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
  at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
  at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
  at java.base/java.security.AccessController.doPrivileged(Unknown Source)
  at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  at java.base/java.lang.Thread.run(Unknown Source)```

This should probably be handled in a slightly less dramatic way.

**Comment by craigraw** [comment]
Hardware wallet enumeration will only occur if a wallet with keystore of type Connected Hardware Wallet is loaded.

My suggestion for this system is to edit Sparrow's config file (close the app first) and set the value of `enumerateHwPeriod` to a much higher value - it is set to 30 seconds by default. Otherwise, you can simply recreate the wallet as type Watch Only - for example by copying the output descriptor.
