### ISSUE TITLE
Unit test com.sparrowwallet.sparrow.io.ColdcardMultisigTest fails on build

### ISSUE THREAD

**Issue by Strunzdesign** [sparrowwallet/sparrow#1154]
Hi,

for some weeks now, "./gradlew build" succeeds building but fails with one unit test. This worked before, so I could bisect the commit that introduced this. Today I tried again with both openjdk-bin 18.0.1_p10 and 19.0.2_p7. Both builds end up with the same unit test failure, tested with a fresh git clone each:

importWalletMultiDeriv
```
org.junit.ComparisonFailure: expected:<...1,coldcard2,coldcard[3]))> but was:<...1,coldcard2,coldcard[]))>
	at junit@4.13.1/org.junit.Assert.assertEquals(Assert.java:117)
	at junit@4.13.1/org.junit.Assert.assertEquals(Assert.java:146)
	at com.sparrowwallet.sparrow@1.7.10/com.sparrowwallet.sparrow.io.ColdcardMultisigTest.importWalletMultiDeriv(ColdcardMultisigTest.java:93)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at junit@4.13.1/org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at junit@4.13.1/org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at junit@4.13.1/org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at junit@4.13.1/org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at junit@4.13.1/org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at junit@4.13.1/org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at junit@4.13.1/org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at junit@4.13.1/org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at junit@4.13.1/org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at junit@4.13.1/org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at junit@4.13.1/org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at junit@4.13.1/org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at junit@4.13.1/org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at junit@4.13.1/org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at junit@4.13.1/org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at junit@4.13.1/org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at junit@4.13.1/org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:39)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

Any inputs I could provide to help you to trace this?

Regards,
Florian

**Comment by craigraw** [comment]
Thanks for reporting - I skipped this test when committing https://github.com/sparrowwallet/drongo/commit/2b7b650faeeeda7fc25ab0962a6132e6531ced4c.

Now fixed in https://github.com/sparrowwallet/drongo/commit/28551247c699c79561180dfe1c2b02db2b742a27.
