### ISSUE TITLE
Reopening Issue #1163 about the send screen not working 

### ISSUE THREAD

**Issue by RobertoPenwell** [sparrowwallet/sparrow#1168]
2023-11-19 22:00:06,347 ERROR [JavaFX Application Thread] c.s.s.SparrowWallet [null:-1] Exception in thread "JavaFX Application Thread"
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at java.base/java.util.ImmutableCollections$List12.indexOf(Unknown Source)
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.contains(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.wallet.SendController.getPreferredOptimizationStrategy(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.wallet.SendController.setPreferredOptimizationStrategy(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.wallet.SendController.initializeView(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.wallet.WalletFormController.setWalletForm(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.wallet.WalletController.lambda$initializeView$0(Unknown Source)
	at javafx.base@18/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleGroup$3.set(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleGroup$3.set(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleGroup.selectToggle(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleButton$1.invalidated(Unknown Source)
	at javafx.base@18/javafx.beans.property.BooleanPropertyBase.markInvalid(Unknown Source)
	at javafx.base@18/javafx.beans.property.BooleanPropertyBase.set(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleButton.setSelected(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleButton.fire(Unknown Source)
	at javafx.controls@18/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at javafx.controls@18/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@18/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@18/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@18/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@18/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@18/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-11-19 22:00:07,472 ERROR [JavaFX Application Thread] c.s.s.SparrowWallet [null:-1] Exception in thread "JavaFX Application Thread"
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at java.base/java.util.ImmutableCollections$List12.indexOf(Unknown Source)
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.contains(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.wallet.SendController.getPreferredOptimizationStrategy(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.wallet.SendController.setPreferredOptimizationStrategy(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.wallet.SendController.initializeView(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.wallet.WalletFormController.setWalletForm(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.wallet.WalletController.lambda$initializeView$0(Unknown Source)
	at javafx.base@18/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleGroup$3.set(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleGroup$3.set(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleGroup.selectToggle(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleButton$1.invalidated(Unknown Source)
	at javafx.base@18/javafx.beans.property.BooleanPropertyBase.markInvalid(Unknown Source)
	at javafx.base@18/javafx.beans.property.BooleanPropertyBase.set(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleButton.setSelected(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.wallet.WalletController.lambda$initializeView$0(Unknown Source)
	at javafx.base@18/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleGroup$3.set(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleGroup$3.set(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleGroup.clearSelectedToggle(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleButton$1.invalidated(Unknown Source)
	at javafx.base@18/javafx.beans.property.BooleanPropertyBase.markInvalid(Unknown Source)
	at javafx.base@18/javafx.beans.property.BooleanPropertyBase.set(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleButton.setSelected(Unknown Source)
	at javafx.controls@18/javafx.scene.control.ToggleButton.fire(Unknown Source)
	at javafx.controls@18/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at javafx.controls@18/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@18/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@18/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@18/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@18/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@18/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by craigraw** [comment]
Already fixed, see original issue.
