### ISSUE TITLE
Can't connect sparrow wallet.

### ISSUE THREAD

**Issue by RickW1212** [sparrowwallet/sparrow#1180]
Unable to connect Sparrow Wallet to Bitcoin Core using Tails OS on thumbdrive iall running wireless on laptop. Data is pruned to 2 gb. Here is log of last connection attempt. Any help greatly appreciated. Out of idea's.

amnesia@amnesia:~$ Persistent/Sparrow/bin/Sparrow ~/Persistent/Sparrow/data
2023-11-26 23:44:13,640 ERROR Connection error
java.lang.IllegalStateException: I/O error during request processing
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.ObjectApiBuilder.execute(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.ObjectApiBuilder.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy15.getNetworkInfo(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.net.cormorant.bitcoind.BitcoindClient.initialize(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.net.cormorant.Cormorant.start(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.0/com.sparrowwallet.sparrow.net.cormorant.bitcoind.BitcoindTransport.pass(Unknown Source)
	... 15 common frames omitted

**Comment by craigraw** [comment]
Did you resolve this as per the chat?

**Comment by RickW1212** [comment]
No, still unsolved.

**Comment by craigraw** [comment]
Tails is probably blocking the connection - all non-Tor connections are blocked by default. I don't believe this is a Sparrow bug, so closing this issue.

See https://web.archive.org/web/20230330153803/https://sovrnbitcoiner.com/sparrow-wallet-and-tails/

**Comment by RickW1212** [comment]
Bit confusing Craig, this article says it works with tails and I am on the Tor network so it shouldn't be blocked ? I still need to read further, maybe make sense yet

**Comment by RickW1212** [comment]
Hello Craig, I have a Tor connection so should not be blocked. So maybe it is a sparrow bug. You don't seem to want to pursue this in the least. Makes me wonder why you bothered replying. I am set up as the article suggests that you supplied. Makes no sense.

**Comment by craigraw** [comment]
Are you connecting to Bitcoin Core over Tor? - i.e. via an onion address, or to an internet-accessible IP address?

See https://sparrowwallet.com/docs/faq.html#how-does-the-proxy-support-work - Sparrow does not use Tor to reach local IPs, as this would always fail.

> You don't seem to want to pursue this in the least. Makes me wonder why you bothered replying.

You have mistaken Github for a support forum - it's not, it's a place for bugs and feature requests. Be aware I am drawing on many years of experience when I say I do not believe this is a bug.

**Comment by RickW1212** [comment]
Hello Craig, 
Apologize for the rant. I was at the end of my rope with trying to get it to work and I was in the wrong place looking for support. Never seen this message till later and didn't know how to reach you outside of GitHub. 
Rick

**Comment by craigraw** [comment]
No worries.

My suggestion is to use an Electrum server on a .onion address if you are using Tails. Exposing Bitcoin Core to an internet accessible address is not advisable for both privacy and performance reasons.
