### ISSUE TITLE
Cannot connect to Public Servers

### ISSUE THREAD

**Issue by szamy1** [sparrowwallet/sparrow#1192]
I cannot connect to the public Mainnet or Testnet servers on macOS. And I also can't get exchange rates. In the 'server preferences' the public servers give 'Could not connect: Broken pipe' message after clicking on Test Connection. On the main sparrow screen, I see 'Connection failed: Socket Error (Broken pipe)' message at the bottom. The Mainnet Private Electrum server still works through Tor.

![Screenshot 2023-12-03 at 08 31 47](https://github.com/sparrowwallet/sparrow/assets/24989564/fd86ea62-1220-45cd-9c51-684e69fbec4b)
![Screenshot 2023-12-03 at 08 32 24](https://github.com/sparrowwallet/sparrow/assets/24989564/31266bd6-e04e-4ad5-a7c4-468d3b998726)

2023-12-03 08:30:00,657 WARN [Thread-4] javafx [null:-1] Timeout while waiting for app reactivation
2023-12-03 08:31:07,315 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
com.sparrowwallet.sparrow.net.ServerException: java.net.SocketException: Broken pipe
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.TcpTransport.connect(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.ElectrumServer.connect(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Broken pipe
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.write(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl$2.write(Unknown Source)
	at java.base/java.net.Socket$SocketOutputStream.write(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketOutputRecord.flush(Unknown Source)
	at java.base/sun.security.ssl.HandshakeOutStream.flush(Unknown Source)
	at java.base/sun.security.ssl.ClientHello$ClientHelloKickstartProducer.produce(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.kickstart(Unknown Source)
	at java.base/sun.security.ssl.ClientHandshakeContext.kickstart(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.kickstart(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.TcpOverTlsTransport.startHandshake(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.TcpOverTlsTransport.createSocket(Unknown Source)
	... 12 common frames omitted
2023-12-03 08:31:14,612 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
com.sparrowwallet.sparrow.net.ServerException: java.net.SocketException: Broken pipe
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.TcpTransport.connect(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.ElectrumServer.connect(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Broken pipe
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.write(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl$2.write(Unknown Source)
	at java.base/java.net.Socket$SocketOutputStream.write(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketOutputRecord.flush(Unknown Source)
	at java.base/sun.security.ssl.HandshakeOutStream.flush(Unknown Source)
	at java.base/sun.security.ssl.ClientHello$ClientHelloKickstartProducer.produce(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.kickstart(Unknown Source)
	at java.base/sun.security.ssl.ClientHandshakeContext.kickstart(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.kickstart(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.TcpOverTlsTransport.startHandshake(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.TcpOverTlsTransport.createSocket(Unknown Source)
	... 12 common frames omitted
2023-12-03 08:31:20,606 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
com.sparrowwallet.sparrow.net.ServerException: java.net.SocketException: Broken pipe
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.TcpTransport.connect(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.ElectrumServer.connect(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Broken pipe
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.write(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl$2.write(Unknown Source)
	at java.base/java.net.Socket$SocketOutputStream.write(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketOutputRecord.flush(Unknown Source)
	at java.base/sun.security.ssl.HandshakeOutStream.flush(Unknown Source)
	at java.base/sun.security.ssl.ClientHello$ClientHelloKickstartProducer.produce(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.kickstart(Unknown Source)
	at java.base/sun.security.ssl.ClientHandshakeContext.kickstart(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.kickstart(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.TcpOverTlsTransport.startHandshake(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.TcpOverTlsTransport.createSocket(Unknown Source)
	... 12 common frames omitted
2023-12-03 08:32:03,433 WARN [Thread-12] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException)
2023-12-03 08:32:13,522 ERROR [Thread-30] c.s.s.n.VersionCheckService [null:-1] Error retrieving version check file
java.io.IOException: com.samourai.wallet.api.backend.beans.HttpException: java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.VersionCheckService.getVersionCheck(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.VersionCheckService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.VersionCheckService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.samourai.wallet.api.backend.beans.HttpException: java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.HttpClientService.requestJson(Unknown Source)
	... 11 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.util.FutureResponseListener.getResult(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.sparrowwallet.nightjar.http.JavaHttpClient.makeRequest(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJsonGet(Unknown Source)
	... 14 common frames omitted
Caused by: org.eclipse.jetty.io.EofException: null
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.ChannelEndPoint.flush(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.WriteFlusher.flush(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.WriteFlusher.write(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.AbstractEndPoint.write(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.http.HttpSenderOverHTTP$HeadersCallback.process(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.util.IteratingCallback.processing(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.util.IteratingCallback.iterate(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.http.HttpSenderOverHTTP.sendHeaders(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.HttpSender.send(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.http.HttpChannelOverHTTP.send(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.HttpChannel.send(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.HttpConnection.send(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.HttpDestination.process(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.HttpDestination.process(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.HttpDestination.send(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.HttpDestination.succeeded(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.AbstractConnectionPool.proceed(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.AbstractConnectionPool$1.succeeded(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.AbstractConnectionPool$1.succeeded(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.util.Promise$Wrapper.succeeded(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onOpen(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.ssl.SslConnection.onOpen(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.SelectorManager.connectionOpened(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.ManagedSelector.createEndPoint(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.ManagedSelector.access$1900(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(Unknown Source)
	... 1 common frames omitted
Caused by: java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.write(Unknown Source)
	... 33 common frames omitted
2023-12-03 08:32:14,719 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
com.sparrowwallet.sparrow.net.ServerException: java.net.SocketException: Socket is not connected
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.TcpTransport.connect(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.ElectrumServer.connect(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Socket is not connected
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.TcpOverTlsTransport.startHandshake(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.net.TcpOverTlsTransport.createSocket(Unknown Source)
	... 12 common frames omitted
2023-12-03 08:37:03,255 WARN [Thread-76] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException)
2023-12-03 08:38:00,214 WARN [Thread-91] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException)
2023-12-03 08:38:00,243 WARN [Thread-100] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException)
2023-12-03 08:38:02,683 WARN [Thread-109] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException)
2023-12-03 08:38:02,701 WARN [Thread-118] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException)
2023-12-03 08:38:09,380 WARN [Thread-129] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException)
2023-12-03 08:38:09,395 WARN [Thread-138] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException)
2023-12-03 08:38:17,185 WARN [Thread-147] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException)
2023-12-03 08:38:17,208 WARN [Thread-156] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException)
2023-12-03 08:43:17,416 WARN [Thread-196] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException)

**Comment by craigraw** [comment]
You are experiencing some kind of the network issue external to Sparrow. Because this is happening across multiple servers, it is unlikely to be the server, and probably something to do with your local network or internet connection. Try another internet connection if possible to isolate the issue.

**Comment by MigGib** [comment]
Was this issue solved? Have the same problems and do not find the solution

**Comment by szamy1** [comment]
> Was this issue solved? Have the same problems and do not find the solution

It was indeed some kind of issue external to Sparrow. I spent some days cleaning my macOS, like cleaning homebrew- and Python-related packages. I'm not sure what caused the problem, but it was solved at some point.
