### ISSUE TITLE
SatoChip: arraycopy last source index 32 out of bounds for byte 0

### ISSUE THREAD

**Issue by abradshaw** [sparrowwallet/sparrow#1229]
I recently got a SatoChip device and card and started receiving and sending testnet payments to it.

I have 1 UTXO in the wallet that I cant send - the other 8 I can send. This is only testnet, so not critical

When I sign I get this error (in the subject and the screenshot below)

![Screenshot from 2024-01-13 19-27-58](https://github.com/sparrowwallet/sparrow/assets/404108/5130ad9e-5075-4922-b308-1e5e64dd8e10)

I have signed the transaction as a psbt but can't add it here as its not a supported file format

Let me know which additional info you need - and just to be clear - there is no hurry on this

**Comment by craigraw** [comment]
Please look in the Sparrow log file (see Help menu) and find the full stacktrace of the error. It should be towards the end of the log file.

**Comment by abradshaw** [comment]
Morning

OK yes, the last entry in the file is

```
2024-01-15 08:44:26,251 ERROR [JavaFX Application Thread] c.s.s.c.DevicePane [null:-1] Signing Error: arraycopy: last source index 32 out of bounds for byte[0]
java.lang.RuntimeException: javax.smartcardio.CardException: Error parsing Satochip extended key
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.io.satochip.SatoCardApi$CardPSBTInputSigner.sign(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTInput.sign(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.io.satochip.SatoCardApi.sign(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.io.satochip.SatoCardApi$SignService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.io.satochip.SatoCardApi$SignService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javax.smartcardio.CardException: Error parsing Satochip extended key
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.io.satochip.SatochipParser.parseBip32GetExtendedKey(Unknown Source)
	... 13 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 32 out of bounds for byte[0]
	at java.base/java.lang.System.arraycopy(Native Method)
	... 14 common frames omitted
```

**Comment by craigraw** [comment]
Looks like an invalid response from the card.

@Toporin can you advise?

**Comment by abradshaw** [comment]
Cool, any way I can test or shall I just wait for a new version ?

**Comment by craigraw** [comment]
It's fairly simple to build from source - instructions in the project README. Otherwise next release will be soon.

**Comment by Toporin** [comment]
I made a test release including the patch at the time:
https://github.com/Toporin/sparrow/releases/tag/v1.8.1patch

**Comment by abradshaw** [comment]
Thanks @Toporin - I just grabbed your patched version and I can confirm I was able to move the UTXO

(Thanks for compiling that, I was having issues with building it - something about javaHome not being set - but I shall work that out)

Thanks so much  @craigraw and @Toporin
