### ISSUE TITLE
Error retrieving coinbase currency rates

### ISSUE THREAD

**Issue by anon-dev-gh** [sparrowwallet/sparrow#1235]
* [Url](https://api.coinbase.com/v2/exchange-rates?currency=BTC) works just fine on browser.
* Tested with 1.8.2 but is not a regression error, I think coinbase rates never worked (at least since 1.7.x)
* Connected to my own node via tor

debug log

```
2024-01-20 11:58:33,770 DEBUG [Thread-57] o.e.j.u.s.SslContextFactory [null:-1] Selected Protocols [TLSv1.3, TLSv1.2] of [TLSv1.3, TLSv1.2, TLSv1.1, TLSv1, SSLv3, SSLv2Hello]
2024-01-20 11:58:33,770 DEBUG [Thread-57] o.e.j.u.s.SslContextFactory [null:-1] Selected Ciphers   [TLS_AES_256_GCM_SHA384, TLS_AES_128_GCM_SHA256, TLS_CHACHA20_POLY1305_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_EMPTY_RENEGOTIATION_INFO_SCSV] of [TLS_AES_256_GCM_SHA384, TLS_AES_128_GCM_SHA256, TLS_CHACHA20_POLY1305_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
2024-01-20 11:58:33,771 DEBUG [Thread-57] o.e.j.u.s.SslContextFactory [null:-1] Customize SSLEngine[hostname=null, port=-1, Session(1705748313771|SSL_NULL_WITH_NULL_NULL)]
2024-01-20 11:58:33,771 DEBUG [Thread-57] o.e.j.u.c.ContainerLifeCycle [null:-1] HttpDestination[https://api.coingecko.com]@4be422c2(via 127.0.0.1:9050),queue=0,pool=DuplexConnectionPool@1e98f758[c=0/64,a=0,i=0] added {DuplexConnectionPool@1e98f758[c=0/64,a=0,i=0],POJO}
2024-01-20 11:58:33,771 DEBUG [Thread-57] o.e.j.u.c.ContainerLifeCycle [null:-1] HttpDestination[https://www.sparrowwallet.com]@70d62f95(via 127.0.0.1:9050),queue=0,pool=DuplexConnectionPool@7760dfbd[c=0/64,a=0,i=0] added {DuplexConnectionPool@7760dfbd[c=0/64,a=0,i=0],POJO}
2024-01-20 11:58:33,771 DEBUG [Thread-57] o.e.j.u.c.ContainerLifeCycle [null:-1] HttpDestination[http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion]@10d565dd(via 127.0.0.1:9050),queue=0,pool=DuplexConnectionPool@2e2dd41e[c=0/64,a=0,i=0] added {DuplexConnectionPool@2e2dd41e[c=0/64,a=0,i=0],POJO}
2024-01-20 11:58:33,771 DEBUG [Thread-57] o.e.j.u.c.ContainerLifeCycle [null:-1] HttpDestination[https://api.coinbase.com]@4e072efd(via 127.0.0.1:9050),queue=0,pool=DuplexConnectionPool@3a59de31[c=0/64,a=0,i=0] added {DuplexConnectionPool@3a59de31[c=0/64,a=0,i=0],POJO}
2024-01-20 11:58:33,771 DEBUG [Thread-57] o.e.j.u.c.ContainerLifeCycle [null:-1] HttpDestination[https://api.coinbase.com]@7df6a7ed(via 127.0.0.1:9050),queue=0,pool=DuplexConnectionPool@6322dc15[c=0/64,a=0,i=0] added {DuplexConnectionPool@6322dc15[c=0/64,a=0,i=0],POJO}
2024-01-20 11:58:33,771 ERROR [Thread-57] c.s.h.c.JacksonHttpClient [null:-1] getJson failed: https://api.coinbase.com/v2/exchange-rates?currency=BTC:java.lang.Exception: Http query failed: status=403
2024-01-20 11:58:33,771 WARN [Thread-57] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates
com.sparrowwallet.nightjar.http.JavaHttpException: java.lang.Exception: Http query failed: status=403
	at com.sparrowwallet.nightjar@0.2.39/com.sparrowwallet.nightjar.http.JavaHttpClient.makeRequest(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJsonGet(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.HttpClientService.requestJson(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.ExchangeSource$2.getRates(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.ExchangeSource$2.getExchangeRate(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.ExchangeSource$RatesService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.ExchangeSource$RatesService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Exception: Http query failed: status=403
	... 17 common frames omitted
```

**Comment by craigraw** [comment]
Unfortunately Coinbase tends to block Tor exit nodes with a 403 (Forbidden) response. Since they do not provide an onion address, there's not much Sparrow can do about this. If you don't use Tor, you'll find it works fine.

**Comment by anon-dev-gh** [comment]
Thanks @craigraw  that makes sense. What do you think about a switch or something to optionally obtain rates via clearnet? Just as suggestion

**Comment by craigraw** [comment]
You can switch to Coingecko, which works over Tor.
