### ISSUE TITLE
Failing to sign tx with Ledger Nano S

### ISSUE THREAD

**Issue by olafmarcos** [sparrowwallet/sparrow#1250]
Leger Nano S fimware 2.1.0 and Bitcoin Test 2.2.0-rc
Sparrow 1.8.2
New wallet generated in Sparrow.

At the time of signing, the Bitcoin Test app on the device (Ledger) close and the next error on Sparrow log:

ERROR [JavaFX Application Thread] c.s.s.c.DevicePane [null:-1] Signing Error: read error
com.sparrowwallet.sparrow.io.SignTransactionException: read error
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.io.Hwi.signPSBT(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by craigraw** [comment]
It appears that something is going wrong on the device itself, or in transferring the data from the device to the computer. You may want to try update the driver for example https://support.ledger.com/hc/en-us/articles/4405542078353-Windows-doesn-t-recognize-my-Ledger-device?support=true

**Comment by olafmarcos** [comment]
Thanks @craigraw .

Latest drivers. I have also a Nano X that sign tx correctly.
I tested the Nano S on Electrum and Ledger Live and same behaviour. Opened support ticket with Ledger.
Keep you informed!

**Comment by olafmarcos** [comment]
Bug on Ledger Bitcoin Test app version 2.2.0rc
Fixed on new 2.2.0rc2

Thank you. Ticket can be closed.

**Comment by craigraw** [comment]
Thank you for testing the RC and reporting the bug! Saved a lot of trouble for many people for sure.
