### ISSUE TITLE
Error executing HWI - F39 Silverblue

### ISSUE THREAD

**Issue by alex27riva** [sparrowwallet/sparrow#1263]
Hi everyone, I'm on Fedora 39 Silverblue and I'm using the latest version of Sparrow (1.8.2).
I'm running Sparrow binary extracted from the tar.gz file.
I have this error when trying to connect my hardware wallet:

![hwi-error](https://github.com/sparrowwallet/sparrow/assets/5512235/8f405783-b5b0-4c0d-80cf-1d4d6f0cdcc3)

Here's the stack trace:
```
2024-02-11 15:29:14,770 ERROR Error executing hwi-2.3.1
java.io.IOException: [5519] Error loading Python lib '/tmp/_MEIwXyyyE/libpython3.9.so.1.0': dlopen: libcrypt.so.1: cannot open shared object file: No such file or directory

	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.io.Hwi.getProcessOutput(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.io.Hwi.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.io.Hwi.enumerateUsb(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.io.Hwi.enumerate(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2024-02-11 15:30:05,873 ERROR Error executing hwi-2.3.1
java.io.IOException: [5532] Error loading Python lib '/tmp/_MEIaqX8t9/libpython3.9.so.1.0': dlopen: libcrypt.so.1: cannot open shared object file: No such file or directory

```

Obviously the file is not existent, but why the library is searched in the `/tmp` folder?

**Comment by craigraw** [comment]
> Obviously the file is not existent, but why the library is searched in the /tmp folder?

The reason for the `/tmp` folder is that HWI uses pyinstaller, which extracts a new executable to a temporary folder every time it runs. It's not searching for `libcrypt` in the `/tmp` folder, but libcrypt is a dependency that `libpython3.9` is looking for from the `/tmp` folder where it was extracted.

It looks like you'll need to install `libcrypt` separately. See https://support.oneidentity.com/safeguard-authentication-services/kb/4259532/fedora-32-error-opt-quest-bin-vastool-error-while-loading-shared-libraries-libcrypt-so-1-cannot-open-shared-object-file-no-such-file-or-directory for example.

**Comment by alex27riva** [comment]
Thank you for your response.
I fixed by installing `libxcrypt-compat` inside the toolbox (since Silverblue is an immutable system) using `sudo dnf install libxcrypt-compat` and running Sparrow inside the toolbox.
The hardware wallet is working fine since I was able to sign a message with Sparrow.
