### ISSUE TITLE
Exchange rates sometimes do not load

### ISSUE THREAD

**Issue by PrinceOfEgypt** [sparrowwallet/sparrow#1276]
There is an intermittent issue where exchange rates do not load when you start sparrow and no fiat value is displayed:

![image](https://github.com/sparrowwallet/sparrow/assets/2649235/47fee711-e74e-4eb4-8f6a-978b02f9d1cd)

if you leave sparrow running for 5 minutes it will eventually load:

![image](https://github.com/sparrowwallet/sparrow/assets/2649235/29d8a6eb-9376-4e83-b8f9-866fb6376142)

when the issue occurs the following error is logged in sparrow.log (running in debug mode):

2024-02-21 14:20:44,700 WARN [Thread-7] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates
com.samourai.wallet.api.backend.beans.HttpException: java.util.concurrent.ExecutionException: java.util.concurrent.RejectedExecutionException: HttpClient@1ed271cf{STOPPING} is stopped
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.HttpClientService.requestJson(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.ExchangeSource$3.getRates(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.ExchangeSource$3.getExchangeRate(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.ExchangeSource$RatesService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.ExchangeSource$RatesService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.RejectedExecutionException: HttpClient@1ed271cf{STOPPING} is stopped
	at com.sparrowwallet.merged.module@1.8.2/org.eclipse.jetty.client.util.FutureResponseListener.getResult(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.2/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.2/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.sparrowwallet.nightjar.http.JavaHttpClient.makeRequest(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJsonGet(Unknown Source)
	... 15 common frames omitted
Caused by: java.util.concurrent.RejectedExecutionException: HttpClient@1ed271cf{STOPPING} is stopped
	at com.sparrowwallet.merged.module@1.8.2/org.eclipse.jetty.client.HttpDestination.send(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.2/org.eclipse.jetty.client.HttpDestination.send(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.2/org.eclipse.jetty.client.HttpClient.send(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.2/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	... 18 common frames omitted

**Comment by PrinceOfEgypt** [comment]
Spent some time messing around in the debugger, this appears to be a concurrency issue - I submitted a PR that helped, but I'm not certain if it's the "best" way to solve the problem.
