### ISSUE TITLE
Error retrieving wallet history. Personal Electrum server with Tor

### ISSUE THREAD

**Issue by afahrer** [sparrowwallet/sparrow#1283]
![image](https://github.com/sparrowwallet/sparrow/assets/44128447/397e15de-bf77-410b-83d1-e0195bcffc3e)

![image](https://github.com/sparrowwallet/sparrow/assets/44128447/32e668a4-9513-4dbc-84c6-b62649e70f65)

2024-02-24 14:19:47,194 ERROR [JavaFX Application Thread] c.s.s.w.WalletForm [null:-1] Error retrieving wallet history
com.sparrowwallet.sparrow.net.ServerException: Failed to subscribe to paths: [m/0/0-m/0/40]
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.ElectrumServer.subscribeWalletNodes(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.ElectrumServer.getHistory(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.ElectrumServer.getHistory(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService.getTransactionHistory(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.PagedBatchRequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.PagedBatchRequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.2/com.sparrowwallet.sparrow.net.BatchedElectrumServerRpc.subscribeScriptHashes(Unknown Source)
	... 14 common frames omitted
Caused by: java.lang.IllegalStateException: Unspecified id: '92' in response
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.processSingleResponse(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.processBatchResponse(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.execute(Unknown Source)
	... 18 common frames omitted

Sparrow 1.8.2, Windows 11
Start9 Personal Electrum server over Tor.

Server connection is successful and then wallet fails to load. Issue is intermittent.

**Comment by craigraw** [comment]
This is an issue for the EPS repo, not Sparrow. `Unspecified id: '92' in response` means the server is sending a response that the client (Sparrow) did not request. It may be a response from a much earlier request from a previous session - it's hard to say with this information. 

You may want to try Sparrow's builtin functionality to connect to Bitcoin Core, which does the same work as EPS, but uses more modern descriptor wallets.

**Comment by urosino** [comment]
@craigraw thank you for your input. 

I am having the same issue related to the inconsistent connection with the private electrum setup (randomly dropping). 

Do you believe there is something a user can do, or just wait for EPS to address it?

Public Server setup works fine.

**Comment by craigraw** [comment]
Rereading this - I think the OP was using Electrs and not EPS. 

Unfortunately Electrs does not scale well. Try upgrading it/restarting it. 

If that doesn't work, switch to Fulcrum, which is much better.

**Comment by urosino** [comment]
@craigraw - this now makes perfect sense as I am also using Electrs not EPS.

Thank you for your contribution. Respect.

**Comment by afahrer** [comment]
Thanks for the info @craigraw yes I'm using electrs. Will definitely check out Fulcrum.
