### ISSUE TITLE
Sparrow Server 1.8.3 throws a ClassNotFound Exception on my Debian

### ISSUE THREAD

**Issue by BtcAutoNode** [sparrowwallet/sparrow#1298]
Starting Sparrow Server via 'Sparrow' I get the following exception:
![grafik](https://github.com/sparrowwallet/sparrow/assets/149917291/04702043-5789-4c75-b880-4d48cc2a1d8d)

I used sparrow-server-1.8.3-x86_64.tar.gz and sparrow-server_1.8.3-1_amd64.deb and tried different java versions.
The previous versions worked quite well.

java.lang.ClassNotFoundException: com.sun.glass.ui.monocle.MonoclePlatformFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at java.base/java.lang.Class.forName(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.PlatformFactory.getPlatformFactory(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.Application.run(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.startup(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Failed to load Glass factory class
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.sun.glass.ui.PlatformFactory.createApplication()" because the return value of "com.sun.glass.ui.PlatformFactory.getPlatformFactory()" is null
	at javafx.graphics@18/com.sun.glass.ui.Application.run(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.startup(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by craigraw** [comment]
Thanks for reporting, fixed in 2d5e2436. New release will be out soon.
