### ISSUE TITLE
Cannot Connect Trezor T

### ISSUE THREAD

**Issue by The-Last-Resort123** [sparrowwallet/sparrow#1345]
It's been days. I've scoured the internet and forum for ways to this to work. Demos online seem so easy; plug in the trezor, enter your pin to unlock, click connected hardware wallet, then scan and it finds the Trezor. Mine will not pop up. I've rebooted, restarted sparrow 100 times, unplugged and replugged the Trezor, etc. A few variation in results:
1. If I enter the pin and unlock it before clicking connected hardware wallet, I will then hit scan and it will tell me to check my device. On the Trezor screen are 4 pages of text entry for the passphrase. Afterwards nothing happens. Sparrow continues to tell me it's scanning and please check your device. There is nothing on the device except the wallpaper. 
2. I can't seem to duplicate the error again, but in at least one instance I got the HWI error that I've seen posted in some other threads. Restarting, unplugging, rebooting leads me back to issue 1 above. I've seen exact log elsewhere, but their fixes didn't help me. Hopefully someone can! I've even tried two different Trezors, one being a new one and the other having a balance. 

2024-03-27 11:49:36,332 ERROR [Thread-22] c.s.s.i.Hwi [null:-1] Error executing hwi-2.4.0
java.io.IOException: Traceback (most recent call last):
  File "hwi.py", line 7, in <module>
  File "hwilib\_cli.py", line 304, in main
  File "hwilib\_cli.py", line 270, in process_commands
  File "hwilib\_cli.py", line 63, in enumerate_handler
  File "hwilib\commands.py", line 117, in enumerate
  File "hwilib\devices\trezor.py", line 857, in enumerate
  File "hwilib\devices\trezorlib\transport\webusb.py", line 130, in enumerate
  File "usb1\__init__.py", line 2003, in getProduct
  File "usb1\__init__.py", line 2055, in open
  File "usb1\__init__.py", line 127, in mayRaiseUSBError
  File "usb1\__init__.py", line 119, in raiseUSBError
usb1.USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]
[23332] Failed to execute script 'hwi' due to unhandled exception!

	at com.sparrowwallet.sparrow@1.8.4/com.sparrowwallet.sparrow.io.Hwi.getProcessOutput(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.4/com.sparrowwallet.sparrow.io.Hwi.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.4/com.sparrowwallet.sparrow.io.Hwi.enumerateUsb(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.4/com.sparrowwallet.sparrow.io.Hwi.enumerate(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.4/com.sparrowwallet.sparrow.io.Hwi$EnumerateService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.4/com.sparrowwallet.sparrow.io.Hwi$EnumerateService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by The-Last-Resort123** [comment]
This was solved finally by removing the Acronis program.

**Comment by craigraw** [comment]
> This was solved finally by removing the Acronis program

A fix for this in HWI is being actively worked on, see https://github.com/bitcoin-core/HWI/issues/653
