### ISSUE TITLE
Cannot connect Trezor Model One to Sparrow

### ISSUE THREAD

**Issue by atticusdaddy** [sparrowwallet/sparrow#1372]
Just recently followed the raspibolt guide and have a node + electrs setup and have Sparrow wallet connected to electrs so I have the blue connection. 

I saw that there was a similar issue for this but, I'm using Linux Mint 21. The other issues are on Mac so I figured I'd make a post. 

Steps to recreate:
I plugged in my Trezor Model one, File>New Wallet. Named the wallet and clicked on connected hardware wallet. When I go to scan it says there is an error. When I look at the log this is what I get.

2024-04-11 14:49:16,910 ERROR [Thread-22] c.s.s.i.Hwi [null:-1] Error executing hwi-3.0.0
java.io.IOException: Traceback (most recent call last):
  File "hwi.py", line 7, in <module>
  File "hwilib/_cli.py", line 305, in main
  File "hwilib/_cli.py", line 271, in process_commands
  File "hwilib/_cli.py", line 63, in enumerate_handler
  File "hwilib/commands.py", line 117, in enumerate
  File "hwilib/devices/trezor.py", line 857, in enumerate
  File "hwilib/devices/trezorlib/transport/webusb.py", line 130, in enumerate
  File "usb1/__init__.py", line 2003, in getProduct
  File "usb1/__init__.py", line 2055, in open
  File "usb1/__init__.py", line 127, in mayRaiseUSBError
  File "usb1/__init__.py", line 119, in raiseUSBError
usb1.USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]
[36332] Failed to execute script 'hwi' due to unhandled exception!

	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.io.Hwi.getProcessOutput(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.io.Hwi.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.io.Hwi.enumerateUsb(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.io.Hwi.enumerate(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Please let me know what I should do. I do have another USB plugged into a KVM switch for my keyboard and mouse. I tried unplugging this and redid it and same error. 

Thanks,

**Comment by craigraw** [comment]
Usually this is a temporary error, but if you are experiencing it consistently there may be something else wrong. Did you install udev rules? See the Tools menu.
