### ISSUE TITLE
Crash on signet startup

### ISSUE THREAD

**Issue by pythcoiner** [sparrowwallet/sparrow#1385]
Just updated to the last version from AUR (1.8.5), i got Sparrow to crash if i want to launch w/ signet mode (tryed bot fron GUI and CLI):

```
❯ Sparrow -n signet                                                                                00:15:23
Exception in Application start method
Exception in Application stop method
2024-04-16 00:16:56,560 ERROR Exception in thread "main"
java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics@18/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
        at javafx.graphics@18/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No enum constant com.samourai.wallet.constants.SamouraiNetwork.SIGNET
        at java.base/java.lang.Enum.valueOf(Unknown Source)
        at com.samourai.extlibj@1.0.6/com.samourai.wallet.constants.SamouraiNetwork.valueOf(Unknown Source)
        at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.whirlpool.WhirlpoolServices.getSamouraiNetwork(Unknown Source)
        at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.whirlpool.WhirlpoolServices.computeExtLibJConfig(Unknown Source)
        at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.whirlpool.WhirlpoolServices.<init>(Unknown Source)
        at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.AppServices.<init>(Unknown Source)
        at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.AppServices.initialize(Unknown Source)
        at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.SparrowDesktop.start(Unknown Source)
        at javafx.graphics@18/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
        at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
        at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
        at javafx.graphics@18/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
        ... 1 common frames omitted
~ ❯ Sparrow --version                                                                                00:16:56
Sparrow Wallet 1.8.5

```

(i got the issue while bitcoind (signet) running or not)

**Comment by craigraw** [comment]
Thanks for the bug report, this was fixed in https://github.com/sparrowwallet/sparrow/commit/9ec5b6ce266bfe49928c2802cd3d5f4e05551fac.

The workarounds for now are to use 1.8.4 or run from source.

**Comment by pythcoiner** [comment]
Thanks i think you are the most reactive dev in bitcoin space :1st_place_medal:
