### ISSUE TITLE
Wallet won't start (or restart) in signet mode

### ISSUE THREAD

**Issue by luisschwab** [sparrowwallet/sparrow#1388]
version: 1.8.5
distribution: sparrow_1.8.5-1_amd64.deb

When launching the wallet in signet mode via GUI `(Tools > Restart In > Signet)`, the wallet will close normally, but won't come back up again.

When launching via CLI with `$ sparrow/bin/Sparrow -n signet`, startup fails and returns this:
```
$ sparrow/bin/Sparrow -n signet

Exception in Application start method
Exception in Application stop method
2024-04-19 09:04:25,393 ERROR Exception in thread "main"
java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics@18/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No enum constant com.samourai.wallet.constants.SamouraiNetwork.SIGNET
	at java.base/java.lang.Enum.valueOf(Unknown Source)
	at com.samourai.extlibj@1.0.6/com.samourai.wallet.constants.SamouraiNetwork.valueOf(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.whirlpool.WhirlpoolServices.getSamouraiNetwork(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.whirlpool.WhirlpoolServices.computeExtLibJConfig(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.whirlpool.WhirlpoolServices.<init>(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.AppServices.<init>(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.AppServices.initialize(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.5/com.sparrowwallet.sparrow.SparrowDesktop.start(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	... 1 common frames omitted
```

**Comment by PrinceOfEgypt** [comment]
FYI this is a duplicate of #1385 - there are solutions / workarounds there.

**Comment by craigraw** [comment]
Closing as duplicate.
