### ISSUE TITLE
Camera V3 not working on Raspberry Pi 5

### ISSUE THREAD

**Issue by scaljeri** [sparrowwallet/sparrow#1521]
I have the official PiOS installed (Debian) and connected the camera module V3. I can see the camera in action with

    $> rpicam-hello -t 10s

The camera also worked with Firefox (not with Chromium)

Now, when I start Sparrow Wallet and create a new wallet and click "Airgapped Hardware Wallet"  -> "Scan" I can see that it tries to open the camera window, but it closes immediately throwing the following error in the terminal:

`(Sparrow:17252): Gdk-WARNING **: 16:09:29.706: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
Unable to get frame rate: 25.
libv4l2: error turning on stream: Invalid argument
2024-10-19 16:09:42,054 ERROR Failed to start web cam
com.github.sarxos.webcam.WebcamException: Cannot execute task
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamProcessor.process(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamTask.process(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.ds.cgt.WebcamOpenTask.open(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.Webcam.open(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.control.WebcamService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.control.WebcamService$1.call(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.github.sarxos.webcam.WebcamException: Cannot start native grabber!
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.control.WebcamScanDevice.open(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.ds.cgt.WebcamOpenTask.handle(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(Unknown Source)
	... 3 common frames omitted
2024-10-19 16:09:42,128 ERROR Error importing QR
com.github.sarxos.webcam.WebcamException: Cannot execute task
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamProcessor.process(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamTask.process(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.ds.cgt.WebcamOpenTask.open(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.Webcam.open(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.control.WebcamService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.control.WebcamService$1.call(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.github.sarxos.webcam.WebcamException: Cannot start native grabber!
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.control.WebcamScanDevice.open(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.ds.cgt.WebcamOpenTask.handle(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(Unknown Source)
	... 3 common frames omitted
` 

I'm using Sparrow 2.0.0. Here are some details of the camera 👍 
`$>v4l2-ctl --device /dev/video0 --all
Driver Info:
	Driver name      : rp1-cfe
	Card type        : rp1-cfe
	Bus info         : platform:1f00128000.csi
	Driver version   : 6.6.51
	Capabilities     : 0xaca00001
		Video Capture
		Metadata Capture
		Metadata Output
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x24a00001
		Video Capture
		Metadata Capture
		Streaming
		Extended Pix Format
Media Driver Info:
	Driver name      : rp1-cfe
	Model            : rp1-cfe
	Serial           : 
	Bus info         : platform:1f00128000.csi
	Media version    : 6.6.51
	Hardware revision: 0x00114666 (1132134)
	Driver version   : 6.6.51
Interface Info:
	ID               : 0x03000017
	Type             : V4L Video
Entity Info:
	ID               : 0x00000015 (21)
	Name             : rp1-cfe-csi2_ch0
	Function         : V4L2 I/O
	Pad 0x01000016   : 0: Sink, Must Connect
	  Link 0x02000037: from remote pad 0x1000006 of entity 'csi2' (Video Interface Bridge): Data
Priority: 2
Video input : 0 (rp1-cfe-csi2_ch0: ok)
Format Video Capture:
	Width/Height      : 1280/720
	Pixel Format      : 'RGB3' (24-bit RGB 8-8-8)
	Field             : None
	Bytes per Line    : 3840
	Size Image        : 2764800
	Colorspace        : Default
	Transfer Function : Default (maps to Rec. 709)
	YCbCr/HSV Encoding: Default (maps to ITU-R 601)
	Quantization      : Default (maps to Full Range)
	Flags             : 
Format Metadata Capture:
	Sample Format   : 'SENS' (Sensor Ancillary Metadata)
	Buffer Size     : 16384
 `

Hope someone understands all this data. Any help would be appreciated!

**Comment by craigraw** [comment]
Have you tried changing the camera resolution? Use the View menu to switch from normal to HD (or vice versa).

**Comment by scaljeri** [comment]
I just noticed that the pulldown menu's do not work too, I even tried to start the wallet as follows

     $> GDK_DISPLAY=1 ./Sparrow

[Source](https://github.com/sparrowwallet/sparrow/issues/170)

**Comment by craigraw** [comment]
> I just noticed that the pulldown menu's do not work too

Can you verify which window manager you are using?

**Comment by scaljeri** [comment]
Sure, this is Wayfire (Debian for Raspberry PI 5, Pi Os)

**Comment by craigraw** [comment]
Are you running XWayland? As the issue you linked to above notes, you'll need XWayland to to run Sparrow on Wayland compositors.

**Comment by scaljeri** [comment]
Yes, it seems I am:

`ps -e | grep Xwayland 3002 ?        00:00:00 Xwayland
`

**Comment by craigraw** [comment]
I am working on replacing the webcam library in Sparrow, and I believe this setup now works, but I would appreciate testing of a pre-release build at https://github.com/craigraw/beta/releases/tag/2.1.4-openpnp-capture.

If you are running a recent version of RPiOS (bookworm), you will need to use it with `libcamerify`:
```
sudo apt install libcamera-v4l2
libcamerify /opt/sparrow/bin/Sparrow
```

Let me know if it works for you.

**Comment by scaljeri** [comment]
l'm indeed using bookworm. So, when I install libcamera-v4l2 and run my Sparrow as you described I get errors when I try to scan a QR via the camera:


`$> libcamerify ~/software/Sparrow/bin/Sparrow

(Sparrow:37086): Gdk-WARNING **: 21:17:12.771: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
2025-03-28 21:17:22,475 ERROR Error executing hwi-3.1.0
java.io.IOException: /tmp/hwi-3.1.0425476513018974915.tmp: /tmp/_MEIjGp1nL/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/aarch64-linux-gnu/libcamera/v4l2-compat.so)
/tmp/hwi-3.1.0425476513018974915.tmp: /tmp/_MEIjGp1nL/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/aarch64-linux-gnu/libcamera/v4l2-compat.so)
/tmp/hwi-3.1.0425476513018974915.tmp: /tmp/_MEIjGp1nL/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/aarch64-linux-gnu/libcamera.so.0.4)
/tmp/hwi-3.1.0425476513018974915.tmp: /tmp/_MEIjGp1nL/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/aarch64-linux-gnu/libcamera.so.0.4)
/tmp/hwi-3.1.0425476513018974915.tmp: /tmp/_MEIjGp1nL/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/aarch64-linux-gnu/libcamera-base.so.0.4)
/tmp/hwi-3.1.0425476513018974915.tmp: /tmp/_MEIjGp1nL/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/aarch64-linux-gnu/libpisp.so.1)
/tmp/hwi-3.1.0425476513018974915.tmp: /tmp/_MEIjGp1nL/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /lib/aarch64-linux-gnu/libpisp.so.1)
/tmp/hwi-3.1.0425476513018974915.tmp: /tmp/_MEIjGp1nL/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /lib/aarch64-linux-gnu/libboost_log.so.1.74.0)
/tmp/hwi-3.1.0425476513018974915.tmp: /tmp/_MEIjGp1nL/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/aarch64-linux-gnu/libboost_log.so.1.74.0)
/tmp/hwi-3.1.0425476513018974915.tmp: /tmp/_MEIjGp1nL/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /lib/aarch64-linux-gnu/libboost_log.so.1.74.0)
...
`

So maybe I do something wrong. Should I  install a different sparrow version? I did verify that my camera did work using Chrome!

**Comment by craigraw** [comment]
This error (`GLIBCXX_3.4.29' not found`) is actually not related to Sparrow at all, but rather that `libcamera-v4l2` is not compatible with your operating system.

Please confirm which Raspberry Pi OS you are running with
```
cat /etc/os-release
```

If you are running bullseye, try enabling the legacy camera stack. To enable legacy camera support in Raspberry Pi OS Bullseye, open a terminal, run `sudo raspi-config`, navigate to "Interface Options", select "Legacy camera", choose "Yes" to enable it, and then reboot. You should then not need to use `libcamerify` at all, avoiding this problem.

**Comment by craigraw** [comment]
I took another look at your errors - are you sure you are running the Sparrow downloaded from https://github.com/craigraw/beta/releases/tag/2.1.4-openpnp-capture? 

It looks like you are running an earlier version of Sparrow - perhaps 2.0.0. You can check with 
```
~/software/Sparrow/bin/Sparrow -v
```

**Comment by scaljeri** [comment]
Yes, that did the trick, with 2.1.4 it works (not with 2.1.3) and I was indeed running 2.0.0 :) 
Thnx

**Comment by craigraw** [comment]
Good news :) Closing this off.
