### ISSUE TITLE
Restart mixing does not work

### ISSUE THREAD

**Issue by Emissio** [sparrowwallet/sparrow#1526]
Hi,

Earlier this year, I started to use Whirlpool to mix UTXOs in my Sparrow wallet. I stopped mixing for a while and now I struggle to restart mixing or mix to cold storage.

When I upgrade to Sparrow 2.0.0, I cannot see the options “Start Mixing” and “Mixing to Wallet” in the Postmix UTXO tab. 

When I downgrade to Sparrow 1.8.1 (the version I used for mixing earlier this year if I correctly recall), I can see these options again. 
However, both options fail. Mixing does not restart.

Below some logs. I use my own node connected via TOR. 

Many thanks in advance for any help.

2024-10-27 18:00:41,493 ERROR [JavaFX Application Thread] c.s.s.w.WhirlpoolServices [null:-1] Failed to start Whirlpool
com.sparrowwallet.sparrow.whirlpool.WhirlpoolException: Could not create whirlpool wallet 
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.Whirlpool.getWhirlpoolWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.samourai.wallet.api.backend.beans.HttpException: java.util.concurrent.ExecutionException: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.whirlpool.ServerApi.fetchPools(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier$1.getOrThrow(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.google.common@31.1-jre/com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.open(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.dataSource.SparrowDataSource.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.WhirlpoolWallet.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.WhirlpoolWalletService.openWallet(Unknown Source)
	... 11 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.util.FutureResponseListener.getResult(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.sparrowwallet.nightjar.http.JavaHttpClient.makeRequest(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJsonGet(Unknown Source)
	... 26 common frames omitted
Caused by: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.onSocks4Response(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.access$300(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection$Socks4Parser.parse(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection$Socks4Parser.access$200(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.onFillable(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.FillInterest.fillable(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.ChannelEndPoint$2.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(Unknown Source)
	... 1 common frames omitted
2024-10-27 18:04:28,554 ERROR [Thread-73] c.s.w.c.w.d.p.ExpirablePoolSupplier [null:-1] load() failure
com.samourai.wallet.api.backend.beans.HttpException: java.util.concurrent.ExecutionException: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.whirlpool.ServerApi.fetchPools(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier$1.getOrThrow(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.google.common@31.1-jre/com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.open(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.dataSource.SparrowDataSource.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.WhirlpoolWallet.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.WhirlpoolWalletService.openWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.Whirlpool.getWhirlpoolWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.util.FutureResponseListener.getResult(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.sparrowwallet.nightjar.http.JavaHttpClient.makeRequest(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJsonGet(Unknown Source)
	... 26 common frames omitted
Caused by: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.onSocks4Response(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.access$300(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection$Socks4Parser.parse(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection$Socks4Parser.access$200(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.onFillable(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.FillInterest.fillable(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.ChannelEndPoint$2.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(Unknown Source)
	... 1 common frames omitted
2024-10-27 18:04:28,557 ERROR [JavaFX Application Thread] c.s.s.w.WhirlpoolServices [null:-1] Failed to start Whirlpool
com.sparrowwallet.sparrow.whirlpool.WhirlpoolException: Could not create whirlpool wallet 
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.Whirlpool.getWhirlpoolWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.samourai.wallet.api.backend.beans.HttpException: java.util.concurrent.ExecutionException: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.whirlpool.ServerApi.fetchPools(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier$1.getOrThrow(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.google.common@31.1-jre/com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.open(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.dataSource.SparrowDataSource.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.WhirlpoolWallet.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.WhirlpoolWalletService.openWallet(Unknown Source)
	... 11 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.util.FutureResponseListener.getResult(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.sparrowwallet.nightjar.http.JavaHttpClient.makeRequest(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJsonGet(Unknown Source)
	... 26 common frames omitted
Caused by: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.onSocks4Response(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.access$300(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection$Socks4Parser.parse(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection$Socks4Parser.access$200(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.onFillable(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.FillInterest.fillable(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.ChannelEndPoint$2.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(Unknown Source)
	... 1 common frames omitted
2024-10-27 18:08:19,240 ERROR [Thread-103] c.s.w.c.w.d.p.ExpirablePoolSupplier [null:-1] load() failure
com.samourai.wallet.api.backend.beans.HttpException: java.util.concurrent.ExecutionException: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.whirlpool.ServerApi.fetchPools(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier$1.getOrThrow(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.google.common@31.1-jre/com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.open(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.dataSource.SparrowDataSource.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.WhirlpoolWallet.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.WhirlpoolWalletService.openWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.Whirlpool.getWhirlpoolWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.util.FutureResponseListener.getResult(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.sparrowwallet.nightjar.http.JavaHttpClient.makeRequest(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJsonGet(Unknown Source)
	... 26 common frames omitted
Caused by: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.onSocks4Response(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.access$300(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection$Socks4Parser.parse(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection$Socks4Parser.access$200(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.onFillable(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.FillInterest.fillable(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.ChannelEndPoint$2.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(Unknown Source)
	... 1 common frames omitted
2024-10-27 18:08:19,241 ERROR [JavaFX Application Thread] c.s.s.w.WhirlpoolServices [null:-1] Failed to start Whirlpool
com.sparrowwallet.sparrow.whirlpool.WhirlpoolException: Could not create whirlpool wallet 
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.Whirlpool.getWhirlpoolWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.samourai.wallet.api.backend.beans.HttpException: java.util.concurrent.ExecutionException: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.whirlpool.ServerApi.fetchPools(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier$1.getOrThrow(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.google.common@31.1-jre/com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.open(Unknown Source)
	at com.sparrowwallet.sparrow@1.8.1/com.sparrowwallet.sparrow.whirlpool.dataSource.SparrowDataSource.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.WhirlpoolWallet.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.samourai.whirlpool.client.wallet.WhirlpoolWalletService.openWallet(Unknown Source)
	... 11 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.util.FutureResponseListener.getResult(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.sparrowwallet.nightjar.http.JavaHttpClient.makeRequest(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.39/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJsonGet(Unknown Source)
	... 26 common frames omitted
Caused by: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.onSocks4Response(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.access$300(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection$Socks4Parser.parse(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection$Socks4Parser.access$200(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.onFillable(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.FillInterest.fillable(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.io.ChannelEndPoint$2.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Unknown Source)
	at com.sparrowwallet.merged.module@1.8.1/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(Unknown Source)
	... 1 common frames omitted

**Comment by craigraw** [comment]
The Whirlpool coordinator is no longer available, and the feature was removed.
