### ISSUE TITLE
transaction did not work

### ISSUE THREAD

**Issue by edjoe** [sparrowwallet/sparrow#1534]
Hello,
I'm a user without much tech experience. I tried different times to send a transaction but got 'server problem' answer.
What can I do?

Thank you.

I include the log file:

2024-11-06 14:29:30,836 WARN [Thread-179] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 8 secs
2024-11-06 16:01:12,033 WARN [Thread-458] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 8 secs
2024-11-06 16:09:17,047 WARN [Thread-469] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 16 secs
2024-11-06 16:09:44,770 WARN [Thread-471] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 8 secs
2024-11-10 16:51:59,284 ERROR [JavaFX Application Thread] c.s.s.t.HeadersController [null:-1] Error broadcasting transaction
com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.ElectrumServer.broadcastTransaction(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.ElectrumServer.broadcastTransactionPrivately(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.ElectrumServer$BroadcastTransactionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.ElectrumServer$BroadcastTransactionService$1.call(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ElectrumServerRpcException: Retries exhausted
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.broadcastTransaction(Unknown Source)
	... 12 common frames omitted
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	... 13 common frames omitted
Caused by: java.lang.IllegalStateException: Socket connection has not been established.
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.TcpTransport.writeRequest(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.TcpTransport.pass(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeRequest(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeAndConvert(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.lambda$broadcastTransaction$15(Unknown Source)
	... 14 common frames omitted
2024-11-10 17:37:09,924 ERROR [JavaFX Application Thread] c.s.s.t.HeadersController [null:-1] Error broadcasting transaction
com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.ElectrumServer.broadcastTransaction(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.ElectrumServer.broadcastTransactionPrivately(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.ElectrumServer$BroadcastTransactionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.ElectrumServer$BroadcastTransactionService$1.call(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ElectrumServerRpcException: Retries exhausted
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.broadcastTransaction(Unknown Source)
	... 12 common frames omitted
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	... 13 common frames omitted
Caused by: java.lang.IllegalStateException: I/O error during a request processing
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeRequest(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeAndConvert(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.lambda$broadcastTransaction$15(Unknown Source)
	... 14 common frames omitted
Caused by: java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getOutputStream(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.TcpTransport.writeRequest(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.TcpTransport.pass(Unknown Source)
	... 18 common frames omitted
2024-11-10 17:39:06,883 ERROR [JavaFX Application Thread] c.s.s.t.HeadersController [null:-1] Error broadcasting transaction
com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.ElectrumServer.broadcastTransaction(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.ElectrumServer.broadcastTransactionPrivately(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.ElectrumServer$BroadcastTransactionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.ElectrumServer$BroadcastTransactionService$1.call(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ElectrumServerRpcException: Retries exhausted
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.broadcastTransaction(Unknown Source)
	... 12 common frames omitted
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	... 13 common frames omitted
Caused by: java.lang.IllegalStateException: I/O error during a request processing
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeRequest(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeAndConvert(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.lambda$broadcastTransaction$15(Unknown Source)
	... 14 common frames omitted
Caused by: java.io.IOException: Error reading response: Could not connect to server at ssl://electrum.blockstream.info:50002
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.TcpTransport.readResponse(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.TcpTransport.pass(Unknown Source)
	... 18 common frames omitted
Caused by: java.io.IOException: Could not connect to server at ssl://electrum.blockstream.info:50002
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.TcpTransport.readInputStream(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	... 1 common frames omitted
2024-11-10 17:44:18,494 ERROR [JavaFX Application Thread] c.s.s.t.HeadersController [null:-1] Error broadcasting transaction
com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.ElectrumServer.broadcastTransaction(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.ElectrumServer.broadcastTransactionPrivately(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.ElectrumServer$BroadcastTransactionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.ElectrumServer$BroadcastTransactionService$1.call(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ElectrumServerRpcException: Retries exhausted
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.broadcastTransaction(Unknown Source)
	... 12 common frames omitted
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	... 13 common frames omitted
Caused by: java.lang.IllegalStateException: Socket connection has not been established.
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.TcpTransport.writeRequest(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.TcpTransport.pass(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeRequest(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeAndConvert(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.lambda$broadcastTransaction$15(Unknown Source)
	... 14 common frames omitted
2024-11-10 17:50:31,045 WARN [Thread-147] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 8 secs

**Comment by edjoe** [comment]
Just went back to Sparrow and found that I can test the server. The server answers and seems to be ok.

**Comment by craigraw** [comment]
I assume this is a public server? Have you tried a different public server?

Can you tell me more about the transaction - how many inputs and outputs, roughly?

**Comment by edjoe** [comment]
Yes, this is the most simple server. It is called electrum.blockstream.info.
The transaction is now in a folder called UTXOs. I will try to send it again. Hmm, when I clicked on Send Selection nothing happened. When I click on it  and click 'clear' nothing happens either. I might restart my Mac and see if this makes a difference.

**Comment by edjoe** [comment]
All good now. I used a different server and made a new transfer. It all worked out!
