### ISSUE TITLE
Freezing after opening camera on Fedora Asahi Remix aarch64 Linux on Apple Silicon

### ISSUE THREAD

**Issue by openoms** [sparrowwallet/sparrow#1571]
Aware that this is not a common OS to use (linux on Mac M1), but reporting in case others get the same or it is easy to fix.

Running sparrow-2.0.0-1.aarch64.rpm
on:
```
uname -a
Linux fedora 6.12.4-400.asahi.fc41.aarch64+16k #1 SMP PREEMPT_DYNAMIC  aarch64 GNU/Linux
```

When I click anything using the camera the picture appear temporarily then freezes. Able to close the camera window, but then Sparrow freezes and needs to be forcefully killed.

Logs:
```
(Sparrow:17477): Gdk-WARNING **: 21:30:27.499: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
2024-12-27 21:30:34,194 ERROR Error executing hwi-3.1.0
java.io.IOException: [17654] Error loading Python lib '/tmp/_MEIKGqx8o/libpython3.9.so.1.0': dlopen: libcrypt.so.1: cannot open shared object file: No such file or directory

	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.io.Hwi.getProcessOutput(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.io.Hwi.execute(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.io.Hwi.enumerateUsb(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.io.Hwi.enumerate(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@22/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Killed
```

Partially fixed with:
```
sudo dnf install libxcrypt-compat
```

Still remains:
```
/opt/sparrow/bin/Sparrow

(Sparrow:23809): Gdk-WARNING **: 21:44:17.053: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
```

**Comment by craigraw** [comment]
Thanks for the report. This is a duplicate of #1504, and will be solved by replacing HWI with [Lark](https://github.com/sparrowwallet/lark) in the next release.

The error trap message is harmless - you can read more about it in #1059.

**Comment by craigraw** [comment]
I may have closed this too early - is the camera still freezing?

**Comment by openoms** [comment]
Closing as fixed after a `dnf update` and restart.
