### ISSUE TITLE
Seeing the difference between Not-Connected and Connected is more important than having 3 different colors for private/public/core connection types.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#212]
Seems like I never see that button that's supposed to tell me the wallet is not connected.

It's light gray on light gray.

![image](https://user-images.githubusercontent.com/388716/134755177-63959c45-52cb-400f-95c1-8a07dd9a847b.png)

![image](https://user-images.githubusercontent.com/388716/134755238-c00ef8af-2a3c-429c-b79b-36547e9aa5df.png)

**Comment by Transisto** [comment]
Not sure if useful but seems like connection is often a hit and miss.

`2021-09-24 22:34:02,211 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-09-24 22:34:54,832 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-09-24 22:34:55,808 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-09-24 22:35:00,743 WARN [Thread-307] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 8 secs
2021-09-24 22:35:10,280 WARN [Thread-307] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 16 secs
2021-09-24 22:35:27,485 WARN [Thread-307] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 34 secs
2021-09-24 22:39:59,634 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-09-24 22:40:01,249 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-09-24 22:40:24,033 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
`

**Comment by craigraw** [comment]
Making the icon red would indicate an error state. Being disconnected is not an error state - in fact using Sparrow as an offline signer is a valid use case.

> Not sure if useful but seems like connection is often a hit and miss.

Probably the Blockstream server is overloaded at this time and disconnecting users.
