### ISSUE TITLE
Change to "no password" of a BIP39+Passphrase wallet

### ISSUE THREAD

**Issue by Tx0123** [sparrowwallet/sparrow#223]
Setup a BIP39+passphrase wallet and set a sparrow password.

Go the setup, advanced, change password, input your current password and then press no password.

Close Sparrow Wallet and try to reopen your wallet: error message "Wallet was not encrypted but seed is"
<img width="471" alt="SparrowError" src="https://user-images.githubusercontent.com/91465293/134891165-2972d475-1412-4a2c-9d04-ab13c52ee2eb.png">
"

**Comment by craigraw** [comment]
Thanks for the bug report.

I haven't been able to recreate this exactly - I think it's a bit more complicated than the instructions above. There is however a bug - Sparrow v1.5.0 allows the setting of different passwords on the Premix, Postmix etc wallets. If that happens, then removing the password on one of them would fail to do so on the other causing the error above.

As of 429b733 Sparrow will change the password on all related wallets at the same time.

**Comment by Tx0123** [comment]
Thank for your answer. 

To clarify, I reproduced the bug on a fresh wallet on which whirlpool mixing wasn't yet configured.

I use OSX 11.5.2 and Sparrow 1.5.0.

It's not a big deal, importing the wallet (with bip39) solves the problem.

**Comment by craigraw** [comment]
Strange, I've just tried several times to reproduce this following your instructions as closely as possible, and I can't. OSX 11.6 and Sparrow 1.5.0. Is there anything in the log file (Help > Show Log File) that might be relevant?

**Comment by Tx0123** [comment]
This is the event in the log file:

2021-09-27 13:45:10,663 ERROR [JavaFX Application Thread] c.s.s.AppController [null:-1] Error opening wallet
java.lang.IllegalStateException: Wallet was not encrypted, but seed is
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.AppController.restorePublicKeysFromSeed(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.AppController.openWallet(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.AppController.openWalletFile(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.AppController.openWallet(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.AppController.openWallet(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.reflect.Trampoline.invoke(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(Unknown Source)
	at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.controls/javafx.scene.control.MenuItem.fire(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.GlobalMenuAdapter.lambda$bindMenuItemProperties$2(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.controls/javafx.scene.control.MenuItem.fire(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassSystemMenu$1.action(Unknown Source)

**Comment by craigraw** [comment]
Thanks - sorry should have been clearer, anything prior to this when changing/removing the password?

**Comment by Tx0123** [comment]
I believe I made a mistake, the problem only occurs with the wallet that was mixing. I can't reproduce the bug with a fresh wallet.
