### ISSUE TITLE
Premix UTXO get banned from whirlpool coordinator.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#225]
Added more logs than hopefully needed.

`com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1028 column 78 path $.transactions.
	at com.google.gson@2.8.6/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Unknown Source)
	at com.google.gson@2.8.6/com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(Unknown Source)
	at com.google.gson@2.8.6/com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(Unknown Source)
	at com.google.gson@2.8.6/com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(Unknown Source)
	at com.google.gson@2.8.6/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(Unknown Source)
	at com.google.gson@2.8.6/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Unknown Source)
	at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.io.JsonPersistence.loadWallet(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.io.Storage.loadUnencryptedWallet(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.AppController.openWalletFile(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.AppController.openWallet(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.AppController.openWallet(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.reflect.Trampoline.invoke(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(Unknown Source)
	at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.controls/javafx.scene.control.MenuItem.fire(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1028 column 78 path $.transactions.
	at com.google.gson@2.8.6/com.google.gson.stream.JsonReader.beginObject(Unknown Source)
	... 66 common frames omitted
2021-09-27 22:47:47,724 WARN [stop-whirlpoolClient] c.s.w.c.w.WhirlpoolWallet [null:-1] onMixFail(CANCEL): won't retry
2021-09-27 22:47:47,857 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-8718] o.s.w.s.s.c.WebSocketClientSockJsSession [null:-1] Ignoring received message due to state CLOSING in WebSocketClientSockJsSession[id='8347a21f3c5b4a098e82bdbb09e70609, url=wss://pool.whirl.mx:8080/ws/connect]
2021-09-27 22:48:23,872 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-9042] c.s.w.c.m.d.MixSession[1632797267266] [null:-1]  ! connexion lost, reconnecting for a new mix...
2021-09-27 22:48:24,039 WARN [stop-whirlpoolClient] c.s.w.c.w.WhirlpoolWallet [null:-1] onMixFail(CANCEL): won't retry
2021-09-27 22:49:55,644 ERROR [Thread-15] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:49:56,244 ERROR [Thread-15] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:49:56,268 WARN [Thread-15] c.s.w.c.w.PostmixIndexService [null:-1] postmixIndex already used: 78
2021-09-27 22:49:57,371 ERROR [Thread-15] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:49:57,388 WARN [Thread-15] c.s.w.c.w.PostmixIndexService [null:-1] postmixIndex already used: 82
2021-09-27 22:49:58,469 ERROR [Thread-15] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:49:58,486 WARN [Thread-15] c.s.w.c.w.PostmixIndexService [null:-1] postmixIndex already used: 90
2021-09-27 22:49:59,556 ERROR [Thread-15] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:49:59,569 WARN [Thread-15] c.s.w.c.w.PostmixIndexService [null:-1] postmixIndex already used: 106
2021-09-27 22:50:00,787 ERROR [Thread-15] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:50:00,802 WARN [Thread-15] c.s.w.c.w.PostmixIndexService [null:-1] postmixIndex already used: 110
2021-09-27 22:50:01,882 ERROR [Thread-15] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:50:01,894 WARN [Thread-15] c.s.w.c.w.PostmixIndexService [null:-1] postmixIndex already used: 114
2021-09-27 22:50:56,931 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-156] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:50:56,962 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-156] c.s.w.c.m.d.MixDialog[1632797433144] [null:-1] onPrivateReceived NotifiableException: Output already registered
2021-09-27 22:50:56,962 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-156] c.s.w.c.m.MixClient[1632797433144] [null:-1] ERROR: Output already registered
2021-09-27 22:50:56,963 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-156] c.s.w.c.w.WhirlpoolWallet [null:-1]  - [MIX] 0.01btc ? WHIRLPOOL FAILED ? Input rejected ; Output already registered, receiveAddress=bc1, path=m/84'/0'/2147483646'/0/76, type=POSTMIX
2021-09-27 22:50:57,541 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-156] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:50:58,134 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-156] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:50:58,148 WARN [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-156] c.s.w.c.w.PostmixIndexService [null:-1] postmixIndex already used: 80
2021-09-27 22:50:59,250 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-156] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:50:59,264 WARN [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-156] c.s.w.c.w.PostmixIndexService [null:-1] postmixIndex already used: 84
2021-09-27 22:51:00,410 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-156] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:51:00,422 WARN [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-156] c.s.w.c.w.PostmixIndexService [null:-1] postmixIndex already used: 92
2021-09-27 22:51:01,518 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-156] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:51:01,531 WARN [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-156] c.s.w.c.w.PostmixIndexService [null:-1] postmixIndex already used: 108
2021-09-27 22:51:02,738 WARN [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-156] c.s.w.c.w.WhirlpoolWallet [null:-1] onMixFail(INPUT_REJECTED): won't retry
2021-09-27 22:51:28,731 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-157] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:51:28,744 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-157] c.s.w.c.m.d.MixDialog[1632797463147] [null:-1] onPrivateReceived NotifiableException: Output already registered
2021-09-27 22:51:28,745 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-157] c.s.w.c.m.MixClient[1632797463147] [null:-1] ERROR: Output already registered
2021-09-27 22:51:28,745 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-157] c.s.w.c.w.WhirlpoolWallet [null:-1]  - [MIX] 0.01btc ? WHIRLPOOL FAILED ? Input rejected ; Output already registered, receiveAddress=bc1q, path=m/84'/0'/2147483646'/0/114, type=POSTMIX
2021-09-27 22:51:29,445 WARN [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-157] c.s.w.c.w.WhirlpoolWallet [null:-1] onMixFail(INPUT_REJECTED): won't retry
2021-09-27 22:51:29,585 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-152] o.s.w.s.s.c.WebSocketClientSockJsSession [null:-1] Ignoring received message due to state CLOSING in WebSocketClientSockJsSession[id='943d81507715455cab19b9e69522619c, url=wss://pool.whirl.mx:8080/ws/connect]
2021-09-27 22:52:26,977 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-152] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:52:26,996 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-152] c.s.w.c.m.d.MixDialog[1632797523151] [null:-1] onPrivateReceived NotifiableException: Output already registered
2021-09-27 22:52:26,996 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-152] c.s.w.c.m.MixClient[1632797523151] [null:-1] ERROR: Output already registered
2021-09-27 22:52:26,997 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-152] c.s.w.c.w.WhirlpoolWallet [null:-1]  - [MIX] 0.01btc ? WHIRLPOOL FAILED ? Input rejected ; Output already registered, receiveAddress=bc1ql, path=m/84'/0'/2147483646'/0/76, type=POSTMIX
2021-09-27 22:52:27,608 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-152] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:52:28,200 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-152] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:52:28,212 WARN [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-152] c.s.w.c.w.PostmixIndexService [null:-1] postmixIndex already used: 80
2021-09-27 22:52:29,279 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-152] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:52:29,311 WARN [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-152] c.s.w.c.w.PostmixIndexService [null:-1] postmixIndex already used: 84
2021-09-27 22:52:30,427 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-152] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:52:30,439 WARN [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-152] c.s.w.c.w.PostmixIndexService [null:-1] postmixIndex already used: 92
2021-09-27 22:52:31,517 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-152] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:52:31,534 WARN [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-152] c.s.w.c.w.PostmixIndexService [null:-1] postmixIndex already used: 108
2021-09-27 22:52:32,739 WARN [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-152] c.s.w.c.w.WhirlpoolWallet [null:-1] onMixFail(INPUT_REJECTED): won't retry
2021-09-27 22:52:58,514 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-153] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:52:58,526 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-153] c.s.w.c.m.d.MixDialog[1632797553155] [null:-1] onPrivateReceived NotifiableException: Output already registered
2021-09-27 22:52:58,527 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-153] c.s.w.c.m.MixClient[1632797553155] [null:-1] ERROR: Output already registered
2021-09-27 22:52:58,527 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-153] c.s.w.c.w.WhirlpoolWallet [null:-1]  - [MIX] 0.01btc ? WHIRLPOOL FAILED ? Input rejected ; Output already registered, receiveAddress=bc1...., path=m/84'/0'/2147483646'/0/114, type=POSTMIX
2021-09-27 22:52:59,078 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-153] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:52:59,644 WARN [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-153] c.s.w.c.w.WhirlpoolWallet [null:-1] onMixFail(INPUT_REJECTED): won't retry
2021-09-27 22:53:05,313 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-151] c.s.w.c.m.MixClient[1632797583157] [null:-1] ERROR: Banned from service. Contact us.
2021-09-27 22:53:05,314 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-151] c.s.w.c.w.WhirlpoolWallet [null:-1]  - [MIX] 0.01btc ? WHIRLPOOL FAILED ? Input rejected ; Banned from service. Contact us.
2021-09-27 22:53:05,451 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-151] c.s.n.h.JavaHttpClient[COORDINATOR_REGISTER_OUTPUT] [null:-1] Http query failed: status=500, responseBody={"message":"Output already registered"}
2021-09-27 22:53:06,022 WARN [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-151] c.s.w.c.w.WhirlpoolWallet [null:-1] onMixFail(INPUT_REJECTED): won't retry`

**Comment by craigraw** [comment]
Can you confirm the operating system, and what the computer sleep settings are? Also, are you connecting over Tor?

**Comment by Transisto** [comment]
Not connected over Tor, No sleep mode, I'll close and reopen if it happens again and pay more attention to the logs.
