### ISSUE TITLE
Connection error logs, Slow remixes

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#229]
Are the "won't retry" normal?

I don't have much data to consider it slow, just that in the same 24h period Samourai did 3 remix of the same pool. and Sparrow 1. 

`2021-09-29 04:56:08,190 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-1091] o.s.w.s.s.c.SockJsClient [null:-1] Initial SockJS "Info" request to server failed, url=wss://pool.whirl.mx:8080/ws/connect
org.springframework.web.socket.sockjs.SockJsTransportFailureException: Failed to execute request to https://pool.whirl.mx:8080/ws/connect/info; nested exception is java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Connect Timeout
	at com.sparrowwallet.merged.module@1.5.0/org.springframework.web.socket.sockjs.client.JettyXhrTransport.executeRequest(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.springframework.web.socket.sockjs.client.JettyXhrTransport.executeInfoRequestInternal(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.springframework.web.socket.sockjs.client.AbstractXhrTransport.executeInfoRequest(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.springframework.web.socket.sockjs.client.SockJsClient.getServerInfo(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.springframework.web.socket.sockjs.client.SockJsClient.doHandshake(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.springframework.web.socket.messaging.WebSocketStompClient.connect(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.springframework.web.socket.messaging.WebSocketStompClient.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.17-SNAPSHOT/com.sparrowwallet.nightjar.stomp.JavaStompClient.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.17-SNAPSHOT/com.samourai.stomp.client.StompTransport.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.17-SNAPSHOT/com.samourai.whirlpool.client.mix.dialog.MixSession.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.17-SNAPSHOT/com.samourai.whirlpool.client.mix.dialog.MixSession$3.onTransportDisconnected(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.17-SNAPSHOT/com.samourai.stomp.client.StompTransport$1.onError(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.17-SNAPSHOT/com.samourai.stomp.client.StompTransport$1.onError(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.17-SNAPSHOT/com.sparrowwallet.nightjar.stomp.JavaStompClient$1.handleTransportError(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.springframework.messaging.simp.stomp.DefaultStompSession.handleFailure(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.springframework.messaging.simp.stomp.DefaultStompSession.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.springframework.web.socket.messaging.WebSocketStompClient$WebSocketTcpConnectionHandlerAdapter.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.springframework.web.socket.handler.WebSocketHandlerDecorator.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.springframework.web.socket.sockjs.client.AbstractClientSockJsSession.afterTransportClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.springframework.web.socket.sockjs.client.WebSocketTransport$ClientSockJsWebSocketHandler.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.springframework.web.socket.adapter.jetty.JettyWebSocketHandlerAdapter.onWebSocketClose(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.eclipse.jetty.websocket.common.WebSocketSession.callApplicationOnClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.disconnect(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.eclipse.jetty.websocket.common.WebSocketSession.onClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.eclipse.jetty.io.AbstractConnection.onClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.eclipse.jetty.io.AbstractConnection.onClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.eclipse.jetty.io.ssl.SslConnection.onClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.eclipse.jetty.io.SelectorManager.connectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Connect Timeout
	at com.sparrowwallet.merged.module@1.5.0/org.eclipse.jetty.client.util.FutureResponseListener.getResult(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.0/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	... 40 common frames omitted
Caused by: java.net.SocketTimeoutException: Connect Timeout
	at com.sparrowwallet.merged.module@1.5.0/org.eclipse.jetty.io.ManagedSelector$Connect.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 common frames omitted
2021-09-29 05:57:10,816 WARN [stop-whirlpoolClient] c.s.w.c.w.WhirlpoolWallet [null:-1] onMixFail(CANCEL): won't retry
2021-09-29 06:57:41,140 WARN [stop-whirlpoolClient] c.s.w.c.w.WhirlpoolWallet [null:-1] onMixFail(CANCEL): won't retry
2021-09-29 07:58:11,024 WARN [stop-whirlpoolClient] c.s.w.c.w.WhirlpoolWallet [null:-1] onMixFail(CANCEL): won't retry
2021-09-29 07:58:11,157 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-1701] o.s.w.s.s.c.WebSocketClientSockJsSession [null:-1] Ignoring received message due to state CLOSING in WebSocketClientSockJsSession[id='56acd1ee178b4e17831e39a4cd27bfb6, url=wss://pool.whirl.mx:8080/ws/connect]
2021-09-29 08:58:41,033 WARN [stop-whirlpoolClient] c.s.w.c.w.WhirlpoolWallet [null:-1] onMixFail(CANCEL): won't retry
2021-09-29 09:14:29,076 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-1053] c.s.w.c.m.d.MixSession[1632920320440] [null:-1]  ! connexion lost, reconnecting for a new mix...
2021-09-29 09:14:29,672 WARN [stop-whirlpoolClient] c.s.w.c.w.WhirlpoolWallet [null:-1] onMixFail(CANCEL): won't retry
2021-09-29 15:01:07,884 WARN [stop-whirlpoolClient] c.s.w.c.w.WhirlpoolWallet [null:-1] onMixFail(CANCEL): won't retry
2021-09-29 16:01:37,907 WARN [stop-whirlpoolClient] c.s.w.c.w.WhirlpoolWallet [null:-1] onMixFail(CANCEL): won't retry`

**Comment by Transisto** [comment]
Connection errors seems to be clocked at every hours.
2021-09-29 15:01:07,884 WARN [stop-whirlpoolClient] c.s.w.c.w.WhirlpoolWallet [null:-1] onMixFail(CANCEL): won't retry
2021-09-29 16:01:37,907 WARN [stop-whirlpoolClient] c.s.w.c.w.WhirlpoolWallet [null:-1] onMixFail(CANCEL): won't retry
2021-09-29 17:02:07,915 WARN [stop-whirlpoolClient] c.s.w.c.w.WhirlpoolWallet [null:-1] onMixFail(CANCEL): won't retry

**Comment by craigraw** [comment]
I've consulted the Samourai team on this behaviour, and it is normal.
