### ISSUE TITLE
New errors "java.lang.NullPointerException: date must not be null"

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#230]
Soon after initiating a new mix.

`2021-09-30 18:29:49,112 ERROR [JavaFX Application Thread] c.s.s.MainApp [null:-1] Exception in thread "JavaFX Application Thread"
java.lang.IndexOutOfBoundsException: [ fromIndex: 0, toIndex: 16, size: 15 ]
	at javafx.controls/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList.subList(Unknown Source)
	at javafx.base/javafx.collections.ListChangeListener$Change.getAddedSubList(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.getAddedElements(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.lambda$new$0(Unknown Source)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at javafx.base/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at javafx.base/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at javafx.base/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList._endChange(Unknown Source)
	at javafx.controls/javafx.scene.control.MultipleSelectionModelBase$SelectedIndicesList._endChange(Unknown Source)
	at javafx.controls/javafx.scene.control.ControlUtils.updateSelectedIndices(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeTableView$TreeTableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeTableView.sort(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.control.UtxosTreeTable.updateHistory(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.wallet.UtxosController.walletHistoryChanged(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber$1.run(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.util.concurrent.DirectExecutor.execute(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber.dispatchEvent(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.EventBus.post(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.wallet.WalletForm.lambda$notifyIfChanged$4(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-09-30 18:35:46,047 ERROR [JavaFX Application Thread] c.s.s.MainApp [null:-1] Exception in thread "JavaFX Application Thread"
java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
	at java.base/java.util.BitSet.get(Unknown Source)
	at javafx.controls/javafx.scene.control.MultipleSelectionModelBase$SelectedIndicesList.clear(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(Unknown Source)
	at java.base/java.util.stream.DistinctOps$1$2.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at javafx.controls/javafx.scene.control.ControlUtils.updateSelectedIndices(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeTableView$TreeTableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(Unknown Source)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at javafx.base/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at javafx.base/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at javafx.base/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at javafx.base/javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)
	at javafx.base/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)
	at javafx.base/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at javafx.base/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at javafx.base/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at javafx.base/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at javafx.base/javafx.collections.ModifiableObservableListBase.setAll(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.SelectedCellsMap.setAll(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeTableView$TreeTableViewArrayListSelectionModel$3.handle(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeTableView$TreeTableViewArrayListSelectionModel$3.handle(Unknown Source)
	at javafx.base/javafx.event.WeakEventHandler.handle(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$WeakEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeItem.fireEvent(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeItem.updateChildren(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeItem.lambda$new$0(Unknown Source)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at javafx.base/com.sun.javafx.collections.ObservableListWrapper.sort(Unknown Source)
	at javafx.base/javafx.collections.FXCollections.sort(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeItem.doSort(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeItem.runSort(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeItem.sort(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeItem.sort(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeTableView$3.call(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeTableView$3.call(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeTableView.sort(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.control.UtxosTreeTable.updateHistory(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.wallet.UtxosController.walletHistoryChanged(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber$1.run(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.util.concurrent.DirectExecutor.execute(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber.dispatchEvent(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.EventBus.post(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.wallet.WalletForm.lambda$notifyIfChanged$4(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-09-30 18:37:34,561 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-1051] c.s.w.c.m.d.MixSession[1633038321438] [null:-1]  ! connexion lost, reconnecting for a new mix...
2021-09-30 18:37:35,202 WARN [stop-whirlpoolClient] c.s.w.c.w.WhirlpoolWallet [null:-1] onMixFail(CANCEL): won't retry
2021-09-30 18:38:03,251 ERROR [JavaFX Application Thread] c.s.s.MainApp [null:-1] Exception in thread "JavaFX Application Thread"
java.lang.NullPointerException: date must not be null
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at java.base/java.util.Calendar.setTime(Unknown Source)
	at java.base/java.text.SimpleDateFormat.format(Unknown Source)
	at java.base/java.text.SimpleDateFormat.format(Unknown Source)
	at java.base/java.text.DateFormat.format(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.control.DateCell.updateItem(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.control.DateCell.updateItem(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeTableCell.updateItem(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeTableCell.indexChanged(Unknown Source)
	at javafx.controls/javafx.scene.control.IndexedCell.updateIndex(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.TableColumnHeader.resizeColumnToFitContent(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.TableColumnHeader.resizeColumnToFitContent(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.TableColumnHeader.doColumnAutoSize(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.TableColumnHeader.updateScene(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.TableColumnHeader.lambda$new$0(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(Unknown Source)
	at javafx.base/javafx.beans.value.WeakChangeListener.changed(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Unknown Source)
	at javafx.graphics/javafx.scene.Node.setScenes(Unknown Source)
	at javafx.graphics/javafx.scene.Parent$2.onChanged(Unknown Source)
	at javafx.base/com.sun.javafx.collections.TrackableObservableList.lambda$new$0(Unknown Source)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at javafx.base/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at javafx.base/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at javafx.base/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at javafx.base/javafx.collections.ModifiableObservableListBase.setAll(Unknown Source)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.NestedTableColumnHeader.updateContent(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.NestedTableColumnHeader.updateTableColumnHeaders(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.NestedTableColumnHeader.checkState(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.NestedTableColumnHeader.computePrefHeight(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.prefHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.prefHeight(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.TableHeaderRow.computePrefHeight(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.TableHeaderRow.computeMinHeight(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.minHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.minHeight(Unknown Source)
	at javafx.controls/javafx.scene.control.SkinBase.computeMinHeight(Unknown Source)
	at javafx.controls/javafx.scene.control.Control.computeMinHeight(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.minHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.minHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.computeChildMinAreaHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.BorderPane.getAreaHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.BorderPane.computeMinHeight(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.minHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.minHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.computeChildMinAreaHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.VBox.getAreaHeights(Unknown Source)
	at javafx.graphics/javafx.scene.layout.VBox.computeContentHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.VBox.computeMinHeight(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.minHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.minHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.computeChildMinAreaHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.BorderPane.getAreaHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.BorderPane.computeMinHeight(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.minHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.minHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.computeChildMinAreaHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.getMaxAreaHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.computeMaxMinAreaHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.StackPane.computeMinHeight(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.minHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.minHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.computeChildMinAreaHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.BorderPane.getAreaHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.BorderPane.computeMinHeight(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.minHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.minHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.boundedNodeSizeWithBias(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.layoutInArea(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.layoutInArea(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.layoutInArea(Unknown Source)
	at javafx.graphics/javafx.scene.layout.StackPane.layoutChildren(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-09-30 18:38:03,348 ERROR [JavaFX Application Thread] c.s.s.MainApp [null:-1] Exception in thread "JavaFX Application Thread"
java.lang.NullPointerException: date must not be null
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at java.base/java.util.Calendar.setTime(Unknown Source)
	at java.base/java.text.SimpleDateFormat.format(Unknown Source)
	at java.base/java.text.SimpleDateFormat.format(Unknown Source)
	at java.base/java.text.DateFormat.format(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.control.DateCell.updateItem(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.control.DateCell.updateItem(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeTableCell.updateItem(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeTableCell.indexChanged(Unknown Source)
	at javafx.controls/javafx.scene.control.IndexedCell.updateIndex(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.TableRowSkinBase.updateCells(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.TreeTableRowSkin.updateCells(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.TableRowSkinBase.<init>(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.TreeTableRowSkin.<init>(Unknown Source)
	at javafx.controls/javafx.scene.control.TreeTableRow.createDefaultSkin(Unknown Source)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Unknown Source)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Node.processCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Node.applyCss(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.setCellIndex(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.getCell(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.getCellLength(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.computeViewportOffset(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.layoutChildren(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by craigraw** [comment]
Closing see #231
