### ISSUE TITLE
[Oct 07 14:42:53] java.lang.NullPointerException: Cannot read the array length because "<parameter1>" is null

### ISSUE THREAD

**Issue by 0bs72** [sparrowwallet/sparrow#244]
I'm not sure if this is an issue that needs to be addressed, but I'm seeing <title> after the 1.5.0 update.
This is the latest sparrow.log entry...
```
021-10-07 14:42:57,289 ERROR [JavaFX Application Thread] c.s.s.w.WalletForm [null:-1] Error retrieving wallet history
com.sparrowwallet.sparrow.net.ServerException: Failed to subscribe to paths: [m/0/0-m/0/19]
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer.subscribeWalletNodes(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer.getHistory(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer.getHistory(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.BatchedElectrumServerRpc.subscribeScriptHashes(Unknown Source)
	... 13 common frames omitted
Caused by: java.lang.IllegalStateException: Unspecified id: 'm/1/0' in response
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.processSingleResponse(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.processBatchResponse(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.execute(Unknown Source)
	... 15 common frames omitted

**Comment by 0bs72** [comment]
I'm not too sure if this has been fixed or if it's simply come good, but as of now, I'm no longer seeing this error.
I'll leave this open for now and check back within the next 24 hrs.

My thanks to you guys for **THE** best BTC Wallet, and I've tried quite a few.
Peace.

**Comment by 0bs72** [comment]
It seems that the way that Electrs is downloading blocks has changed. I'm getting a Ping time of 11710 ms reported, so it looks like some kind of a timing issue to me.

[This is the post](https://github.com/mynodebtc/mynode/issues/571)

The bottom line is, does this (the error here) need addressing, or is it of no real consequence?
