### ISSUE TITLE
1.5.1 Failed to start whirlpool

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#245]
Also noticed mixing doesn't start on it's own anymore.

`2021-10-07 12:42:16,169 ERROR [Thread-9] c.s.w.c.w.d.p.ExpirablePoolSupplier [null:-1] load() failure
com.samourai.wallet.api.backend.beans.HttpException: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Connect Timeout
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.whirlpool.ServerApi.fetchPools(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier$1.getOrThrow(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.open(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.whirlpool.dataSource.SparrowDataSource.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.WhirlpoolWallet.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.WhirlpoolWalletService.openWallet(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.whirlpool.Whirlpool.getWhirlpoolWallet(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Connect Timeout
	at com.sparrowwallet.merged.module@1.5.1/org.eclipse.jetty.client.util.FutureResponseListener.getResult(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.1/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.1/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJsonGet(Unknown Source)
	... 26 common frames omitted
Caused by: java.net.SocketTimeoutException: Connect Timeout
	at com.sparrowwallet.merged.module@1.5.1/org.eclipse.jetty.io.ManagedSelector$Connect.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	... 3 common frames omitted
2021-10-07 12:42:16,171 ERROR [JavaFX Application Thread] c.s.s.w.WhirlpoolServices [null:-1] Failed to start whirlpool
com.sparrowwallet.sparrow.whirlpool.WhirlpoolException: Could not create whirlpool wallet 
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.whirlpool.Whirlpool.getWhirlpoolWallet(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.samourai.wallet.api.backend.beans.HttpException: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Connect Timeout
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.whirlpool.ServerApi.fetchPools(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier$1.getOrThrow(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.open(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.whirlpool.dataSource.SparrowDataSource.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.WhirlpoolWallet.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.WhirlpoolWalletService.openWallet(Unknown Source)
	... 11 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Connect Timeout
	at com.sparrowwallet.merged.module@1.5.1/org.eclipse.jetty.client.util.FutureResponseListener.getResult(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.1/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.1/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJsonGet(Unknown Source)
	... 26 common frames omitted
Caused by: java.net.SocketTimeoutException: Connect Timeout
	at com.sparrowwallet.merged.module@1.5.1/org.eclipse.jetty.io.ManagedSelector$Connect.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	... 3 common frames omitted
2021-10-07 12:44:21,799 ERROR [Thread-43] c.s.w.c.w.d.p.ExpirablePoolSupplier [null:-1] load() failure
com.samourai.wallet.api.backend.beans.HttpException: java.lang.InterruptedException
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.whirlpool.ServerApi.fetchPools(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier$1.getOrThrow(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.open(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.whirlpool.dataSource.SparrowDataSource.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.WhirlpoolWallet.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.samourai.whirlpool.client.wallet.WhirlpoolWalletService.openWallet(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.whirlpool.Whirlpool.getWhirlpoolWallet(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source)
	at java.base/java.util.concurrent.CountDownLatch.await(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.1/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.1/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.18-SNAPSHOT/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJsonGet(Unknown Source)
	... 26 common frames omitted`

**Comment by craigraw** [comment]
This is just a connection problem. `Connect Timeout at...`.

In general you have many issues related to your connection. I would consider looking at that before filing more issues here.

**Comment by Transisto** [comment]
Connection seems impossible again, no matter what I do.

`2021-10-09 01:16:54,713 WARN [Thread-1672] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 34 secs
2021-10-09 01:17:06,831 WARN [Thread-1506] c.s.s.n.SimpleElectrumServerRpc [null:-1] Failed to retrieve fee rate for target blocks: 4 (Retries exhausted)
2021-10-09 01:17:10,626 WARN [Thread-1506] c.s.s.n.SimpleElectrumServerRpc [null:-1] Failed to retrieve fee rate for target blocks: 5 (Retries exhausted)
2021-10-09 01:17:13,664 WARN [Thread-1506] c.s.s.n.SimpleElectrumServerRpc [null:-1] Failed to retrieve fee rate for target blocks: 10 (Retries exhausted)
2021-10-09 01:17:16,876 WARN [Thread-1506] c.s.s.n.SimpleElectrumServerRpc [null:-1] Failed to retrieve fee rate for target blocks: 25 (Retries exhausted)
2021-10-09 01:17:18,932 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-10-09 01:17:23,716 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
com.sparrowwallet.sparrow.net.ElectrumServerRpcException: Error getting fee rate histogram
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.getFeeRateHistogram(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer.getMempoolRateSizes(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	... 12 common frames omitted
Caused by: java.lang.IllegalStateException: I/O error during a request processing
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeRequest(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeAndConvert(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.lambda$getFeeRateHistogram$13(Unknown Source)
	... 13 common frames omitted
Caused by: java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getOutputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.writeRequest(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.pass(Unknown Source)
	... 17 common frames omitted
`

![image](https://user-images.githubusercontent.com/388716/136645204-72ccebc5-8a01-4950-95aa-7f0769ddb6b4.png)

Connecting or connected

**Comment by craigraw** [comment]
Blockstream's server does often have these kind of issues. It appears that when it is overloaded it disconnects clients and prevents them from reconnecting (as far as I can tell). 

Agreed the tooltip should reflect this state better.

**Comment by Transisto** [comment]
While I didn't try another server I tried disconnecting and reconnecting many times over 15min. I went in the connection box and tried testing connection with BS server. Nothing would happen. It really felt like nothing at all could be done to get any connection from sparrow over this long 15 block off time.
Restarting sparrow acheived connection instantly.
