### ISSUE TITLE
Scan QR code doesn't work [Windows]

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#25]
A window pops up and disappear instantly.

**Comment by craigraw** [comment]
What version of Windows? My testing has been done on Windows 10.

Also, any errors in the sparrow.log file in the Sparrow home folder (%APPDATA%\Sparrow on Windows)

**Comment by Transisto** [comment]
```
2020-10-21 15:22:36,698 ERROR [JavaFX Application Thread] c.s.s.c.WebcamView [null:-1] Failed to start web cam
com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at com.sparrowwallet.merged.module@0.9.5/com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/com.github.sarxos.webcam.Webcam.getWebcams(Unknown Source)
	at com.sparrowwallet.sparrow@0.9.5/com.sparrowwallet.sparrow.control.WebcamService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@0.9.5/com.sparrowwallet.sparrow.control.WebcamService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	... 12 common frames omitted
Caused by: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at com.sparrowwallet.merged.module@0.9.5/com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/com.github.sarxos.webcam.WebcamProcessor.process(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/com.github.sarxos.webcam.WebcamTask.process(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.newGrabber(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver.getDevices(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	... 3 common frames omitted
Caused by: java.lang.RuntimeException: Failed to allocate new instance of type class com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber
	at com.sparrowwallet.merged.module@0.9.5/org.bridj.cpp.CPPRuntime.newCPPInstance(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/org.bridj.CRuntime$CTypeInfo.initialize(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/org.bridj.BridJ.initialize(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/org.bridj.NativeObject.<init>(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/org.bridj.StructObject.<init>(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/org.bridj.cpp.CPPObject.<init>(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<init>(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(Unknown Source)
	... 3 common frames omitted
Caused by: java.lang.RuntimeException: Library 'OpenIMAJGrabber' was not loaded successfully from file 'C:\Users\T3\AppData\Local\Temp\BridJExtractedLibraries754541801931749993\OpenIMAJGrabber.dll'
	at com.sparrowwallet.merged.module@0.9.5/org.bridj.BridJ.getNativeLibrary(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/org.bridj.BridJ.getNativeLibrary(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.5/org.bridj.BridJ.getNativeLibrary(Unknown Source)
	... 14 common frames omitted
```

**Comment by craigraw** [comment]
Ok, the key issue is:
```Library 'OpenIMAJGrabber' was not loaded successfully from file 'C:\Users\T3\AppData\Local\Temp\BridJExtractedLibraries754541801931749993\OpenIMAJGrabber.dll'```

Either this is because the file does not exist (?) for some reason, or there is some issue loading it. Which version of Windows is this error occurring on?

**Comment by Transisto** [comment]
It's windows 10, that file in a temp folder has never existed.

**Comment by craigraw** [comment]
The file will delete when Sparrow exits, so that might explain why it wasn't present.

If you restart Sparrow, start the webcam and watch both sparrow.log and that Temp folder carefully there might be more information as to why this is failing.

**Comment by craigraw** [comment]
Does this issue still occur?

**Comment by Transisto** [comment]
Tested as working fine with both my camera.
Amazing!
