### ISSUE TITLE
Can't connect to electrs 

### ISSUE THREAD

**Issue by datvebi** [sparrowwallet/sparrow#266]
I have an electrum rust server running on my raspiblitz (latest release). I was able to get my Wasabi wallet to connect to it, so I know it's up and running, but Sparrow can't connect. I've toggled SSL on/off and used the tor proxy localhost:9050 with Tor browser open and also toggling it off. The log below has me testing a few different combinations but the most common one was SSL toggled on and using the Tor proxy and it would return a "can't connect" or "socket closed" exception.

2021-10-14 16:37:44,530 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
com.sparrowwallet.sparrow.net.TorServerAlreadyBoundException: Tor server already bound
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TorService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TorService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: net.freehaven.tor.control.TorControlError: Error reply: Unable to set option: Failed to bind one of the listener ports.
	at com.github.JesusMcCloud.jtorctl@1.5/net.freehaven.tor.control.TorControlConnection.sendAndWaitForResponse(Unknown Source)
	at com.github.JesusMcCloud.jtorctl@1.5/net.freehaven.tor.control.TorControlConnection.setConf(Unknown Source)
	at com.github.JesusMcCloud.jtorctl@1.5/net.freehaven.tor.control.TorControlConnection.setConf(Unknown Source)
	at netlayer.jpms@0.6.8/org.berndpruenster.netlayer.tor.TorController.enableNetwork(Unknown Source)
	at netlayer.jpms@0.6.8/org.berndpruenster.netlayer.tor.NativeTor.<init>(Unknown Source)
	at netlayer.jpms@0.6.8/org.berndpruenster.netlayer.tor.NativeTor.<init>(Unknown Source)
	at netlayer.jpms@0.6.8/org.berndpruenster.netlayer.tor.NativeTor.<init>(Unknown Source)
	... 10 common frames omitted
2021-10-14 16:39:56,062 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-10-14 16:40:03,556 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-10-14 16:40:50,632 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-10-14 16:40:50,635 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-10-14 18:55:51,463 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-10-14 18:56:06,719 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
com.sparrowwallet.sparrow.net.ElectrumServerRpcException: Error getting server version
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.getServerVersion(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer.getServerVersion(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	... 12 common frames omitted
Caused by: java.lang.IllegalStateException: I/O error during a request processing
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeRequest(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeAndConvert(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.lambda$getServerVersion$1(Unknown Source)
	... 13 common frames omitted
Caused by: java.io.IOException: Error reading response: Could not connect to server at tcp://e6hlbtx64xsjo4ybutr7gbtr4r3fgrivopucwnh22luuwrv4say3klyd.onion:50002
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readResponse(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.pass(Unknown Source)
	... 17 common frames omitted
Caused by: java.io.IOException: Could not connect to server at tcp://e6hlbtx64xsjo4ybutr7gbtr4r3fgrivopucwnh22luuwrv4say3klyd.onion:50002
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	... 1 common frames omitted
2021-10-14 18:56:09,912 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-10-14 18:58:14,700 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-10-14 18:58:19,596 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-10-14 18:58:57,934 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-10-14 19:00:22,613 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-10-14 19:03:09,795 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-10-14 19:06:05,198 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/java.net.Socket.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-10-14 19:07:16,787 ERROR [ElectrumServerReadThread] c.s.s.n.ElectrumServer [null:-1] Uncaught error in ConnectionService
java.lang.NullPointerException: Cannot read field "in" because "this.proxy" is null
	at com.github.ravn.jsocks@1.0/com.runjva.sourceforge.jsocks.protocol.SocksSocket.getInputStream(Unknown Source)
	at netlayer.jpms@0.6.8/org.berndpruenster.netlayer.tor.TorSocket.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-10-14 19:08:33,762 ERROR [Thread-16] c.s.s.n.VersionCheckService [null:-1] Error retrieving version check file
java.net.SocketException: Connection refused: connect
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.VersionCheckService.getVersionCheck(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.VersionCheckService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.VersionCheckService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by craigraw** [comment]
A few points here:

- Wasabi doesn't use Electrs AFAIK
- SSL should probably be off if you are connecting with Tor
- The Tor Browser proxy runs on port 9150
- If SSL is off for the Tor address, the correct port to use for the onion URL is 50001.
