### ISSUE TITLE
Windows resource usage report, CPU RAM GPU

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#283]
Wallet has been running for 4 hours.

![image](https://user-images.githubusercontent.com/388716/138803131-6f8e7cba-d818-458c-9c3c-b1951b66efc4.png)

If I close the one wallet it doesn't improve.

![image](https://user-images.githubusercontent.com/388716/138803378-eff6da4a-04b3-4a6d-add9-a82d2362740a.png)

Then if I disconnect from a server the 5% GPU usage stops.

**Comment by 6102bitcoin** [comment]
Is this expected behaviour @craigraw ?

**Comment by craigraw** [comment]
@Transisto it would be good to get an update here using v1.5.6 - there have been a number of memory related improvements.

**Comment by Transisto** [comment]
Hi, I've let 3 wallet run for 2 days, the result is that at some point it got a 
Failed to subscribe to paths: [../1/0-../1/1082]
error

then no matter the server it wouldn't connect to anything, 

with a series of this in the logs.

2022-02-11 01:25:44,776 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-02-11 01:27:54,621 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-02-11 01:29:40,717 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-02-11 01:30:10,046 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-02-11 01:30:17,234 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream



![image](https://user-images.githubusercontent.com/388716/153548247-3ff55549-14bf-4126-b181-602dc9ba8c39.png)


CPU usage is reasonable but RAM is way too high.

**Comment by craigraw** [comment]
Regarding memory usage: These metrics in the screenshots are not reliable indicators of how much memory an executable is actually using. See https://stackoverflow.com/questions/1984186/what-is-private-bytes-virtual-bytes-working-set

That said I've found another memory usage win in 9ec57b1. I'll continue to search for ways to reduce it further.

**Comment by Transisto** [comment]
1.6.2

Ran for 1.5 days, 3 wallet open

When I looked at it this morning the wallets were blinking as if unconnected,
Stable 50% CPU usage. 3.1GB, low responsiveness @ 1fps
Now, 30min later it's responsive, 1% CPU, the wallet top icon are solid but the bottom connection is fading in and out slowly.
Number of thread: 240

I sampled the Stack of a some of the newer threads,

0x0000000000000000
ntdll.dll!ZwWaitForSingleObject+0x14
KERNELBASE.dll!WaitForSingleObjectEx+0x8e
jvm.dll!c2v_notifyCompilerInliningEvent+0x21de39
jvm.dll!c2v_notifyCompilerInliningEvent+0x3ac09f
0x0000000000000000
jvm.dll!c2v_notifyCompilerInliningEvent+0x21cd5f
0x0000000000000000


0x0000000000000000
ntdll.dll!ZwWaitForSingleObject+0x14
mswsock.dll+0x9d55
mswsock.dll+0x39d6
WS2_32.dll!select+0x152
nio.dll!Java_sun_nio_ch_WindowsSelectorImpl_00024SubSelector_poll0+0x19d
0x0000000000000000

(NTDLL.dll)
0x0000000000000000
ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
ntdll.dll!EtwNotificationRegister+0x5af
KERNEL32.DLL!BaseThreadInitThunk+0x10
ntdll.dll!RtlUserThreadStart+0x2b


0x0000000000000000
ntdll.dll!ZwWaitForSingleObject+0x14
mswsock.dll+0x9d55
mswsock.dll+0x39d6
WS2_32.dll!select+0x152
nio.dll!Java_sun_nio_ch_WindowsSelectorImpl_00024SubSelector_poll0+0x19d
0x0000000000000000


0x0000000000000000
ntdll.dll!ZwWaitForSingleObject+0x14
mswsock.dll+0x9d55
mswsock.dll+0x39d6
WS2_32.dll!select+0x152
nio.dll!Java_sun_nio_ch_WindowsSelectorImpl_00024SubSelector_poll0+0x19d
0x0000000000000000



0x0000000000000000
ntdll.dll!ZwWaitForSingleObject+0x14
KERNELBASE.dll!WaitForSingleObjectEx+0x8e
jvm.dll!c2v_notifyCompilerInliningEvent+0x21de39
jvm.dll!c2v_notifyCompilerInliningEvent+0x3ac09f
0x0000000000000000
jvm.dll!c2v_notifyCompilerInliningEvent+0x21cd5f
0x0000000000000000


0x0000000000000000
ntdll.dll!ZwWaitForSingleObject+0x14
KERNELBASE.dll!WaitForSingleObjectEx+0x8e
jvm.dll!c2v_notifyCompilerInliningEvent+0x21de39
jvm.dll!c2v_notifyCompilerInliningEvent+0x3ac09f
0x0000000000000000
jvm.dll!c2v_notifyCompilerInliningEvent+0x21cd5f
0x0000000000000000



0x0000000000000000
ntdll.dll!ZwWaitForSingleObject+0x14
KERNELBASE.dll!WaitForSingleObjectEx+0x8e
jvm.dll!c2v_notifyCompilerInliningEvent+0x21de39
jvm.dll!c2v_notifyCompilerInliningEvent+0x3ac09f
0x0000000000000000
jvm.dll!c2v_notifyCompilerInliningEvent+0x21cd5f
0x0000000000000000


0x0000000000000000
ntdll.dll!ZwWaitForSingleObject+0x14
KERNELBASE.dll!WaitForSingleObjectEx+0x8e
jvm.dll!c2v_notifyCompilerInliningEvent+0x401d94
jvm.dll!c2v_notifyCompilerInliningEvent+0x382dca
jvm.dll!c2v_notifyCompilerInliningEvent+0x220666


0x0000000000000000
ntdll.dll!ZwWaitForSingleObject+0x14
KERNELBASE.dll!WaitForSingleObjectEx+0x8e
jvm.dll!c2v_notifyCompilerInliningEvent+0x21de39
jvm.dll!c2v_notifyCompilerInliningEvent+0x3ac09f
0x0000000000000000
jvm.dll!c2v_notifyCompilerInliningEvent+0x21cd5f
0x0000000000000000


0x0000000000000000
ntdll.dll!ZwWaitForSingleObject+0x14
KERNELBASE.dll!WaitForSingleObjectEx+0x8e
jvm.dll!c2v_notifyCompilerInliningEvent+0x21de39
jvm.dll!c2v_notifyCompilerInliningEvent+0x3ac09f
0x0000000000000000
jvm.dll!c2v_notifyCompilerInliningEvent+0x21cd5f
0x0000000000000000


(Threads in the middle)


0x0000000000000000
ntdll.dll!ZwWaitForSingleObject+0x14
mswsock.dll+0x9d55
mswsock.dll+0x39d6
WS2_32.dll!select+0x152
nio.dll!Java_sun_nio_ch_WindowsSelectorImpl_00024SubSelector_poll0+0x19d
0x0000000000000000


0x0000000000000000
ntdll.dll!ZwWaitForSingleObject+0x14
mswsock.dll+0x9d55
mswsock.dll+0x39d6
WS2_32.dll!select+0x152
nio.dll!Java_sun_nio_ch_WindowsSelectorImpl_00024SubSelector_poll0+0x19d
0x0000000000000000



Looks like the wallet isn't closing connection and eventually can't open new ones.
I don't know how flaky the Whirlpool servers are but there's a lot of connection issue in the logs.

2022-03-20 06:20:51,843 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-8324] o.s.w.s.s.c.SockJsClient [null:-1] Initial SockJS "Info" request to server failed, url=wss://pool.whirl.mx:8080/ws/connect
org.springframework.web.socket.sockjs.SockJsTransportFailureException: Failed to execute request to https://pool.whirl.mx:8080/ws/connect/info; nested exception is java.lang.InterruptedException
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.JettyXhrTransport.executeRequest(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.JettyXhrTransport.executeInfoRequestInternal(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.AbstractXhrTransport.executeInfoRequest(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.SockJsClient.getServerInfo(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.SockJsClient.doHandshake(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.messaging.WebSocketStompClient.connect(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.messaging.WebSocketStompClient.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.sparrowwallet.nightjar.stomp.JavaStompClient.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.stomp.client.StompTransport.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.whirlpool.client.mix.dialog.MixSession.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.whirlpool.client.mix.dialog.MixSession$3.onTransportDisconnected(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.stomp.client.StompTransport$1.onError(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.stomp.client.StompTransport$1.onError(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.sparrowwallet.nightjar.stomp.JavaStompClient$1.handleTransportError(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.messaging.simp.stomp.DefaultStompSession.handleFailure(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.messaging.simp.stomp.DefaultStompSession.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.messaging.WebSocketStompClient$WebSocketTcpConnectionHandlerAdapter.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.handler.WebSocketHandlerDecorator.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.AbstractClientSockJsSession.afterTransportClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.WebSocketTransport$ClientSockJsWebSocketHandler.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.adapter.jetty.JettyWebSocketHandlerAdapter.onWebSocketClose(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.websocket.common.WebSocketSession.callApplicationOnClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.disconnect(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.websocket.common.WebSocketSession.onClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.io.AbstractConnection.onClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.io.AbstractConnection.onClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.io.ssl.SslConnection.onClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.io.SelectorManager.connectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source)
	at java.base/java.util.concurrent.CountDownLatch.await(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	... 40 common frames omitted
2022-03-20 06:20:51,844 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-8354] o.s.w.s.s.c.SockJsClient [null:-1] Initial SockJS "Info" request to server failed, url=wss://pool.whirl.mx:8080/ws/connect
org.springframework.web.socket.sockjs.SockJsTransportFailureException: Failed to execute request to https://pool.whirl.mx:8080/ws/connect/info; nested exception is java.lang.InterruptedException
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.JettyXhrTransport.executeRequest(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.JettyXhrTransport.executeInfoRequestInternal(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.AbstractXhrTransport.executeInfoRequest(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.SockJsClient.getServerInfo(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.SockJsClient.doHandshake(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.messaging.WebSocketStompClient.connect(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.messaging.WebSocketStompClient.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.sparrowwallet.nightjar.stomp.JavaStompClient.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.stomp.client.StompTransport.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.whirlpool.client.mix.dialog.MixSession.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.whirlpool.client.mix.dialog.MixSession$3.onTransportDisconnected(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.stomp.client.StompTransport$1.onError(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.stomp.client.StompTransport$1.onError(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.sparrowwallet.nightjar.stomp.JavaStompClient$1.handleTransportError(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.messaging.simp.stomp.DefaultStompSession.handleFailure(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.messaging.simp.stomp.DefaultStompSession.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.messaging.WebSocketStompClient$WebSocketTcpConnectionHandlerAdapter.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.handler.WebSocketHandlerDecorator.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.AbstractClientSockJsSession.afterTransportClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.WebSocketTransport$ClientSockJsWebSocketHandler.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.adapter.jetty.JettyWebSocketHandlerAdapter.onWebSocketClose(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.websocket.common.WebSocketSession.callApplicationOnClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.disconnect(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.websocket.common.WebSocketSession.onClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.io.AbstractConnection.onClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.io.AbstractConnection.onClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.io.ssl.SslConnection.onClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.io.SelectorManager.connectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source)
	at java.base/java.util.concurrent.CountDownLatch.await(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	... 40 common frames omitted
2022-03-20 06:20:51,844 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-8342] o.s.w.s.s.c.SockJsClient [null:-1] Initial SockJS "Info" request to server failed, url=wss://pool.whirl.mx:8080/ws/connect
org.springframework.web.socket.sockjs.SockJsTransportFailureException: Failed to execute request to https://pool.whirl.mx:8080/ws/connect/info; nested exception is java.lang.InterruptedException
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.JettyXhrTransport.executeRequest(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.JettyXhrTransport.executeInfoRequestInternal(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.AbstractXhrTransport.executeInfoRequest(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.SockJsClient.getServerInfo(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.SockJsClient.doHandshake(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.messaging.WebSocketStompClient.connect(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.messaging.WebSocketStompClient.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.sparrowwallet.nightjar.stomp.JavaStompClient.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.stomp.client.StompTransport.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.whirlpool.client.mix.dialog.MixSession.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.whirlpool.client.mix.dialog.MixSession$3.onTransportDisconnected(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.stomp.client.StompTransport$1.onError(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.stomp.client.StompTransport$1.onError(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.sparrowwallet.nightjar.stomp.JavaStompClient$1.handleTransportError(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.messaging.simp.stomp.DefaultStompSession.handleFailure(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.messaging.simp.stomp.DefaultStompSession.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.messaging.WebSocketStompClient$WebSocketTcpConnectionHandlerAdapter.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.handler.WebSocketHandlerDecorator.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.AbstractClientSockJsSession.afterTransportClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.sockjs.client.WebSocketTransport$ClientSockJsWebSocketHandler.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.springframework.web.socket.adapter.jetty.JettyWebSocketHandlerAdapter.onWebSocketClose(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.websocket.common.WebSocketSession.callApplicationOnClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.disconnect(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.websocket.common.WebSocketSession.onClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.io.AbstractConnection.onClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.io.AbstractConnection.onClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.io.ssl.SslConnection.onClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.io.SelectorManager.connectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source)
	at java.base/java.util.concurrent.CountDownLatch.await(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.2/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	... 40 common frames omitted

**Comment by Transisto** [comment]
Same setup, after 28h of run time, 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/388716/159311087-15b0871c-3e9b-4c3b-a0de-3b28ca927be3.png">

**Comment by helpau** [comment]
Can't reproduce on Sparrow 1.7.9. Around 3 days of work on empty wallet on different tabs with and without connection, max memory usage was 681 MB(Private Bytes) and 876 MB(Working Set).
