### ISSUE TITLE
Error Opening Wallet: "this.masterWallet" is null

### ISSUE THREAD

**Issue by ogas2** [sparrowwallet/sparrow#293]
2021-10-29 22:33:19,895 ERROR [JavaFX Application Thread] c.s.s.AppController [null:-1] Error Opening Wallet
java.lang.NullPointerException: Cannot invoke "com.sparrowwallet.drongo.wallet.Wallet.setChildWallets(java.util.List)" because "this.masterWallet" is null
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.io.db.DbPersistence.loadWallet(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.io.db.DbPersistence.loadWallet(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.io.Storage.loadEncryptedWallet(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.io.Storage$LoadWalletService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.io.Storage$LoadWalletService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by craigraw** [comment]
Can you confirm:
- Are you using Windows?
- Were you using the View > Refresh Wallet function before this occurred?
- Are there any errors in the log prior to this error?

It would help to narrow this issue down for a fix.

Unfortunately the wallet file itself is corrupt and will need to be recreated (as a new wallet) from seed/backup.

**Comment by ogas2** [comment]
Using MacOS
I am not sure but think yes I was refreshing wallet

**Comment by craigraw** [comment]
Thanks for the info. Nothing earlier in the log that may indicate what caused this? If so it would likely also have DbPersistence and saveWallet in the stacktrace.
