### ISSUE TITLE
After a 2-3 days, about half of postmix UTXO are "Waiting for broadcast".

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#301]
![image](https://user-images.githubusercontent.com/388716/140833251-00353c73-721d-4071-befd-f33a4526f0c3.png)
![image](https://user-images.githubusercontent.com/388716/140833383-ab97f790-0721-4b03-8ac6-0813dcfdd14b.png)

**Comment by craigraw** [comment]
Your server did not notify Sparrow that the transactions had reached the mempool. There's not much Sparrow can do about this - it actually polls the server (doesn't just wait for the server to notify) but clearly that failed too. Can you confirm what server you are using?

**Comment by Transisto** [comment]
I restarted sparrow, and same thing, after around 12h, it was hard to have it connect to a server.
eventually I manage to connect to bitaroo and lookup all addresses, but that one UTXO is still spinning "Waiting for broadcast"  that little blue spin is also taking 6-7% GPU

**Comment by Transisto** [comment]
The UTXO 47c88ce8cd9e646dd6ac8264422eafcf8d1760e75260832180c9626f892e3200 is the one that keep on spinning.

Looks like it had a bad response once and will never check it again.

Can't seems to be able to connect at all to lukechilds, but electrum connects to it fine.

Resrtarted sparrow, connection to lukechild happen reliably for now.



2021-11-09 11:03:19,046 WARN [JavaFX Application Thread] c.s.w.c.w.d.u.BasicUtxoSupplier [null:-1] findUtxo(47c88ce8cd9e646dd6ac8264422eafcf8d1760e75260832180c9626f892e3200:4): not found
2021-11-09 11:25:59,835 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-5108] c.s.w.c.m.d.MixSession[1636473445453] [null:-1]  ! connexion lost, reconnecting for a new mix...
2021-11-09 11:25:59,836 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-5109] c.s.w.c.m.d.MixSession[1636449032830] [null:-1]  ! connexion lost, reconnecting for a new mix...
2021-11-09 11:27:38,077 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-11-09 11:41:36,963 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-11-09 12:00:42,969 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-11-09 12:00:50,445 ERROR [JavaFX Application Thread] c.g.c.e.E.default [null:-1] Exception thrown by subscriber method walletHistoryChanged(com.sparrowwallet.sparrow.event.WalletHistoryChangedEvent) on subscriber com.sparrowwallet.sparrow.wallet.UtxosController@775ed78b when dispatching event: com.sparrowwallet.sparrow.event.WalletHistoryChangedEvent@7ccccfc5
java.lang.NullPointerException: null
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.wallet.UtxosController.walletHistoryChanged(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber$1.run(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.util.concurrent.DirectExecutor.execute(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber.dispatchEvent(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.EventBus.post(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.wallet.WalletForm.lambda$notifyIfChanged$4(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-11-09 12:05:30,168 ERROR [JavaFX Application Thread] c.g.c.e.E.default [null:-1] Exception thrown by subscriber method walletHistoryChanged(com.sparrowwallet.sparrow.event.WalletHistoryChangedEvent) on subscriber com.sparrowwallet.sparrow.wallet.UtxosController@775ed78b when dispatching event: com.sparrowwallet.sparrow.event.WalletHistoryChangedEvent@5ffba589
java.lang.NullPointerException: null
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.wallet.UtxosController.walletHistoryChanged(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber$1.run(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.util.concurrent.DirectExecutor.execute(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber.dispatchEvent(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.EventBus.post(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.wallet.WalletForm.lambda$notifyIfChanged$4(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-11-09 12:05:30,846 ERROR [JavaFX Application Thread] c.g.c.e.E.default [null:-1] Exception thrown by subscriber method walletHistoryChanged(com.sparrowwallet.sparrow.event.WalletHistoryChangedEvent) on subscriber com.sparrowwallet.sparrow.wallet.UtxosController@775ed78b when dispatching event: com.sparrowwallet.sparrow.event.WalletHistoryChangedEvent@7f904d14
java.lang.NullPointerException: null
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.wallet.UtxosController.walletHistoryChanged(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber$1.run(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.util.concurrent.DirectExecutor.execute(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Subscriber.dispatchEvent(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.eventbus.EventBus.post(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.wallet.WalletForm.lambda$notifyIfChanged$4(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-11-09 12:07:21,825 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by craigraw** [comment]
It appears that at certain times of the day, the public Electrum servers are not reliable. I'm trying to get more added. 

Note that you might be running into ElectrumX resource-based usage limits: https://electrumx.readthedocs.io/en/latest/environment.html#resource-usage-limits

It could be that restarting Sparrow means ElectrumX sees a new client session which resets the resource limits. This is just a guess though, I've haven't looked into how the server recognises clients.

**Comment by craigraw** [comment]
I'm going to close this off as a server issue - noting that the number of public servers needs to be increased.
