### ISSUE TITLE
Cannot load Taproot wallet. Failed to start BWT

### ISSUE THREAD

**Issue by kozo-cz** [sparrowwallet/sparrow#316]
Script Type: Taproot
Policy: tr(BIP39)
Passphrase: No
Password: No
OS: Windows 7 Pro
Version: 1.5.2

I created a new Taproot wallet. Every time I try to open it I get 

 ERROR [JavaFX Application Thread] c.s.s.n.ElectrumServer [null:-1] Failed to start BWT
dev.bwt.libbwt.BwtException: Invalid config: unexpected «tr(1 args) while parsing Miniscript» at line 1 column 1278
	at com.sparrowwallet.merged.module@1.5.2/dev.bwt.libbwt.daemon.NativeBwtDaemon.start(Native Method)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.Bwt.start(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.Bwt.start(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.Bwt$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.Bwt$ConnectionService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by craigraw** [comment]
Indeed, Taproot is not yet supported by BWT: https://github.com/bwt-dev/bwt/issues/91 due to upstream work being required in rust-bitcoin.

The workaround for now is to use an Electrum server.
