### ISSUE TITLE
Support Wayland

### ISSUE THREAD

**Issue by cotsuka** [sparrowwallet/sparrow#329]
Running on a Wayland-only setup, seems like JVM is looking for DISPLAY. Attempted to run on 1.5.2.

```sh
➜  ~ which Sparrow
/usr/bin/Sparrow
➜  ~ Sparrow
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.<init>(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.Application.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.startup(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
	... 5 more
Failed to launch JVM
```

**Comment by Ciphero** [comment]
I'm running Zorin OS 16 with Wayland and Sparrow 1.5.4 is working fine for me.
![image](https://user-images.githubusercontent.com/47178118/146361093-69f86f41-4df7-4e43-8081-5403635b67ab.png)

**Comment by craigraw** [comment]
This comes down to support in the underlying framework Sparrow uses, JavaFX. JavaFX supports XWayland, but not Wayland natively: https://bugs.openjdk.java.net/browse/JDK-8232949

I'm not sure there's anything that can be done further here, so I'm closing this off.

**Comment by handpickencounter** [comment]
Mar 04, 2025
https://wiki.openjdk.org/display/wakefield/Pure+Wayland+toolkit+prototype

java -Dawt.toolkit.name=WLToolkit -Dsun.java2d.vulkan=True J2Ddemo.jar

Not familiar with Java so I'm not sure if this is something which cannot be applied to Sparrow.

**Comment by craigraw** [comment]
Thanks for linking. That work is for a different Java windowing toolkit (AWT) but interesting to see nonetheless. 

Here's where things currently stand with JavaFX: https://mail.openjdk.org/pipermail/openjfx-dev/2024-December/051186.html

**Comment by handpickencounter** [comment]
The problem with x11/xwayland is that you need to employ additional measures to secure it.

x11/xwayland apps by default can both spy and influence each other with no restrictions, this is obviously very bad for a crypto wallet...

This is irrespective of other sandboxing measures, you can have the best sandbox in the world but by just sharing the x11 socket you are insecure, this isn't the case with wayland.

Securing x11 also tends to destroy clipboard functionality: ex. xpra
