### ISSUE TITLE
Paynym retrieve error 1.5.3.beta1

### ISSUE THREAD

**Issue by 6102bitcoin** [sparrowwallet/sparrow#336]
Select utxo, send, click drop down in Pay to field, Paynym 

Error message: Error retrieving PayNym. java.util.concurrent.ExecutionException: java.io.IOException: SOCKS4 tunnel failed with code 91

2021-12-01 18:09:12,820 WARN [Thread-7] c.s.s.n.FeeRatesSource [null:-1] Error retrieving recommended fee rates from http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/api/v1/fees/recommended (SOCKS: TTL expired)
2021-12-01 18:11:21,285 ERROR [JavaFX Application Thread] c.s.s.s.PayNymController [null:-1] Error retrieving PayNym
com.samourai.wallet.api.backend.beans.HttpException: java.util.concurrent.ExecutionException: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.nightjar@0.2.24/com.samourai.http.client.JacksonHttpClient$2.call(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.24/com.samourai.http.client.JacksonHttpClient$2.call(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/io.reactivex.Observable.subscribe(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/io.reactivex.Scheduler$DisposeTask.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/io.reactivex.internal.schedulers.ScheduledRunnable.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/io.reactivex.internal.schedulers.ScheduledRunnable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.client.util.FutureResponseListener.getResult(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.24/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.24/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJsonPost(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.24/com.samourai.http.client.JacksonHttpClient$1.call(Unknown Source)
	... 13 common frames omitted
Caused by: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.onSocks4Response(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.access$300(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection$Socks4Parser.parse(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection$Socks4Parser.access$200(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.onFillable(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.io.FillInterest.fillable(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.io.ChannelEndPoint$2.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(Unknown Source)
	... 1 common frames omitted
2021-12-01 18:12:15,070 WARN [Thread-54] c.s.s.n.FeeRatesSource [null:-1] Error retrieving recommended fee rates from http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/api/v1/fees/recommended (SOCKS: TTL expired)
2021-12-01 18:30:21,116 WARN [Thread-195] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 8 secs

**Comment by craigraw** [comment]
Thanks for the report. Error handling for paynym.is connection issues has been improved in eb498f2.
