### ISSUE TITLE
Paynym retrieve error when using Tor proxy

### ISSUE THREAD

**Issue by emmanuelrosa** [sparrowwallet/sparrow#349]
With version 1.5.3 (and the beta) I get an error when trying to retrieve my PayNym while using a Tor proxy. The error is as follows:

```
2021-12-09 09:46:24,864 ERROR Error retrieving PayNym
com.samourai.wallet.api.backend.beans.HttpException: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused
	at com.sparrowwallet.nightjar@0.2.24/com.samourai.http.client.JacksonHttpClient$2.call(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.24/com.samourai.http.client.JacksonHttpClient$2.call(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/io.reactivex.Observable.subscribe(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/io.reactivex.Scheduler$DisposeTask.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/io.reactivex.internal.schedulers.ScheduledRunnable.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/io.reactivex.internal.schedulers.ScheduledRunnable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.client.util.FutureResponseListener.getResult(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.24/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.24/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJsonPost(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.24/com.samourai.http.client.JacksonHttpClient$1.call(Unknown Source)
	... 13 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.io.SelectorManager.doFinishConnect(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.io.ManagedSelector.processConnect(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.io.ManagedSelector.access$1500(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Unknown Source)
	at com.sparrowwallet.merged.module@1.5.3/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(Unknown Source)
	... 1 common frames omitted

```

It fails right away, so it's not a Tor latency issue. When I disable the Tor proxy (in the server configuration) the PayNym retrieval works.

**Comment by craigraw** [comment]
Strange - it's working on this side through Tor right now. PayNym.is is one of the few Samourai services not available as an .onion address, so there might be something in breaking out of a Tor exit node on your side. Odd that it fails immediately though. Is this with the internal Sparrow Tor proxy or an external one?

**Comment by emmanuelrosa** [comment]
It's with an external Tor proxy.

How does one turn on the internal Tor proxy? I've been using an external one thinking Sparrow didn't come with one.

**Comment by craigraw** [comment]
You need to connect to your Electrum server through a .onion address, have the proxy setting disabled, and the external Tor shutdown if running on port 9050. Not that I think it make much difference to the issue, but might be worth trying.

**Comment by craigraw** [comment]
Any further progress on this? I don't believe it's a Sparrow issue (it would have been reported elsewhere if so by now).

**Comment by emmanuelrosa** [comment]
I was unable to change the proxy's port on the external Tor. Something is not working properly with the NixOS module that configures Tor. And that Tor instance is used by my bitcoind node, which is in turn used by Sparrow. I suppose I'll just turn off the Tor proxy in Sparrow.

**Comment by emmanuelrosa** [comment]
For what it's worth, today retrieving the Paynym worked using the same external Tor. I tried the `Tools -> Show Paynym` feature in 1.5.5 and it worked. About an hour later I tried it again, just for kicks and giggles, and it failed. Right away I pushed the button to retry and it worked :)

**Comment by craigraw** [comment]
I've also seen this kind of intermittent issue. I think the best solution is to have paynym.is exposed as a hidden service, which should remove the need for Tor exit nodes. Samourai are implementing this.

**Comment by RequestPrivacy** [comment]
Had the same problem but from one moment to the other it started to work again. So I think not a Sparrow issue. I leave the log here nevertheless. It seems to differ a little bit from the posted one above, so I don't know if it adds some value.

```
2022-03-17 10:35:10,255 ERROR [JavaFX Application Thread] c.s.s.p.PayNymController [null:-1] Error retrieving PayNym
com.samourai.wallet.api.backend.beans.HttpException: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.http.client.JacksonHttpClient$2.call(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.http.client.JacksonHttpClient$2.call(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/io.reactivex.Observable.subscribe(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/io.reactivex.Scheduler$DisposeTask.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/io.reactivex.internal.schedulers.ScheduledRunnable.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/io.reactivex.internal.schedulers.ScheduledRunnable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.client.util.FutureResponseListener.getResult(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJsonPost(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.http.client.JacksonHttpClient$1.call(Unknown Source)
	... 13 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.io.SelectorManager.doFinishConnect(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.io.ManagedSelector.processConnect(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.io.ManagedSelector.access$1500(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(Unknown Source)
	... 1 common frames omitted

```
