### ISSUE TITLE
Silent error when creating transaction

### ISSUE THREAD

**Issue by CherryDT** [sparrowwallet/sparrow#356]
I filled in a transaction as follows:

![image](https://user-images.githubusercontent.com/6010463/145717063-1f8acd90-1081-4530-9752-2fb270debc62.png)

But when clicking "Create Transaction", nothing happened. The logs revealed that it silently failed.

Probably the most relevant part:

```none
Caused by: java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 1
        ...
	at java.base/java.util.Collections$UnmodifiableList.get(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTInput.getUtxo(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTInput.isTaproot(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTInput.getDefaultSigHash(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTInput.<init>(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.<init>(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.<init>(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.wallet.WalletTransaction.createPSBT(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.4/com.sparrowwallet.sparrow.wallet.SendController.createTransaction(Unknown Source)
```

Full exception:

```none
2021-12-12 15:43:06,191 ERROR [JavaFX Application Thread] c.s.s.MainApp [null:-1] Exception in thread "JavaFX Application Thread"
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Node.fireEvent(Unknown Source)
	at javafx.controls/javafx.scene.control.Button.fire(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.reflect.Trampoline.invoke(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(Unknown Source)
	at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(Unknown Source)
	... 59 common frames omitted
Caused by: java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at java.base/java.util.Collections$UnmodifiableList.get(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTInput.getUtxo(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTInput.isTaproot(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTInput.getDefaultSigHash(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTInput.<init>(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.<init>(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.<init>(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.wallet.WalletTransaction.createPSBT(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.4/com.sparrowwallet.sparrow.wallet.SendController.createTransaction(Unknown Source)
	... 69 common frames omitted

```

In case it's relevant, here is how the UTXOs looked like:

![image](https://user-images.githubusercontent.com/6010463/145717184-195a399b-0494-4b2c-a2a3-2cff5aa1e648.png)

![image](https://user-images.githubusercontent.com/6010463/145717212-cac4b517-89fb-4fc9-9296-8f27b8fd859d.png)

![image](https://user-images.githubusercontent.com/6010463/145717225-6da6dc1b-3bf8-43b6-9bf4-31cbc6ddc593.png)

**NOTE:** It _does_ work when I change the amount so that it uses either just the 1st UTXO shown here or the 2nd+3rd. It also works when it uses additional UTXOs beyond the 3 ones shown. But when it uses exactly those 3, it fails.

**Comment by craigraw** [comment]
Thanks for the detailed report. I've tried unsuccessfully to reproduce this error - my best guess at this time is that your server has served some bad data to your wallet. I'm not 100% convinced of this, but it's worth checking out. You can do so in two ways:
1. Examine (in Sparrow) the transaction starting with `4a...` - use the magnifying glass icon in the Transactions tab for example. Check that the outputs match the inputs in the transaction you were creating.
2. If this is a test wallet, try connecting to a public server and refreshing the wallet (View menu). Then try create the transaction again.

Also, if you're prepared to run from source it would be helpful to see the line numbers of the exception (instructions in the project README). There are two lines in `getUtxo()` that might be causing this.

**Comment by CherryDT** [comment]
Unfortunately I've now spent those outputs already so it's hard to encounter the exception again. Note however my edit at the very bottom: It sounds strange that any single one of these UTXOs could cause the issue because any of them alone or in combination of two of them it was OK, also with additional ones, just those exact three in combination caused the exception.

Anyway, I looked at the transaction details and it's all as expected, and matching what the preview showed. The only thing of note here is that this transaction has the exact same outputs (same amount and address) twice, as indices 0 and 2, which is uncommon but not unheard of.

I cannot publish the exact transaction IDs here, as this is work-related. But I sent you a private email with the information in case it is helpful.

The server I'm connected to is a server I run myself, it's ElectrumX 0.16.0 with Bitcoin Core 22.0.

By the way I realized there is no search function in the transaction list! That would be amazing to have.

_Side note: This is an amazing wallet. You have no idea how delightful it is to have finally found something that gives you all the power, visibility and tools you need (and also sticks to proper desktop UI without reinventing the wheel for the gazillionth time) while still being easy to use._

**Comment by CherryDT** [comment]
Hah! I was able to get the exception again. This time it's three different transactions as inputs, but the `46...` transaction is involved again... I'll see if I can build from source and debug this.

**Comment by craigraw** [comment]
Great, thanks!

Interesting that it's not the `4a...` transaction but the other one, which appears to be very normal.

**Comment by CherryDT** [comment]
It's the second `get` call:

```none
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
```
![image](https://user-images.githubusercontent.com/6010463/145812261-62fac78a-5398-4fe2-b1e4-1759e770f1e7.png)

This TX has only one output (no change). This is correct.

![image](https://user-images.githubusercontent.com/6010463/145812773-74599c04-e9be-4d14-960c-d510b023e52f.png)

So the question is why the wallet tries to access output `[1]`. (This time it's 1, last time it was 2.)

Now, here's the thing. Something doesn't match up between the `transaction`/`index` and the `nonWitnessUtxo`:

![image](https://user-images.githubusercontent.com/6010463/145814361-6a159098-6f62-4f9c-9794-49f0dbe89458.png)

`transaction.inputs[1]` is UTXO `28...:1`. However, the `nonWitnessUtxo` is `46...:0` (that would be `transaction.inputs[2]`), and for the input index 1 of the new transaction, `isTaproot` appears to attempt accessing `46...:1` (not `28...:1`) which fails.

Do you need me to continue digging? If yes, please tell me where to go from here, what to check/test. Thank you.

**Comment by CherryDT** [comment]
Update: I dug a bit further, and it seems there is some sort of mess in the order of inputs when the PSBT is created in the first place.

`transaction.inputs` is `[95...:0, 28...:1, 46...:0]`, but `walletTransaction.selectedUtxoSets[0]` is `[28...:1, 46...:0, 95...:0]`!

For this reason, eventually we end up with this call:

```
PSBTInput psbtInput = new PSBTInput(
  this,
  wallet.getScriptType(), // "P2PKH"
  transaction, // has inputs of [95...:0, 28...:1, 46...:0]
  inputIndex, // 1, i.e. pointing to 28...:1
  utxo, // TX 46... !!! and not 28...
  utxoIndex, // 0
  redeemScript, // null
  witnessScript, // null
  derivedPublicKeys,
  Collections.emptyMap(),
  tapInternalKey, // null
  alwaysIncludeWitnessUtxo // true
);
```

**Comment by craigraw** [comment]
Thanks for the detailed debugging! This looks like a regression introduced in https://github.com/sparrowwallet/drongo/commit/7ac4bce14f04163c57b94e34945b5e4a1bf79eb6. 

I've fixed it in [3131b26](https://github.com/sparrowwallet/drongo/commit/3131b265a5c9c18d33af4ee67b273ab4df1bf4a1) (and it's followup), which uses an ordered maps to retain stable ordering for `walletTransaction.selectedUtxoSets[0]`. Although it's strange that the Map is changing the order of keys between iterations (i.e. without any modification), the order is not guaranteed with a normal `HashMap` leading to the problem (perhaps only occurring on certain platforms).

Please could you test? Update your source with
```
git pull --recurse-submodules
```

Much appreciated!

**Comment by craigraw** [comment]
> The pull didn't suffice because the repo was still referring to `20ec0f9` for the submodule

Indeed - long day! Fixed.

> It's working now. Thank you for your swift response to this issue!

Excellent - thank you again for the detailed debugging. This one would have been difficult to find without reproduction.

**Comment by craigraw** [comment]
ICYMI - Sparrow v1.5.5 has been released which fixes this problem.
