### ISSUE TITLE
Could Not Sign PSBT 

### ISSUE THREAD

**Issue by supernotic** [sparrowwallet/sparrow#388]
Trying to sign transaction with Ledger Device
Policy Type: Single Signature
Inputs: 40 
I was able to sign transaction using Electrum. 

Below is the log. Let me know what additional information I can provide. Thanks

 =====================
 
 2022-01-09 08:07:34,631 ERROR [JavaFX Application Thread] c.s.s.c.DevicePane [null:-1] Signing Error: Could not sign PSBT
com.sparrowwallet.sparrow.io.SignTransactionException: Could not sign PSBT
	at com.sparrowwallet.sparrow@1.5.5/com.sparrowwallet.sparrow.io.Hwi.signPSBT(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.5/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.5/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Cannot run program "C:\Users\.....\AppData\Local\Temp\hwi-2.0.24428619347882203870.tmp": CreateProcess error=206, The filename or extension is too long
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.5/com.sparrowwallet.sparrow.io.Hwi.execute(Unknown Source)
	... 11 common frames omitted
Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 14 common frames omitted

**Comment by craigraw** [comment]
Thanks for the report, fixed in 7f2d72e.
