### ISSUE TITLE
RBF function

### ISSUE THREAD

**Issue by captJiri** [sparrowwallet/sparrow#417]
Hi, i right-clicked on RBF function on the TX waiting to be approved in Mp. But nothing happened. TX was approved while after that but I just wanted to try how rbf works. Are there any conditions when RBF works or not - or is it some way automatic ... How that works? Thanks a lot for reply.
@coinmasteroid

**Comment by craigraw** [comment]
Can you check the log file (Help menu) to see if there is anything at the end that might indicate why it failed?

**Comment by captJiri** [comment]
I will check with the next TX but it takes a while... to add info, i run own umbrel node in combo with sparrow + ledger HW. If that would have some influence ...

**Comment by craigraw** [comment]
The information is still in the log file - you don't need to recreate the problem. Just look for any errors at the time of posting your original issue - each error has a timestamp.

**Comment by captJiri** [comment]
This is the info from Log file on that day when tried to increase fee by RBF function:

2022-02-06 11:09:47,551 ERROR [JavaFX Application Thread] c.s.s.c.DevicePane [null:-1] Signing Error: read error
com.sparrowwallet.sparrow.io.SignTransactionException: read error
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.io.Hwi.signPSBT(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-02-06 12:15:56,225 WARN [Thread-372] c.s.s.n.FeeRatesSource [null:-1] Error retrieving recommended fee rates from http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/api/v1/fees/recommended (SOCKS server general failure)

**Comment by craigraw** [comment]
Thanks for this - unfortunately, it doesn't appear to be related to the RBF issue you experienced. It may be that there was no logging as a result of that error - if this the case then we have little to go on. Are there any other logs from 6 Feb?

**Comment by captJiri** [comment]
This is all of the log. But let me ask this that came on my mind - while was clicking on RBF on the TX, my HW Ledger was disconnected - couldn't be this the cause? Some months ago i did try RBF same way already and didn't work either - nothing happened after click on RBF. So maybe it has something to do with the HW device.

**Comment by craigraw** [comment]
There's nothing in the RBF function that needs the HWW, so I don't think it's related.

It's not possible to use RBF if there is insufficient change on the existing transaction and you don't have any additional UTXOs to add to the replacement. But that's an unlikely scenario, and would not result in "nothing happened" - you should still see the transaction that Sparrow attempted to create.

Just to be clear, when you say you "right-clicked on RBF function" do you mean you right-clicked on the "Unconfirmed" label and selected the `Increase Fee (RBF)` item from the context menu?

**Comment by captJiri** [comment]
Exactly as you say with right click... 

Plus you reminded me, i had no other utxo to take an additional fee to increase by the way 🤦‍♂️. 

But if i still would see some screen and some RBF action, i did not. 

Next time i try i will send you log straight away... thanks.
