### ISSUE TITLE
Error loading transactions: Failed to subscribe to path

### ISSUE THREAD

**Issue by ln3xp** [sparrowwallet/sparrow#430]
Running Sparrow 1.5.6 connected to Electrum Personal Server via port forwarding.

Used to work great and suddenly started failing.

Connection does succeed both when testing

```
Connected to ElectrumPersonalServer 0.2.2 on protocol version 1.4
Server Banner: Welcome to Electrum Personal Server 0.2.2

Monitoring 2 deterministic wallets, in total 4000 addresses.

Connected bitcoin node: /Satoshi:22.0.0/
```

and as shown in the blue toggle button ("Connected to ssl://127.0.0.1:50002 at height 723896").

It however fails finding transactions (same for all wallets)

```
Wallet loading history for first - Deposit
[Feb 18 11:47:30] Finding transactions for ../0/0
[Feb 18 11:47:34] Failed to subscribe to path: ../0/0
```

Logs:

```
2022-02-18 11:49:49,941 ERROR [JavaFX Application Thread] c.s.s.w.WalletForm [null:-1] Error retrieving wallet history
com.sparrowwallet.sparrow.net.ServerException: Failed to subscribe to path: m/0/0
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.ElectrumServer.subscribeWalletNodes(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.ElectrumServer.getHistory(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.ElectrumServer.getHistory(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.subscribeScriptHashes(Unknown Source)
	... 13 common frames omitted
Caused by: java.lang.IllegalStateException: I/O error during a request processing
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeRequest(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeAndConvert(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeNullable(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.lambda$subscribeScriptHashes$6(Unknown Source)
	... 15 common frames omitted
Caused by: java.io.IOException: Error reading response: Could not connect to server at ssl://127.0.0.1:50002
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.TcpTransport.readResponse(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.TcpTransport.pass(Unknown Source)
	... 19 common frames omitted
Caused by: java.io.IOException: Could not connect to server at ssl://127.0.0.1:50002
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.TcpTransport.readInputStream(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	... 1 common frames omitted
```

What could be going on?  Both bitcoind and EPS are running with no errors. I restarted both Sparrow and EPS several times but no luck.

**Comment by craigraw** [comment]
It seems that even though EPS is "running" it has not opened port 50002, or you cannot reach that port on localhost. Could it be that the port forwarding setup has changed?

You can try to verify this with
```
telnet localhost 50002
```
and see if you can connect.

**Comment by ln3xp** [comment]
Thanks Craig.  Yes, it does reach port 50002.

```
~ ❯ telnet localhost 50002
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
```

Port forwarding seems correct running `ssh -N -L 50002:127.0.0.1:50002 node -v` and watching the output.

What else could be causing the issue?

**Comment by craigraw** [comment]
Effectively then, the problem is that EPS is receiving the request from the Sparrow, but not responding to it. Are there no logs in EPS that might indicate what is at fault? You might try the Electrum wallet client to verify this.

**Comment by ln3xp** [comment]
Solved it!  It was my mistake but the confusing messaging/UX from the Sparrow/EPS combo didn't help.

I was specifically trying to check transactions on the deposit wallet so this is the only zpub I added to EPS `config.ini`. Starting up EPS showed the first 3 correct addresses giving the impression that the configuration was right. The wallet however is composed of 4 different wallets (deposit, pre, post, bad).

Sparrow tries to fetch addresses for all four wallets even when only the deposit tab is selected. As soon as the first one from e.g. premix is requested, EPS simply closes the connection and naturally Sparrow shows this in the logs.

I guess I would have expected retrieving txs/addrs for the deposit wallet and not for the rest, and certainly not having EPS shutting down the connection when not recognizing an address.

```
WARNING:2022-02-21 09:51:46,056: Address not known to server, hash(address) = 8857594f8257d50eeeeeb892f21dd6e3854bdd2e0f8d7183da4.
Check that you've imported the master public key(s) correctly. The first three addresses of each key are printed out on startup,
so check that they really are addresses you expect. In Electrum go to Wallet -> Information to get the right master public key.
DEBUG:2022-02-21 09:51:46,056: Disconnecting client due to misconfiguration. User must correctly configure master public key(s)
```

**Comment by ln3xp** [comment]
I wanted to add a thank you for the amazing software!

**Comment by craigraw** [comment]
Thanks for the update! Strange behaviour from EPS indeed. Using the built in EPS-alternative (BWT) in Sparrow is another way to approach this - you can connect to Bitcoin Core directly in Sparrow using it.

**Comment by ProfEduStream** [comment]
Hi guys,

I'm sorry to bother you, but i do have the exact same problem and i can't find the solution..

I've created a post on bitcointalk about that: https://bitcointalk.org/index.php?topic=5473740.msg63141548#msg63141548


To be precize, i think the port 50002 is okay (listening), and i added the master public keyS as you said. However, i do think the problem is like compatibility 'cause there are lots of mpk in the config.ini file whereas, in the bitcoin core node, there's only the wallet which had been created + the watch only one (which is, i guess, about the first mpk).

Have you got explanations or help? Any advice will be great !

**Comment by craigraw** [comment]
@ProfEduStream use the EPS option in File > Export Wallet to configure Electrum Personal Server. Make sure you have added all the lines to config.ini - you are missing the one for BIP47 notification address.

**Comment by ProfEduStream** [comment]
Thanks @craigraw. I did so, and it now works. Thank you !

To sum up, the problem was about the bitcoin core watch-only address, which i didn't have in my config.ini file.
I'm curious: where does this "watch-only address" come from?

'gonna make a video tutorial about it.

Have a beautiful day !

**Comment by craigraw** [comment]
As noted above, it's the BIP47 notification address which Sparrow scans to see if there are any new linked wallets. See the BIP47 specification for more details.
