### ISSUE TITLE
Airgapped coldcard and sparrow- Error broadcasting tx...

### ISSUE THREAD

**Issue by helloMrSovereign** [sparrowwallet/sparrow#444]
Connected to public blockstream server. I get this error. Can someone please help I'm about to lose it

2022-02-27 21:09:40,921 ERROR [JavaFX Application Thread] c.s.s.t.HeadersController [null:-1] Error broadcasting transaction
com.sparrowwallet.sparrow.net.ServerException: Cannot invoke "java.net.Socket.getOutputStream()" because "this.socket" is null
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.ElectrumServer.broadcastTransaction(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.ElectrumServer.broadcastTransactionPrivately(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.ElectrumServer$BroadcastTransactionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.ElectrumServer$BroadcastTransactionService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ElectrumServerRpcException: Cannot invoke "java.net.Socket.getOutputStream()" because "this.socket" is null
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.broadcastTransaction(Unknown Source)
	... 12 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.Socket.getOutputStream()" because "this.socket" is null
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.TcpTransport.writeRequest(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.TcpTransport.pass(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeRequest(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeAndConvert(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.lambda$broadcastTransaction$15(Unknown Source)
	at com.sparrowwallet.sparrow@1.5.6/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	... 13 common frames omitted

**Comment by craigraw** [comment]
Try a different public server in the Server Preferences - sometimes, a public server is overloaded or your connection to it is not working.
