### ISSUE TITLE
Process keep running when closed (after running for ~12h)

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#457]
Resemble https://github.com/sparrowwallet/sparrow/issues/455

Running on Windows, 
Problem happen when wallet is closed after a little while (6-24h)

There are usually connection problems happening before it can't close properly.

These are some details of the hung process.

These threads close and reopen as shown in red.
![image](https://user-images.githubusercontent.com/388716/156897833-352e5af9-ec02-4009-bb1f-5317f822f565.png)

![image](https://user-images.githubusercontent.com/388716/156897939-ee09d8ca-8d6e-417e-a559-d76b9567ffdc.png)

![image](https://user-images.githubusercontent.com/388716/156897852-e61fd994-37ac-4221-96b4-4d7c07f23d04.png)

![image](https://user-images.githubusercontent.com/388716/156897866-ce526ef6-0099-43cb-a1fd-56a4b89ad12e.png)

![image](https://user-images.githubusercontent.com/388716/156897880-9e980f51-0da3-4da4-beb7-64f9469b4de4.png)

Here are the last logs.
`2022-03-05 13:48:41,981 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.1/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.1/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-03-05 13:48:42,009 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-3385] c.s.w.c.m.d.MixSession[1646502612634] [null:-1]  ! connexion lost, reconnecting for a new mix...
2022-03-05 13:48:42,010 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-3414] c.s.w.c.m.d.MixSession[1646505975542] [null:-1]  ! connexion lost, reconnecting for a new mix...
2022-03-05 13:49:12,024 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-3385] o.s.w.s.s.c.SockJsClient [null:-1] Initial SockJS "Info" request to server failed, url=wss://pool.whirl.mx:8080/ws/connect
org.springframework.web.socket.sockjs.SockJsTransportFailureException: Failed to execute request to https://pool.whirl.mx:8080/ws/connect/info; nested exception is java.lang.InterruptedException
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.sockjs.client.JettyXhrTransport.executeRequest(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.sockjs.client.JettyXhrTransport.executeInfoRequestInternal(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.sockjs.client.AbstractXhrTransport.executeInfoRequest(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.sockjs.client.SockJsClient.getServerInfo(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.sockjs.client.SockJsClient.doHandshake(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.messaging.WebSocketStompClient.connect(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.messaging.WebSocketStompClient.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.sparrowwallet.nightjar.stomp.JavaStompClient.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.stomp.client.StompTransport.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.whirlpool.client.mix.dialog.MixSession.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.whirlpool.client.mix.dialog.MixSession$3.onTransportDisconnected(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.stomp.client.StompTransport$1.onError(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.stomp.client.StompTransport$1.onError(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.sparrowwallet.nightjar.stomp.JavaStompClient$1.handleTransportError(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.messaging.simp.stomp.DefaultStompSession.handleFailure(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.messaging.simp.stomp.DefaultStompSession.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.messaging.WebSocketStompClient$WebSocketTcpConnectionHandlerAdapter.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.handler.WebSocketHandlerDecorator.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.sockjs.client.AbstractClientSockJsSession.afterTransportClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.sockjs.client.WebSocketTransport$ClientSockJsWebSocketHandler.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.adapter.jetty.JettyWebSocketHandlerAdapter.onWebSocketClose(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor100.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.websocket.common.WebSocketSession.callApplicationOnClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.disconnect(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.websocket.common.WebSocketSession.onClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.io.AbstractConnection.onClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.io.AbstractConnection.onClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.io.ssl.SslConnection.onClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.io.SelectorManager.connectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source)
	at java.base/java.util.concurrent.CountDownLatch.await(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	... 39 common frames omitted
2022-03-05 13:49:12,024 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-3414] o.s.w.s.s.c.SockJsClient [null:-1] Initial SockJS "Info" request to server failed, url=wss://pool.whirl.mx:8080/ws/connect
org.springframework.web.socket.sockjs.SockJsTransportFailureException: Failed to execute request to https://pool.whirl.mx:8080/ws/connect/info; nested exception is java.lang.InterruptedException
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.sockjs.client.JettyXhrTransport.executeRequest(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.sockjs.client.JettyXhrTransport.executeInfoRequestInternal(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.sockjs.client.AbstractXhrTransport.executeInfoRequest(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.sockjs.client.SockJsClient.getServerInfo(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.sockjs.client.SockJsClient.doHandshake(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.messaging.WebSocketStompClient.connect(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.messaging.WebSocketStompClient.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.sparrowwallet.nightjar.stomp.JavaStompClient.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.stomp.client.StompTransport.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.whirlpool.client.mix.dialog.MixSession.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.whirlpool.client.mix.dialog.MixSession$3.onTransportDisconnected(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.stomp.client.StompTransport$1.onError(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.samourai.stomp.client.StompTransport$1.onError(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.32/com.sparrowwallet.nightjar.stomp.JavaStompClient$1.handleTransportError(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.messaging.simp.stomp.DefaultStompSession.handleFailure(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.messaging.simp.stomp.DefaultStompSession.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.messaging.WebSocketStompClient$WebSocketTcpConnectionHandlerAdapter.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.handler.WebSocketHandlerDecorator.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.sockjs.client.AbstractClientSockJsSession.afterTransportClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.sockjs.client.WebSocketTransport$ClientSockJsWebSocketHandler.afterConnectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.springframework.web.socket.adapter.jetty.JettyWebSocketHandlerAdapter.onWebSocketClose(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor100.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.websocket.common.WebSocketSession.callApplicationOnClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.disconnect(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.websocket.common.WebSocketSession.onClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.io.AbstractConnection.onClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.io.AbstractConnection.onClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.io.ssl.SslConnection.onClose(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.io.SelectorManager.connectionClosed(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source)
	at java.base/java.util.concurrent.CountDownLatch.await(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.1/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	... 39 common frames omitted`

**Comment by craigraw** [comment]
> There are usually connection problems happening before it can't close properly.

I think this comment probably holds the key to the issue. Does this only occur when Whirlpool has been used?

Is it possible to get a thread dump of the application when this issue occurs? It would show which threads are still running. A thread dump can be obtained by running from source (see project README) and pressing Ctrl+Break in the cmd window. Alternatively, [install a JDK](https://adoptium.net/?variant=openjdk16)  and run
```
jstack -l PID
```

when Sparrow is in the described state. In the previous screenshots, the PID of Sparrow.exe was 64536. Please copy the output to this issue. Using `jstack` is described in more detail here: https://access.redhat.com/solutions/19170

**Comment by craigraw** [comment]
Good news - I've managed to reproduce this (it seems to be Windows only behaviour). 

I've fixed it in d865176 and tested the fix after running with Whirlpool, internal Tor etc for over 24 hours. Everything shutdown correctly.
