### ISSUE TITLE
Error retrieving wallet history

### ISSUE THREAD

**Issue by outpoints** [sparrowwallet/sparrow#47]
Not sure what causes this. Wallet loads fine on Electrum 4.0.5.

```
2020-11-28 14:35:03,982 WARN [ElectrumServerReadThread] c.s.s.n.SubscriptionService [null:-1] Received script hash status update for unsubscribed script hash: censored
2020-11-28 14:35:36,241 WARN [ElectrumServerReadThread] c.s.s.n.SubscriptionService [null:-1] Received script hash status update, but status has not changed
2020-11-28 14:35:36,242 WARN [ElectrumServerReadThread] c.s.s.n.SubscriptionService [null:-1] Received script hash status update, but status has not changed
2020-11-28 14:35:52,551 WARN [ElectrumServerReadThread] c.s.s.n.SubscriptionService [null:-1] Received script hash status update, but status has not changed
2020-11-28 14:36:25,756 WARN [ElectrumServerReadThread] c.s.s.n.SubscriptionService [null:-1] Received script hash status update, but status has not changed
2020-11-28 14:36:58,462 WARN [ElectrumServerReadThread] c.s.s.n.SubscriptionService [null:-1] Received script hash status update, but status has not changed
2020-11-28 14:37:15,260 WARN [ElectrumServerReadThread] c.s.s.n.SubscriptionService [null:-1] Received script hash status update, but status has not changed
2020-11-28 14:37:15,261 WARN [ElectrumServerReadThread] c.s.s.n.SubscriptionService [null:-1] Received script hash status update, but status has not changed
2020-11-28 14:37:31,425 WARN [ElectrumServerReadThread] c.s.s.n.SubscriptionService [null:-1] Received script hash status update, but status has not changed
2020-11-28 14:37:47,539 WARN [ElectrumServerReadThread] c.s.s.n.SubscriptionService [null:-1] Received script hash status update, but status has not changed
2020-11-28 14:38:04,115 WARN [ElectrumServerReadThread] c.s.s.n.SubscriptionService [null:-1] Received script hash status update, but status has not changed
2020-11-28 14:38:04,115 WARN [ElectrumServerReadThread] c.s.s.n.SubscriptionService [null:-1] Received script hash status update, but status has not changed
2020-11-28 14:38:36,763 WARN [ElectrumServerReadThread] c.s.s.n.SubscriptionService [null:-1] Received script hash status update, but status has not changed
2020-11-28 14:38:36,763 WARN [ElectrumServerReadThread] c.s.s.n.SubscriptionService [null:-1] Received script hash status update, but status has not changed
2020-11-28 14:38:52,765 WARN [Thread-35] c.s.s.n.SimpleElectrumServerRpc [null:-1] Failed to retrieve fee rate for target blocks: 1 (Retries exhausted)
2020-11-28 14:48:10,619 WARN [ElectrumServerReadThread] c.s.s.n.SubscriptionService [null:-1] Received script hash status update, but status has not changed
2020-11-28 14:48:26,752 WARN [ElectrumServerReadThread] c.s.s.n.SubscriptionService [null:-1] Received script hash status update, but status has not changed
2020-11-28 14:48:42,980 WARN [ElectrumServerReadThread] c.s.s.n.SubscriptionService [null:-1] Received script hash status update, but status has not changed
2020-11-28 14:49:15,960 WARN [ElectrumServerReadThread] c.s.s.n.SubscriptionService [null:-1] Received script hash status update, but status has not changed
2020-11-28 14:49:32,144 ERROR [JavaFX Application Thread] c.s.s.w.WalletForm [null:-1] Error retrieving wallet history
com.sparrowwallet.sparrow.net.ServerException: Failed to retrieve reference for path: m/0/156
	at com.sparrowwallet.sparrow@0.9.8/com.sparrowwallet.sparrow.net.ElectrumServer.subscribeWalletNodes(Unknown Source)
	at com.sparrowwallet.sparrow@0.9.8/com.sparrowwallet.sparrow.net.ElectrumServer.getHistory(Unknown Source)
	at com.sparrowwallet.sparrow@0.9.8/com.sparrowwallet.sparrow.net.ElectrumServer.getHistory(Unknown Source)
	at com.sparrowwallet.sparrow@0.9.8/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@0.9.8/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@0.9.8/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	at com.sparrowwallet.sparrow@0.9.8/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.subscribeScriptHashes(Unknown Source)
	... 13 common frames omitted
Caused by: java.lang.IllegalStateException: I/O error during a request processing
	at com.sparrowwallet.merged.module@0.9.8/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeRequest(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.8/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeAndConvert(Unknown Source)
	at com.sparrowwallet.merged.module@0.9.8/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeNullable(Unknown Source)
	at com.sparrowwallet.sparrow@0.9.8/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.lambda$subscribeScriptHashes$6(Unknown Source)
	... 15 common frames omitted
Caused by: java.io.IOException: No response from server
	at com.sparrowwallet.sparrow@0.9.8/com.sparrowwallet.sparrow.net.TcpTransport.readResponse(Unknown Source)
	at com.sparrowwallet.sparrow@0.9.8/com.sparrowwallet.sparrow.net.TcpTransport.pass(Unknown Source)
	... 19 common frames omitted```

**Comment by craigraw** [comment]
In short, all Electrs issues as discussed in https://github.com/sparrowwallet/sparrow/issues/36

Did you try Electrs 0.8.6? I see mynode upgraded to it this week.

**Comment by outpoints** [comment]
It is running 0.8.6 @craigraw :(
Need any other info?

**Comment by craigraw** [comment]
Ok, was hoping that 0.8.6 would help. Looks like the real solution will only be in the forthcoming major release (which I referred to in the previous issue). 

Could you give me a rough idea how many used addresses are in this wallet?

/cc @romanz

**Comment by outpoints** [comment]
200+ addresses @craigraw 
Why does Electrum work flawlessly though? It loads the wallet but Sparrow doesn't work :/

**Comment by craigraw** [comment]
My best understanding of that is here: https://github.com/sparrowwallet/sparrow/issues/36#issuecomment-729497983

I think you'll find that even with Electrum, Electrs is running at 100% CPU with that wallet loaded.

**Comment by outpoints** [comment]
> 
> 
> My best understanding of that is here: [#36 (comment)](https://github.com/sparrowwallet/sparrow/issues/36#issuecomment-729497983)
> 
> I think you'll find that even with Electrum, Electrs is running at 100% CPU with that wallet loaded.

Oh duh, sorry haha
Hope electrs-next is released soon then! Sparrow is such a nice looking wallet, I'm really looking forward to trying it!
