### ISSUE TITLE
Cant sign Transaction

### ISSUE THREAD

**Issue by Mitc0in** [sparrowwallet/sparrow#485]
1. I shutdown the connection to the internet
2. I create a taproot wallet with derivation m/86...
3. I export the xpub to create the only watch wallet in bluewallet
4. I send sats to a legacy adress of this only watch wallet
5. I start sparrow with internet and public server connection
6. I change the script type to legacy and safed to the derivation m/87...
7. Now I can see the sats and the address but cant sign them for spend

There is no error message. I use my wallet password and press sign but nothing happens.

I restarted sparrow and somehow the xpub changed.

Pls help me!

**Comment by Mitc0in** [comment]
There is no error message. I use my wallet password and press sign but nothing happens.

**Comment by craigraw** [comment]
Can you check the log file (Help menu) for an error when you sign? It would be interesting to know what the error is.

To recover the funds:
1. Turn off derivation path validation in Sparrow (General Preferences)
2. Create a new wallet in Sparrow
3. Set the script type to Legacy
4. Enter the seed words (Software wallet)
5. Before importing the seed words, change to a custom derivation path of `m/86'/0'/0'`
6. Import the seed words

You should now have the same xpub as you entered into BW, and be able to spend the funds. BTW, this issue is caused by BW incorrectly assuming that all xpubs reference legacy wallets.

**Comment by Mitc0in** [comment]
Thanks, you safed my life!

the logfile says:

2022-03-24 10:49:16,726 WARN [Thread-82] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (api.coingecko.com)
2022-03-24 10:54:16,726 WARN [Thread-93] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (api.coingecko.com)
2022-03-24 10:59:16,726 WARN [Thread-104] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (api.coingecko.com)
2022-03-24 11:04:16,728 WARN [Thread-115] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (api.coingecko.com)
2022-03-24 11:09:16,728 WARN [Thread-126] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (api.coingecko.com)
2022-03-24 11:14:16,729 WARN [Thread-137] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (api.coingecko.com)
2022-03-24 11:19:16,730 WARN [Thread-148] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (api.coingecko.com)
2022-03-24 11:24:16,731 WARN [Thread-159] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (api.coingecko.com)
2022-03-24 11:29:16,732 WARN [Thread-170] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (api.coingecko.com)
2022-03-24 11:34:16,732 WARN [Thread-181] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (api.coingecko.com)
2022-03-24 11:39:16,734 WARN [Thread-192] c.s.s.n.ExchangeSource [null:-1] Error retrieving currency rates (api.coingecko.com)
2022-03-24 12:08:52,003 ERROR [JavaFX Application Thread] c.g.c.e.E.default [null:-1] Exception thrown by subscriber method openWallets(com.sparrowwallet.sparrow.event.OpenWalletsEvent) on subscriber com.sparrowwallet.sparrow.transaction.HeadersController@20538f93 when dispatching event: com.sparrowwallet.sparrow.event.OpenWalletsEvent@3ee58f3a
java.lang.IllegalArgumentException: Pubkey of partial signature does not match wallet pubkey
  at com.sparrowwallet.drongo/com.sparrowwallet.drongo.wallet.Wallet.finalise(Unknown Source)
  at com.sparrowwallet.sparrow@1.5.5/com.sparrowwallet.sparrow.transaction.HeadersController.finalizePSBT(Unknown Source)
  at com.sparrowwallet.sparrow@1.5.5/com.sparrowwallet.sparrow.transaction.HeadersController.openWallets(Unknown Source)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.base/java.lang.reflect.Method.invoke(Unknown Source)

**Comment by craigraw** [comment]
Thanks for the log - Sparrow will now show an error message when partial signatures do not match the wallet. 761ec06.
