### ISSUE TITLE
Error retreiving wallet history

### ISSUE THREAD

**Issue by NWHODL** [sparrowwallet/sparrow#525]
Hello, I'm out of my depth. I keep getting these errors using Sparrow wallet with an Umbrel node. 

2022-04-21 18:07:00,582 ERROR [JavaFX Application Thread] c.s.s.w.WalletForm [null:-1] Error retrieving wallet history
com.sparrowwallet.sparrow.net.ServerException: Failed to retrieve transaction history for paths: [m/0/0, m/0/2]
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.ElectrumServer.getReferences(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.ElectrumServer.getHistory(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.ElectrumServer.getHistory(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService.getTransactionHistory(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.PagedBatchRequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.PagedBatchRequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.BatchedElectrumServerRpc.getScriptHashHistory(Unknown Source)
	... 14 common frames omitted
Caused by: java.lang.IllegalStateException: Unspecified id: '394' in response
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.processSingleResponse(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.processBatchResponse(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.execute(Unknown Source)
	... 18 common frames omitted
2022-04-21 18:07:00,583 ERROR [JavaFX Application Thread] c.s.s.w.WalletForm [null:-1] Error retrieving wallet history
com.sparrowwallet.sparrow.net.ServerException: Failed to subscribe to paths: [m/0/0-m/0/26]
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.ElectrumServer.subscribeWalletNodes(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.ElectrumServer.getHistory(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.ElectrumServer.getHistory(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService.getTransactionHistory(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.ElectrumServer$TransactionHistoryService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.PagedBatchRequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.PagedBatchRequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.net.BatchedElectrumServerRpc.subscribeScriptHashes(Unknown Source)
	... 14 common frames omitted
Caused by: java.lang.IllegalStateException: Unspecified id: '372' in response
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.processSingleResponse(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.processBatchResponse(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.BatchRequestBuilder.execute(Unknown Source)
	... 18 common frames omitted

**Comment by NWHODL** [comment]
Manually refreshing the wallet resolved the issue.

**Comment by BonHodl** [comment]
I keep getting this constantly now. Need to refresh wallet atleast once a day and sometimes it still doesn't resolve.

**Comment by craigraw** [comment]
> I keep getting this constantly now. Need to refresh wallet atleast once a day and sometimes it still doesn't resolve.

This is entirely due to an issue with the server you are connecting to - Sparrow is just reporting that the server did not respond.
