### ISSUE TITLE
There was an error connecting sparrow to my Trezor wallet "Error parsing JSON"

### ISSUE THREAD

**Issue by medoyley** [sparrowwallet/sparrow#542]
I have installed the sparrow wallet version 1.6.3 and connected with the Bitcoin Core.  I have set up my Trezor wallet and everytime I try to create a new wallet with sparrow I get the message there was an error connecting to the wallet Error parsing JSON.  I thought this error was fixed in version 1.55.  Please advise.
Thanks

**Comment by craigraw** [comment]
Please look in the Sparrow log file (see Help menu) to find the full error, and paste it here. Please also supply your operating system, and at what point in the process you receive the error.

**Comment by medoyley** [comment]
Here are my sparrow logs from today's connecting error:
2022-05-11 13:04:17,718 ERROR [Thread-62] c.s.s.i
.Hwi [null:-1] Error parsing JSON: 
com.sparrowwallet.sparrow.io.ImportException: Error scanning, check devices are ready
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.io.Hwi.enumerate(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-05-11 18:30:25,069 ERROR [Thread-89] c.s.s.i.Hwi [null:-1] Error parsing JSON: 
com.sparrowwallet.sparrow.io.ImportException: Error scanning, check devices are ready
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.io.Hwi.enumerate(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.io.Hwi$EnumerateService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.io.Hwi$EnumerateService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
I am using an HP laptop running Windows 11 Home V210H2 OS Build 22000.675
The error occurs when I am in sparrow I have created a new wallet and I am pressing the Connected Hardware Wallet Button.  I then select Scan and while sparrow is scanning for the Trezor to connect I get the error message.  
Let me know if you have any questions
Thanks

**Comment by craigraw** [comment]
It might caused by an anti-virus blocking the HWI executable Sparrow is trying to run.

Here's something you can try - open your Sparrow `config` file from the Sparrow home folder (see the FAQ to find this). While Sparrow is running, look for an entry called `"hwi"`. Copy that path into your `cmd` command prompt and run it as follows: `c:\path\to\hwi enumerate`. Paste any output here.

**Comment by santochibtc** [comment]
Could be an issue with the HWI interface
[https://github.com/bitcoin-core/HWI/issues/613]
