### ISSUE TITLE
Received a POST request for /wallet/sparrow from x.x.x.x

### ISSUE THREAD

**Issue by valsha** [sparrowwallet/sparrow#566]
Good day
I am using Sparrow wallet connecting to my Bitcoin Core remote server
When I am trying to connect to my remote Bitcoin Core I can see in my logs (bitcoin core)
`Received a POST request for /wallet/sparrow from x.x.x.x`
In Sparrow wallet -
```
Could not connect:
Check if Bitcoin Core is running, and the authentication details are correct.
```

**Comment by craigraw** [comment]
Check the Sparrow log file (Help menu) for more information.

**Comment by valsha** [comment]
```
2022-05-23 16:46:03,279 ERROR [JavaFX Application Thread] c.s.s.n.ElectrumServer [null:-1] Failed to start BWT
dev.bwt.libbwt.BwtException: JSON-RPC error: RPC error response: RpcError { code: -32601, message: "Method not found", data: None }
  at com.sparrowwallet.merged.module@1.6.4/dev.bwt.libbwt.daemon.NativeBwtDaemon.start(Native Method)
  at com.sparrowwallet.sparrow@1.6.4/com.sparrowwallet.sparrow.net.Bwt.start(Unknown Source)
  at com.sparrowwallet.sparrow@1.6.4/com.sparrowwallet.sparrow.net.Bwt.start(Unknown Source)
  at com.sparrowwallet.sparrow@1.6.4/com.sparrowwallet.sparrow.net.Bwt$ConnectionService$1.call(Unknown Source)
  at com.sparrowwallet.sparrow@1.6.4/com.sparrowwallet.sparrow.net.Bwt$ConnectionService$1.call(Unknown Source)
  at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
  at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
  at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
  at java.base/java.security.AccessController.doPrivileged(Unknown Source)
  at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  at java.base/java.lang.Thread.run(Unknown Source)
2022-05-23 16:46:03,281 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
com.sparrowwallet.sparrow.net.ServerException: Check if Bitcoin Core is running, and the authentication details are correct.
  at com.sparrowwallet.sparrow@1.6.4/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
  at com.sparrowwallet.sparrow@1.6.4/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
  at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
  at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
  at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
  at java.base/java.security.AccessController.doPrivileged(Unknown Source)
  at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by craigraw** [comment]
Remove `disablewallet=1` from your Bitcoin Core config file.

**Comment by valsha** [comment]
> Remove `disablewallet=1` from your Bitcoin Core config file.

All is perfect now. Thank you for your support. Have a nice day.
