### ISSUE TITLE
Missing addresses

### ISSUE THREAD

**Issue by spar01** [sparrowwallet/sparrow#569]
I hadn't used sparrow wallet in a while (1-2 months), prior to that I had performed multiple transactions successfully.
Upon launching sparrow wallet today I can no longer see my existing addresses. I still see my old labels but they are now assigned to different addresses.
This was on 1.6.3, so I updated to 1.6.4 and still see the same problem.
I then tried to restore the wallet using my seed on a different computer but that yields the same result. I don't see the old addresses but rather new one's which were now showing up on my original computer.
Opening my backups also doesn't result in any different behavior unfortunately.

I do however see the following in the sparrow.log which doesn't show up in the prior history of that log file:
```
2022-05-24 17:16:28,165 ERROR [Thread-4] h2database [null:-1] main wallet:database flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: Store header is corrupt: /home/xxx/.sparrow/wallets/main wallet.mv.db [2.0.206/6]" [50000-206]
        at com.sparrowwallet.merged.module@1.6.3/org.h2.message.DbException.get(Unknown Source)
        at com.sparrowwallet.merged.module@1.6.3/org.h2.message.DbException.convert(Unknown Source)
        at com.sparrowwallet.merged.module@1.6.3/org.h2.mvstore.db.Store.lambda$new$0(Unknown Source)
        at com.sparrowwallet.merged.module@1.6.3/org.h2.mvstore.MVStore.handleException(Unknown Source)
        at com.sparrowwallet.merged.module@1.6.3/org.h2.mvstore.MVStore.panic(Unknown Source)
        at com.sparrowwallet.merged.module@1.6.3/org.h2.mvstore.MVStore.<init>(Unknown Source)
        at com.sparrowwallet.merged.module@1.6.3/org.h2.mvstore.MVStore$Builder.open(Unknown Source)
        at com.sparrowwallet.merged.module@1.6.3/org.h2.mvstore.db.Store.<init>(Unknown Source)
        at com.sparrowwallet.merged.module@1.6.3/org.h2.engine.Database.<init>(Unknown Source)
        at com.sparrowwallet.merged.module@1.6.3/org.h2.engine.Engine.openSession(Unknown Source)
        at com.sparrowwallet.merged.module@1.6.3/org.h2.engine.Engine.openSession(Unknown Source)
        at com.sparrowwallet.merged.module@1.6.3/org.h2.engine.Engine.createSession(Unknown Source)
        at com.sparrowwallet.merged.module@1.6.3/org.h2.engine.SessionRemote.connectEmbeddedOrServer(Unknown Source)
        at com.sparrowwallet.merged.module@1.6.3/org.h2.jdbc.JdbcConnection.<init>(Unknown Source)
        at com.sparrowwallet.merged.module@1.6.3/org.h2.Driver.connect(Unknown Source)
        at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.util.DriverDataSource.getConnection(Unknown Source)
        at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.PoolBase.newConnection(Unknown Source)
        at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.PoolBase.newPoolEntry(Unknown Source)
        at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.HikariPool.createPoolEntry(Unknown Source)
        at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.HikariPool.checkFailFast(Unknown Source)
        at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.HikariPool.<init>(Unknown Source)
        at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.HikariDataSource.<init>(Unknown Source)
        at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.io.db.DbPersistence.createDataSource(Unknown Source)
        at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.io.db.DbPersistence.getDataSource(Unknown Source)
        at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.io.db.DbPersistence.getFlyway(Unknown Source)
        at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.io.db.DbPersistence.migrate(Unknown Source)
        at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.io.db.DbPersistence.loadWallet(Unknown Source)
        at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.io.db.DbPersistence.loadWallet(Unknown Source)
        at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.io.Storage.loadEncryptedWallet(Unknown Source)
        at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.io.Storage$LoadWalletService$1.call(Unknown Source)
        at com.sparrowwallet.sparrow@1.6.3/com.sparrowwallet.sparrow.io.Storage$LoadWalletService$1.call(Unknown Source)
        at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

```

OS: Linux

**Comment by craigraw** [comment]
This is almost certainly due to an incorrect passphrase. Sparrow stores nothing in the wallet that relates to the passphrase, so a different passphrase will generate new addresses that have the old labels applied to them. This is by design of BIP39 passphrases.

**Comment by spar01** [comment]
You were spot on, I have a typo in my passphrase. :(
Closing
