### ISSUE TITLE
App hangs with Concurrent Connect Timeout

### ISSUE THREAD

**Issue by 4NobleTruths** [sparrowwallet/sparrow#574]
On Debian 10.
while mixing, sparrow stopped responding with about 45% memory, but almost no CPU use.
Only signal 9 could kill it.

tail of it was:

> nested exception is java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Concurrent Connect Timeout
	at com.sparrowwallet.merged.module@1.6.4/org.springframework.web.socket.sockjs.client.JettyXhrTransport.executeRequest(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.4/org.springframework.web.socket.sockjs.client.JettyXhrTransport.executeInfoRequestInternal(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.4/org.springframework.web.socket.sockjs.client.AbstractXhrTransport.executeInfoRequest(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.4/org.springframework.web.socket.sockjs.client.SockJsClient.getServerInfo(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.4/org.springframework.web.socket.sockjs.client.SockJsClient.doHandshake(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.4/org.springframework.web.socket.messaging.WebSocketStompClient.connect(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.4/org.springframework.web.socket.messaging.WebSocketStompClient.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.sparrowwallet.nightjar.stomp.JavaStompClient.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.stomp.client.StompTransport.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.mix.dialog.MixSession.connect(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.mix.dialog.MixSession$3$1.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Concurrent Connect Timeout
	at com.sparrowwallet.merged.module@1.6.4/org.eclipse.jetty.client.util.FutureResponseListener.getResult(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.4/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.4/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	... 12 common frames omitted
Caused by: java.net.SocketTimeoutException: Concurrent Connect Timeout
	at com.sparrowwallet.merged.module@1.6.4/org.eclipse.jetty.io.ManagedSelector.processConnect(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.4/org.eclipse.jetty.io.ManagedSelector.access$1500(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.4/org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.4/org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.4/org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.4/org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.4/org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.4/org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.4/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.4/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(Unknown Source)
	... 1 common frames omitted

**Comment by craigraw** [comment]
It's possible that the connect timeout exception was unrelated. Difficult to be sure of what caused this. Try issuing a `kill -3` if it occurs again - it will probably fail, but under normal circumstances a thread dump is printed to the log.

**Comment by 4NobleTruths** [comment]
Thanks. It happened again today. Had to restart the machine for it to work right again.

**Comment by 4NobleTruths** [comment]
kill -s 3 doesn't give any extra log output in this case.

**Comment by craigraw** [comment]
This behaviour is certainly unusual, and there's nothing I can think of that would block certain connections after a `kill` command was issued on a previous instance. I've reviewed the other two issues you opened and it seems possible that there may be some relation to this behaviour when running in a Qubes VM (if that is a common factor here?).

**Comment by 4NobleTruths** [comment]
Yes, possible. Qubes VM is a monstrosity similar to JVM, with main problem also being that it consumes so much memory. A 32GB RAM machine is the practical minimum, if one will try to run Java apps that consume several GBs each. 
Tor is next usual suspect.
The Bitcoin nodes and all the docker mess in most of them is another - with layers of failure points.
My biggest wish is that no more Java or docker based apps are created. In my experience, those are champions of consuming the most resources, while creating the most obscure, complicated and incurable problems.
