### ISSUE TITLE
Sparrow not updating and no sign of connection error.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#580]
I have few transaction that are waiting to be confirmed on sparrow but have multiple confirmation in reality.

The logs don't seems to show any recent connection attempt + error.

2022-05-30 21:23:40,331 WARN [Thread-1886] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 34 secs
2022-05-31 07:03:06,918 WARN [Thread-2582] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 34 secs
2022-05-31 07:03:42,461 WARN [Thread-2582] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 34 secs

Time is currently 13:23

**Comment by Transisto** [comment]
Clicked the connection toggle twice to try reconnecting, This is what the logs showed.

...
2022-05-31 07:03:42,461 WARN [Thread-2582] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 34 secs
2022-05-31 13:23:29,978 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-05-31 13:23:29,989 WARN [JavaFX Application Thread] c.s.s.t.TransactionController [null:-1] Failed to retrieve all referenced input transactions, aborting transaction fetch

**Comment by craigraw** [comment]
Looks like the socket from the server remained open (from the client context, anyway), but was not sending data (or at least, enough data to complete a request). 

That's my best guess, anyway - further investigation on the state of the socket connection (for example, with `netstat`) would be necessary to understand better what is going on. It would also have been helpful to see what the current thread dump looked like for Sparrow when this occurred. This can be obtained by issuing a `kill -3 <PID>` on Sparrow's process id in *nix type systems.

**Comment by craigraw** [comment]
Thinking about this more, the most likely reason is that the server simply failed to notify Sparrow that the transactions had been confirmed (even while keeping the connection open). This is not unusual for Electrs-based implementations, but could also be due to simple connection errors (less likely).

I don't think it's a Sparrow bug however.

**Comment by Transisto** [comment]
"I don't think it's a Sparrow bug however."

If it's not sparrow related is it caused by the underlying JVM?

**Comment by craigraw** [comment]
> If it's not sparrow related is it caused by the underlying JVM?

No, it's caused by the server.
