### ISSUE TITLE
1.6.5 Sparrow seems to be connecting to another electrum server?

### ISSUE THREAD

**Issue by iliaster94** [sparrowwallet/sparrow#588]
I connect to my own electrs instance via tor. The settings are correct in Preferences so I'm curious what this is then...

```2022-06-05 12:58:38,361 ERROR [JavaFX Application Thread] c.s.s.t.HeadersController [null:-1] Error broadcasting transaction
com.sparrowwallet.sparrow.net.ServerException: min relay fee not met, 528 < 529
        at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.net.ElectrumServer.broadcastTransaction(Unknown Source)
        at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.net.ElectrumServer.broadcastTransactionPrivately(Unknown Source)
        at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.net.ElectrumServer$BroadcastTransactionService$1.call(Unknown Source)
        at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.net.ElectrumServer$BroadcastTransactionService$1.call(Unknown Source)
        at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ElectrumServerRpcException: min relay fee not met, 528 < 529
        at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.net.BatchedElectrumServerRpc.broadcastTransaction(Unknown Source)
        ... 12 common frames omitted
Caused by: com.github.arteam.simplejsonrpc.client.exception.JsonRpcException: ErrorMessage{code=2, message=min relay fee not met, 528 < 529}
        at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeAndConvert(Unknown Source)
        at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.execute(Unknown Source)
        at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.net.BatchedElectrumServerRpc.lambda$broadcastTransaction$7(Unknown Source)
        at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
        ... 13 common frames omitted
```
I don't remember ever reading anything about a "min relay fee" and I don't understand why that would apply to me when I'm using my own node.

**Comment by craigraw** [comment]
You are connected to your node - it would not be possible to get a response like this from it if you were not.

All Bitcoin Core nodes have a minimum relay fee. What is probably happening here is that one of the signers of the transaction you are attempting to broadcast has created a non-canonical signature, meaning the transaction is slightly larger than what Sparrow was expecting. To fix this, simply increase the fee rate slightly to just over 1 sat/vB.
