### ISSUE TITLE
Help With Webcam

### ISSUE THREAD

**Issue by me269** [sparrowwallet/sparrow#627]
When trying to scan something I get a webcam error related to some java app. 
Running latest release in LINUX Lite
Heres the log file:

2022-07-15 23:47:44,514 ERROR [JavaFX Application Thread] c.s.s.c.WebcamView [null:-1] Failed to start web cam
com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.Webcam.getWebcams(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.control.WebcamService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.control.WebcamService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	... 12 common frames omitted
Caused by: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamProcessor.process(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamTask.process(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.newGrabber(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver.getDevices(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.control.WebcamScanDriver.getDevices(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	... 3 common frames omitted
Caused by: java.lang.RuntimeException: Failed to allocate new instance of type class com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.cpp.CPPRuntime.newCPPInstance(Unknown Source)
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(Unknown Source)
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(Unknown Source)
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.CRuntime$CTypeInfo.initialize(Unknown Source)
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.BridJ.initialize(Unknown Source)
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.NativeObject.<init>(Unknown Source)
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.StructObject.<init>(Unknown Source)
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.cpp.CPPObject.<init>(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<init>(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(Unknown Source)
	... 3 common frames omitted
Caused by: java.lang.RuntimeException: Library 'OpenIMAJGrabber' was not loaded successfully from file '/tmp/BridJExtractedLibraries4276187744066580300/OpenIMAJGrabber.so'
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.BridJ.getNativeLibrary(Unknown Source)
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.BridJ.getNativeLibrary(Unknown Source)
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.BridJ.getNativeLibrary(Unknown Source)
	... 14 common frames omitted
2022-07-15 23:47:44,544 ERROR [JavaFX Application Thread] c.s.s.c.FileImportPane [null:-1] Error importing QR
com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.Webcam.getWebcams(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.control.WebcamService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.control.WebcamService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	... 12 common frames omitted
Caused by: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamProcessor.process(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamTask.process(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.newGrabber(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver.getDevices(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.5/com.sparrowwallet.sparrow.control.WebcamScanDriver.getDevices(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	... 3 common frames omitted
Caused by: java.lang.RuntimeException: Failed to allocate new instance of type class com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.cpp.CPPRuntime.newCPPInstance(Unknown Source)
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(Unknown Source)
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(Unknown Source)
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.CRuntime$CTypeInfo.initialize(Unknown Source)
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.BridJ.initialize(Unknown Source)
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.NativeObject.<init>(Unknown Source)
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.StructObject.<init>(Unknown Source)
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.cpp.CPPObject.<init>(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<init>(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(Unknown Source)
	at com.github.sarxos.webcam.capture@0.3.13-SNAPSHOT/com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(Unknown Source)
	... 3 common frames omitted
Caused by: java.lang.RuntimeException: Library 'OpenIMAJGrabber' was not loaded successfully from file '/tmp/BridJExtractedLibraries4276187744066580300/OpenIMAJGrabber.so'
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.BridJ.getNativeLibrary(Unknown Source)
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.BridJ.getNativeLibrary(Unknown Source)
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.BridJ.getNativeLibrary(Unknown Source)
	... 14 common frames omitted

**Comment by craigraw** [comment]
Can you provide more details on your system? It appears that it cannot load the webcam library `OpenIMAJGrabber.so`.

You can try using `ldd` on this file to find out more.

**Comment by me269** [comment]
(Sorry, slowly migrating from windows system.)

uname -a
Linux linuxlite-VJF155F11X-B0311B 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

java --version
openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)

ldd OpenIMAJGrabber.so 
	linux-vdso.so.1 (0x00007ffc543e9000)
	libv4l2.so.0 => not found
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f83ecbb5000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f83ecb9a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f83ec9a8000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f83ec859000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f83ecfb5000)

The only place I found the OpenIMAJGrabber.so file was on the tmp folder after sparrow failed to open the camera.

And thank you for replying. Spent couple hours trying to figure out by my own what is wrong but couldn't fix the issue.

**Comment by craigraw** [comment]
Great! Thanks for reporting back.
