### ISSUE TITLE
[BUG] Sparrow tries to constantly start whirlpool while being disconnected from network

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#656]
Running sparrow with head on  commit f1a662ba8a39963d6b04b07fbb991f2bea23f024

Going through the logs I just discovered that sparrow tries to start whirlpool while being disconnected (by manually switching the network toggle off).
```
<DATE TIME> ERROR [JavaFX Application Thread] c.s.s.w.WhirlpoolServices [null:-1] Failed to start Whirlpool
com.sparrowwallet.sparrow.whirlpool.WhirlpoolException: Could not create whirlpool wallet 
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.whirlpool.Whirlpool.getWhirlpoolWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.samourai.wallet.api.backend.beans.HttpException: java.util.concurrent.ExecutionException: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.whirlpool.ServerApi.fetchPools(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier$1.getOrThrow(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.open(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.whirlpool.dataSource.SparrowDataSource.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.wallet.WhirlpoolWallet.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.wallet.WhirlpoolWalletService.openWallet(Unknown Source)
	... 11 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.merged.module@1.6.6/org.eclipse.jetty.client.util.FutureResponseListener.getResult(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.6/org.eclipse.jetty.client.util.FutureResponseListener.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.6/org.eclipse.jetty.client.HttpRequest.send(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.sparrowwallet.nightjar.http.JavaHttpClient.requestJsonGet(Unknown Source)
	... 26 common frames omitted
Caused by: java.io.IOException: SOCKS4 tunnel failed with code 91
	at com.sparrowwallet.merged.module@1.6.6/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.onSocks4Response(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.6/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.access$300(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.6/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection$Socks4Parser.parse(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.6/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection$Socks4Parser.access$200(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.6/org.eclipse.jetty.client.Socks4Proxy$Socks4ProxyConnection.onFillable(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.6/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.6/org.eclipse.jetty.io.FillInterest.fillable(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.6/org.eclipse.jetty.io.ChannelEndPoint$2.run(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.6/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.6/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(Unknown Source)
	... 1 common frames omitted

``` 

```
<DATE TIME> ERROR [Thread-449] c.s.w.c.w.d.p.ExpirablePoolSupplier [null:-1] load() failure
com.samourai.wallet.api.backend.beans.HttpException: java.util.concurrent.TimeoutException: Total timeout 30000 ms elapsed
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.http.client.JacksonHttpClient.getJson(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.whirlpool.ServerApi.fetchPools(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.wallet.data.pool.ExpirablePoolSupplier.fetch(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier$1.getOrThrow(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.zeroleak.throwingsupplier.ThrowingSupplier.get(Unknown Source)
	at com.google.common@28.2-jre/com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.wallet.data.supplier.ExpirableSupplier.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.load(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.wallet.data.dataSource.WalletResponseDataSource.open(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.whirlpool.dataSource.SparrowDataSource.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.wallet.WhirlpoolWallet.open(Unknown Source)
	at com.sparrowwallet.nightjar@0.2.33/com.samourai.whirlpool.client.wallet.WhirlpoolWalletService.openWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.whirlpool.Whirlpool.getWhirlpoolWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.whirlpool.Whirlpool$StartupService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.TimeoutException: Total timeout 30000 ms elapsed
	at com.sparrowwallet.merged.module@1.6.6/org.eclipse.jetty.client.HttpDestination$TimeoutTask.onTimeoutExpired(Unknown Source)
	at com.sparrowwallet.merged.module@1.6.6/org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	... 3 common frames omitted
```
```
<DATE TIME> ERROR [JavaFX Application Thread] c.s.s.w.WhirlpoolServices [null:-1] Error connecting to Whirlpool server: Total timeout 30000 ms elapsed
```

I'm not sure this makes a lot of sense since network access has been actively turned down?!

**Comment by craigraw** [comment]
Thanks for the bug report. Although Sparrow won't start Whirlpool (actually mixing) when offline, if there was a previous unsuccessful attempt to setup the wallet for mixing, Sparrow would continue to try this setup attempt even when offline.

This has been fixed in 5aea538f.
