### ISSUE TITLE
Can't Connect to external Electrum server (electrs) on Whonix

### ISSUE THREAD

**Issue by gabrielseibel1** [sparrowwallet/sparrow#673]
Hi. I'm trying to connect a sparrow wallet, **running on whonix**, to a tor hidden service of an electrum server of mine (running electrs on another machine). Connection works fine for Electrum on Whonix, but sparrow fails to connect. 

The tor part seems to be the problem. Does sparrow run an internal tor client? It seems to try to connect to my hidden service starting a tor instance, but then fails because it's running on whonix and the 9050 port is busy (I've read this on the connection-test log). 

```
Starting Tor
Aug 26 14:46:16.974 [notice] Tor 0.4.3.6 (git-30711296fd5b7f51) running on Linux with Libevent 2.1.11-stable, OpenSSL 1.1.1g, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Aug 26 14:46:16.974 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Aug 26 14:46:16.974 [notice] Read configuration file "/tmp/tor10679590390238463793/torrc".
Aug 26 14:46:16.976 [notice] Opening Control listener on 127.0.0.1:0
Aug 26 14:46:16.976 [notice] Control listener listening on port 33409.
Aug 26 14:46:16.977 [notice] Opened Control listener on 127.0.0.1:33409
Aug 26 14:46:16.983 [notice] DisableNetwork is set. Tor will not make or accept non-control network connections. Shutting down all existing connections.
```

Then it suggests that I configure the proxy:
```
Could not connect:

Error reply: Unable to set option: Failed to bind one of the listener ports.
Is a Tor proxy already running on port 9050?

Assuming Tor proxy is running on port 9050 and trying again...
```

I've tried using localhost:9050 and also 10.152.152.10:9111 (following https://www.whonix.org/wiki/Electrum).
The result is that it exhausts the max retries to connect.

My electrum server doesn't log anything so it seems that messages are not reaching it.

Here is some of the log file of the wallet:

```
2022-08-26 14:46:18,263 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
com.sparrowwallet.sparrow.net.TorServerAlreadyBoundException: Tor server already bound
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.net.TorService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.net.TorService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: net.freehaven.tor.control.TorControlError: Error reply: Unable to set option: Failed to bind one of the listener ports.
	at com.github.JesusMcCloud.jtorctl@1.5/net.freehaven.tor.control.TorControlConnection.sendAndWaitForResponse(Unknown Source)
	at com.github.JesusMcCloud.jtorctl@1.5/net.freehaven.tor.control.TorControlConnection.setConf(Unknown Source)
	at com.github.JesusMcCloud.jtorctl@1.5/net.freehaven.tor.control.TorControlConnection.setConf(Unknown Source)
	at netlayer.jpms@0.6.8/org.berndpruenster.netlayer.tor.TorController.enableNetwork(Unknown Source)
	at netlayer.jpms@0.6.8/org.berndpruenster.netlayer.tor.NativeTor.<init>(Unknown Source)
	at netlayer.jpms@0.6.8/org.berndpruenster.netlayer.tor.NativeTor.<init>(Unknown Source)
	at netlayer.jpms@0.6.8/org.berndpruenster.netlayer.tor.NativeTor.<init>(Unknown Source)
	... 10 common frames omitted
2022-08-26 14:46:21,495 WARN [Thread-229] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 8 secs
2022-08-26 14:46:29,965 WARN [Thread-229] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 16 secs
2022-08-26 14:46:47,883 WARN [Thread-229] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 34 secs
2022-08-26 14:50:32,003 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-08-26 14:50:32,005 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-08-26 14:55:07,859 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-08-26 14:55:11,811 ERROR [JavaFX Application Thread] c.s.s.w.WalletForm [null:-1] Could not determine payment codes for wallet user
com.sparrowwallet.sparrow.net.ServerException: Failed to subscribe to path: m/0
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.net.ElectrumServer.subscribeWalletNodes(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.net.ElectrumServer.getHistory(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.net.ElectrumServer$PaymentCodesService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.net.ElectrumServer$PaymentCodesService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.subscribeScriptHashes(Unknown Source)
	... 12 common frames omitted
Caused by: java.lang.IllegalStateException: I/O error during a request processing
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeRequest(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeAndConvert(Unknown Source)
	at simple.json.rpc.client@1.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeNullable(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.lambda$subscribeScriptHashes$6(Unknown Source)
	... 14 common frames omitted
Caused by: java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getOutputStream(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.net.TcpTransport.writeRequest(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.net.TcpTransport.pass(Unknown Source)
	... 18 common frames omitted
```

**Comment by gabrielseibel1** [comment]
Also, wallet icon is red, and Transactions tab shows
```
Wallet loading history for user
[Aug 26 14:55:13] Failed to subscribe to path: ../0/0
```

**Comment by nyxnor** [comment]
> Aug 26 14:46:16.983 [notice] DisableNetwork is set. Tor will not make or accept non-control network connections. Shutting down all existing connections.

Set `DisableNetwork 0` on the tor conf.

**Comment by nyxnor** [comment]
> Aug 26 14:46:16.974 [notice] Tor 0.4.3.6 (git-30711296fd5b7f51) running on Linux with Libevent 2.1.11-stable, OpenSSL 1.1.1g, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.


Also outdated version, you built from source as I can see the git mention, but the newest tor version is `0.4.7.8`

**Comment by nyxnor** [comment]
> running on whonix,

Qubes-Whonix or Non-Qubes-Whonix?

If using Qubes-Whonix, set the socks host to the output of the command run on the Workstation:
`qubesdb-read /qubes-gateway`, it will show the Gateway IP.

**Comment by gabrielseibel1** [comment]
Hi. 

Thanks for the quick replies.

I'm using whonix on kvm over pop!_os (not on qubes).

I didn't build Tor, Whonix nor Sparrow from source. The Tor log I pasted was from inside the connection test screen from sparrow, which makes me wonder if it's trying to start a bundled Tor client (is this assumption correct?). If that is the case, should I maybe disable that to avoid tor-over-tor on whonix? How would I do that?

Regarding 
> Set DisableNetwork 0 on the tor conf.
How would I do that? Do you mean the tor settings for the whole whonix system? Connections are all-around working fine i.e. browsing and Electrum work.

Thanks for the help up to this point.

**Comment by nyxnor** [comment]
> The Tor log I pasted was from inside the connection test screen from sparrow, which makes me wonder if it's trying to start a bundled Tor client (is this assumption correct?).

Yes, but I didn't have this problem, I wonder why.

>  If that is the case, should I maybe disable that to avoid tor-over-tor on whonix? How would I do that?

Don't know. let's try again the steps.

- Try connecting to your electrum server via the whonix workstation using electrum wallet
- Try connecting to your electrum server via the whonix workstation using sparrow wallet
  - set the private server onion address, proxy host 10.152.152.10, proxy port 9111
  - test connection

Maybe show screenshot of your sparrow server configuration, just hide the onion address if you want.

Don't start sparrow with torsocks or uwt.

Se precisar que eu explique em portugues, eu explico.

**Comment by nyxnor** [comment]
I see the problem, sparrow tries to create a tor instance when connecting to an onion domain if you don't set a proxy url.

Proxy URL host: 10.152.152.10
Proxy URL port: 9111

**Comment by craigraw** [comment]
> sparrow tries to create a tor instance when connecting to an onion domain if you don't set a proxy url.

Correct

> I've tried using localhost:9050 and also 10.152.152.10:9111 

You've already tried setting the proxy to 10.152.152.10:9111?

**Comment by gabrielseibel1** [comment]
Hi. I have a few screenshots to share, but if you'd be interested I've also filmed the whole test.

Here is Electrum with no proxy set (transparent proxyng by whonix)
![electrum_no_proxy](https://user-images.githubusercontent.com/23637113/187276351-31e8f098-e74c-429a-a983-d8e9ad349a37.png)

Now Electrum with proxy set to localhost:9050
![electrum_proxy_9050](https://user-images.githubusercontent.com/23637113/187276482-123f4339-54e7-4f04-870d-aaeba5175368.png)

Then 10.152.152.10:9111 ...
![electrum_proxy_9111](https://user-images.githubusercontent.com/23637113/187276531-1592a674-05cb-4e40-beab-9356a899153d.png)

Now for sparrow:

Connection test errors for transparent proxy (no proxy set) and hangs for 9050 or 9111 

![Screenshot from simple_aac_recording](https://user-images.githubusercontent.com/23637113/187277489-9bb3f26b-a0bf-41d5-bb75-a8569e4b7154.png)
![Screenshot from simple_aac_recording - 1](https://user-images.githubusercontent.com/23637113/187277508-d86d0097-de16-4188-9068-7318528acabd.png)
![Screenshot from simple_aac_recording - 2](https://user-images.githubusercontent.com/23637113/187277519-c3d675f3-82d3-41f4-8bc7-70bf6854947c.png)
![Screenshot from simple_aac_recording - 3](https://user-images.githubusercontent.com/23637113/187277537-526fcb06-7e36-4330-aba6-0a59c8ad7e07.png)
![Screenshot from simple_aac_recording - 4](https://user-images.githubusercontent.com/23637113/187277562-393636a9-55fd-4bd7-b9f5-6c02601f095e.png)
![Screenshot from simple_aac_recording - 5](https://user-images.githubusercontent.com/23637113/187277546-86ab4d18-6865-4175-8ec0-e96c1f2249c0.png)

**Comment by gabrielseibel1** [comment]
>You've already tried setting the proxy to 10.152.152.10:9111?

Yes. It works in Electrum after some wait time (a minute or so) but hangs on Sparrow (waited several minutes)

**Comment by nyxnor** [comment]
Remove the `Use SSL` option and use the port `50001` instead of `50001`
It is not required for onions and has a rare use case.

If you really want to use SSL, you have to provide a certificate because onion certificates are rarely authenticated by a CA. So you need to download the certificate and indicate that to sparrow on the `Certificate` field.

But else, just do the first paragraph, it is simpler and doesn't compromise security if not using SSL, as onion services are end-to-end encrypted.

**Comment by gabrielseibel1** [comment]
Thanks for the suggestion.

I am trying to connect using this method (no SSL) but am still facing problems.

For no proxy specified, I get the same message that tor was not able to start.

Then for localhost:9050 proxy I got this:

(yes I changed the onion address, also validated this new one with Electrum)

![sparrow_error_con](https://user-images.githubusercontent.com/23637113/187305283-61806edc-7ef7-43d8-8c30-9b6f42344823.png)

Tried again and also for 10.152.152.10:9111 but it just hangs indefinitely :(

Any other suggestions?

**Comment by nyxnor** [comment]
> Tried again and also for 10.152.152.10:9111 but it just hangs indefinitely :(

Indefinitely means how much time in minutes?

You can watch tor controller stream on whonix with`tor-ctrl-stream` command. Check to see if any connections are made to that onion domain.

Hanging for me means:
- the socket exist because the connection wasn't closed
- it didn't load yet

SocksPort 10.152.152.10:9111 is for stream isolation and should have worked.
Try Proxy URL: `10.152.152.10` `9050`

It won't have stream isolation, but let's see if it connects.

**Comment by nyxnor** [comment]
Also, instead of your onion domain, set the server to `electrum.emzy.de` and port `50002` for example, and use the proxy url `10.152.152.10` `9111`

**Comment by gabrielseibel1** [comment]
`tor-ctrl-stream` did not produce any output (aside from general info and warn previous to my test) while sparrow was trying to connect.

BUT:

Now I waited 4 minutes for 10.152.152.10 and got this:

![Screenshot from 2022-08-29 19-34-12](https://user-images.githubusercontent.com/23637113/187310610-239b828a-23aa-48e3-ab43-d92804a142f9.png)

Looks like it worked! There is an error in the connection test, but after it appeared the wallet synched...

Should I worry about the error?

Thanks a lot and feel free to close the issue if that error is irrelevant :)

**Comment by nyxnor** [comment]
> tor-ctrl-stream did not produce any output (aside from general info and warn previous to my test) while sparrow was trying to connect.

tor-ctrl-stream should be run before testing the connection.

> Should I worry about the error?

Don't know, will leave this to Craig, but you should search the sparrow issues and electrum github issues about that problem.

**Comment by craigraw** [comment]
Looks like the wallet loaded successfully - the error you got was temporary in nature and probably Tor related. Certainly the connection to your Electrum is now configured correctly. Closing this off.

**Comment by leonarzoh** [comment]
Im having the same issues reported by @gabrielseibel1 above. I also tried 10.152.152.10:9111 or 10.152.152.10:9050 with no success. I used to use 127.0.0.1:9050 for a while, but then I had to change the server (Fulcrum?), and now I can't connect over Tor. No outputs for `tor-ctrl-stream` By the way, my setup is VirtualBox + Whonix Gateway/Workstation + Sparrow 1.6.6 + external electrum server. Feather Wallet (Monero) + external node over Tor works fine.

**Comment by nyxnor** [comment]
I don't know why this happens on Non-Qubes-Whonix.
Try https://forums.whonix.org but not 100% sure Patrick will reply because Sparrow is not integrated.

@leonarzoh  try:
```sh
curl.anondist-orig -x socks5h://10.152.152.10:9111 https://check.torproject.org/api/ip
```

**Comment by leonarzoh** [comment]
> ```shell
> curl.anondist-orig -x socks5h://10.152.152.10:9111 \
> https://check.torproject.org/api/ip
> ```

@nyxnor  here we go
 {"IsTor":true,"IP":"5.255.96.245"}

**Comment by nyxnor** [comment]
`{"IsTor":true,`

So the socks proxy is working. It should also work for Sparrow.

**Comment by gabrielseibel1** [comment]
> Im having the same issues reported by @gabrielseibel1 above. I also tried 10.152.152.10:9111 or 10.152.152.10:9050 with no success. I used to use 127.0.0.1:9050 for a while, but then I had to change the server (Fulcrum?), and now I can't connect over Tor. No outputs for `tor-ctrl-stream` By the way, my setup is VirtualBox + Whonix Gateway/Workstation + Sparrow 1.6.6 + external electrum server. Feather Wallet (Monero) + external node over Tor works fine.

Have you tried waiting 5+ minutes? Took a little longer than Electrum did, on my Whonix VM, to synch to the server.
