### ISSUE TITLE
Error when sign transaction with Ledger Nano - Signing Error: -12186

### ISSUE THREAD

**Issue by abradshaw** [sparrowwallet/sparrow#677]
I was having problems sending a transaction with LedgerLive, so I connected the Ledger to a new Wallet in Sparrow and attempted the same transaction - I got this error

~~~
2022-09-01 14:34:06,628 ERROR Signing Error: -12186
java.lang.NegativeArraySizeException: -12186
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTEntry.<init>(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.parse(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.<init>(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.fromString(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.fromString(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.io.Hwi.signPSBT(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.6/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
~~~

I tried again with a smaller amount/fewer UTXOs and it worked

Sparrow Version: 1.6.6 (on Fedora Linux)

**Comment by abradshaw** [comment]
Hmm Its a Ledger Nano X. The device does take a long to "processing" (being sent the info from the computer) before displaying the transaction on its screen, then it lets you examine it and Accept it. Once Accepted it again spends a long time "processing" (as in sending back the computer) and its at this point it fails. So yeah I guess it makes sense, just a little disappointing considering it (Ledger Nano X) has a great reputation. So you think its to do with the number of UTXOs?

I can try and reproduce on Testnet

**Comment by abradshaw** [comment]
(I should say I was unable to do anything with the LedgerLive - only Sparrow let me actually send a transaction, once I had halved the tx size - so Sparrow 1, Ledger Live 0  )

**Comment by craigraw** [comment]
Unfortunately it's a known problem, even with a Nano X: 
* https://www.reddit.com/r/ledgerwallet/comments/rs238j/slow_ledger_signing/
* https://support.ledger.com/hc/en-us/articles/360018969814-Receive-mining-proceeds?docs=true

**Comment by abradshaw** [comment]
Just out of interest do the Keystone devices also suffer from this? (I have been interested in these for a while)

**Comment by craigraw** [comment]
Keystone devices shouldn't have the same restrictions afaik - they use much more capable hardware. Passport and Coldcard mk4 are good alternatives too.
