### ISSUE TITLE
Sparrow will no longer connect to bitcoin core

### ISSUE THREAD

**Issue by xserver1992** [sparrowwallet/sparrow#724]
Sparrow suddenly won't connect to the bitcoin core even though it was previously working.  I have not changed any of the configuration.  Note that it won't connect locally on the bitcoin core machine either (again, used to work).
Here is the error that appears on the test connection screen:

_Could not connect:_
_Check if Bitcoin Core is running, and the authentication details are correct._
_See https://sparrowwallet.com/docs/connect-node.html_

Here is the error log:
2022-10-28 10:55:28,139 ERROR [JavaFX Application Thread] c.s.s.n.ElectrumServer [null:-1] Failed to start BWT
dev.bwt.libbwt.BwtException: JSON-RPC error: JSON decode error: missing field `keypoololdest` at line 1 column 334
	at com.sparrowwallet.merged.module@1.7.0/dev.bwt.libbwt.daemon.NativeBwtDaemon.start(Native Method)
	at com.sparrowwallet.sparrow@1.7.0/com.sparrowwallet.sparrow.net.Bwt.start(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.0/com.sparrowwallet.sparrow.net.Bwt.start(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.0/com.sparrowwallet.sparrow.net.Bwt$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.0/com.sparrowwallet.sparrow.net.Bwt$ConnectionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-10-28 10:55:28,140 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
com.sparrowwallet.sparrow.net.ServerException: Check if Bitcoin Core is running, and the authentication details are correct.
	at com.sparrowwallet.sparrow@1.7.0/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.0/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

The authentication information **_is_** correct in the bitcoin core configuration file (like I said, used to work).

It seems to halfway work as the following screen appears on the bitcoin core:
![BitcoinCore](https://user-images.githubusercontent.com/116910438/198700668-fd894033-40fe-4193-8079-fda8cbc14682.PNG)

I have Windows 10 on both machines, Sparrow v1.7.0 and bitcoin core v23.0.

java version "1.8.0_351"
Java(TM) SE Runtime Environment (build 1.8.0_351-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.351-b10, mixed mode)

Any suggestions appreciated.

**Comment by lvnilesh** [comment]
Are you able to successfully connect to your node via the command line?
```
bitcoin-cli -rpcconnect=<ip addr> -rpcport=8332 -rpcuser=<user_name> -rpcpassword=<password> -getinfo
```

**Comment by xserver1992** [comment]
It appears so, here is the output:

```
Chain: main
Blocks: 760699
Headers: 760699
Verification progress: 99.9999%
Difficulty: 36835682546787.98

Network: in 0, out 10, total 10
Version: 230000
Time offset (s): 0
Proxies: n/a
Min tx relay fee rate (BTC/kvB): 0.00001000

Wallet: sparrow
Keypool size: 0
Transaction fee rate (-paytxfee) (BTC/kvB): 0.00000000

Balance: 0.00000000

Warnings:
```

**Comment by craigraw** [comment]
This is due to Bitcoin Core changing the default wallet type to descriptor wallets. See #488.

To solve this, start by upgrading Sparrow to the latest release. Shut down both Bitcoin Core and Sparrow, delete the `sparrow` folder in the Bitcoin Core wallets folder, restart Bitcoin Core and then Sparrow. This will recreate the sparrow wallet in Bitcoin Core using the correct type.

**Comment by xserver1992** [comment]
That fixed it, thank you.

**Comment by ExchangeREC** [comment]
I got the **exact same issue like OP but** I already use Sparrow Wallet **1.7.1** (Linux) and Bitcoin Core 23.0.0 (Windows) when trying to connect. 
The workaround of **deleting the "sparrow" folder** in the Bitcoin Core directory **works only once** when I work in the following order:
1. Close Bitcoin Core
2. Close Sparrow Wallet
3. Delete "sparrow" folder in the Bitcoin Core directory
4. Start Bitcoin Core 
5. Start Sparrow Wallet

Then it works, **but**: Only until I shut down Bitcoin Core and restart it. Then I have to follow steps 1-5 again.
Notice: I have not connected/created/imported any wallet on Sparrow yet but my Bitcoin Core application looks like the screenshot from OP anyways. 

I really appreciate any help!

**Comment by xserver1992** [comment]
I can only tell you that mine still works even if restart the Bitcoin Core.  I can only suggest trying to delete the files in Sparrow's folder.  Even though you haven't created a wallet perhaps there is something there anyways?  Otherwise I don't know.

**Comment by xserver1992** [comment]
I hope I'm not belaboring the point, but I was referring to **Sparrow's** working folders on your Linux machine not the Bitcoin core's Sparrow folder mentioned in your post.  Might not work, but worth a try perhaps if you haven't already.  Sorry if this was not clear.

**Comment by craigraw** [comment]
@ExchangeREC take a look at #770 - it might be related. Are you getting any errors in your Sparrow log? (Help menu)

**Comment by ExchangeREC** [comment]
@xserver1992 ah sorry mate, I misunderstood you! Thanks for the suggestion but within the "wallets" folder on Linux, there is nothing inside (I did "ls -la" in the command line) ..

@craigraw thanks! The problem is similar but the only solution working for me right now is: 
- close Bitcoin Core
- close Samourai Wallet
- - delete the "sparrow"-folder in Bitcoin Core directory
- - starting Bitcoin Core
- starting Sparrow Wallet - it then successfully connects, but only until I close Bitcoin Core and reopen it again - then I need to do the above steps again

That is what my sparrow.log file shows about this:

```
2022-12-11 14:15:19,814 ERROR [JavaFX Application Thread] c.s.s.n.ElectrumServer [null:-1] Failed to start BWT
dev.bwt.libbwt.BwtException: JSON-RPC error: JSON decode error: missing field `keypoololdest` at line 1 column 334
	at com.sparrowwallet.merged.module@1.7.1/dev.bwt.libbwt.daemon.NativeBwtDaemon.start(Native Method)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.net.Bwt.start(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.net.Bwt.start(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.net.Bwt$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.net.Bwt$ConnectionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-12-11 14:15:45,316 ERROR [JavaFX Application Thread] c.s.s.n.ElectrumServer [null:-1] Failed to start BWT
dev.bwt.libbwt.BwtException: JSON-RPC error: JSON decode error: missing field `keypoololdest` at line 1 column 334
	at com.sparrowwallet.merged.module@1.7.1/dev.bwt.libbwt.daemon.NativeBwtDaemon.start(Native Method)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.net.Bwt.start(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.net.Bwt.start(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.net.Bwt$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.net.Bwt$ConnectionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by craigraw** [comment]
@ExchangeREC I think this is the "problem":

>  I have not connected/created/imported any wallet on Sparrow yet

Once you have Sparrow connected to Bitcoin Core, create a wallet (a hot wallet is file) and the problem should go away. It appears that the `keypoololdest` field is *not* returned if no keys have been imported into the wallet. Ref https://github.com/bitcoin/bitcoin/blob/e334f7a54592ba9f05e4a5578dd933a7a31c3444/src/wallet/rpc/wallet.cpp#L91

**Comment by craigraw** [comment]
Ok, I've managed to recreate it - the field `keypoololdest` is *not* returned when reloading an existing legacy Bitcoin Core wallet that has had no keys added to it. I've created an issue for BWT: https://github.com/bwt-dev/bwt/issues/108.

The current solution is to stop both Bitcoin Core and Sparrow, delete the Bitcoin Core wallet, restart both and then make sure to create a wallet in Sparrow before restarting either application (to ensure some keys are added to the Bitcoin Core wallet).

**Comment by ExchangeREC** [comment]
@craigraw 

> The current solution is to stop both Bitcoin Core and Sparrow, delete the Bitcoin Core wallet, restart both and then make sure to create a wallet in Sparrow before restarting either application (to ensure some keys are added to the Bitcoin Core wallet).

Wow mate - looks like it works! Thank you SO much! 
I have to "Disconnect" and "Connect" once in Sparrow but then it works. That's so great - thank you again!

**Comment by ExchangeREC** [comment]
@craigraw 

> Once you have Sparrow connected to Bitcoin Core, create a wallet (a hot wallet is file) and the problem should go away.
So in case of setting up a hardware wallet: Should I create a hot software wallet as described by you before importing or setting up a hardware wallet?

**Comment by craigraw** [comment]
> So in case of setting up a hardware wallet: Should I create a hot software wallet as described by you before importing or setting up a hardware wallet?

No, you can create any wallet. The important part is that the wallet is saved, and Sparrow adds the public keys it references to the Bitcoin Core wallet it creates.

**Comment by ExchangeREC** [comment]
Great, thanks!
