### ISSUE TITLE
Sparrow fails to connect to bitcoin core when I am using Tailscale on m1 mac

### ISSUE THREAD

**Issue by lvnilesh** [sparrowwallet/sparrow#734]
## Background:

m1  mac

* running latest sparrow
* It is on the local subnet
* It also participates in a Tailscale mesh 

node machine

* running latest bitcoin core
* running latest fulcrum
* It is on the local subnet
* It does NOT participate in the Tailscale mesh

## Observation:

Sparrow connects to fulcrum WHETHER m1 mac participates in Tailscale mesh network OR NOT

## PROBLEM

* Sparrow fails to connect to bitcoin core when m1 mac participates in Tailscale mesh
* Sparrow succeeds in connecting to bitcoin core when m1 mac stops participating in Tailscale mesh

## Logs
```
2022-11-04 13:59:33,535 ERROR [JavaFX Application Thread] c.s.s.n.ElectrumServer [null:-1] Failed to start BWT
dev.bwt.libbwt.BwtException: JSON-RPC error: transport error: Couldn't connect to host: Resource temporarily unavailable (os error 35)
	at com.sparrowwallet.merged.module@1.7.0/dev.bwt.libbwt.daemon.NativeBwtDaemon.start(Native Method)
	at com.sparrowwallet.sparrow@1.7.0/com.sparrowwallet.sparrow.net.Bwt.start(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.0/com.sparrowwallet.sparrow.net.Bwt.start(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.0/com.sparrowwallet.sparrow.net.Bwt$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.0/com.sparrowwallet.sparrow.net.Bwt$ConnectionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by craigraw** [comment]
This could be related to #723, which has been resolved in a fix that is not yet officially released. 

That said it would be helpful to see what BWT's startup parameters are. To get these, run Sparrow with DEBUG logging (see FAQ for details) and search for the log line `Configuring bwt:`.

**Comment by lvnilesh** [comment]
DEBUG log

```
DEBUG [Thread-N] c.s.s.n.Bwt [null:-1] Configuring bwt: {"network":"bitcoin","bitcoind_url":"http://192.168.22.22:8332","bitcoind_auth":"user:hash","bitcoind_wallet":"sparrow","bitcoind_timeout":30,"create_wallet_if_missing":true,"verbose":2,"electrum_addr":"127.0.0.1:0","electrum_skip_merkle":true,"require_addresses":false}

DEBUG [Thread-N] c.s.s.n.Bwt [null:-1] Booting bwt

```

**Comment by lvnilesh** [comment]
The latest build of sparrow resolved it after I did the following:

0. stop sparrow and update to the latest build
1. stop bitcoind
2. delete ~/.bitcoin/sparrow wallet
3. start bitcoind
4. run latest sparrow and let it scan the entire timechain for the wallets in sparrow.
5. repeat 4 with and without tailscale

Resolved. 

Thanks, @craigraw
