### ISSUE TITLE
Wallet failed to delete 

### ISSUE THREAD

**Issue by NoSandMan** [sparrowwallet/sparrow#738]
When trying to delete a wallet file, the wallet did not delete and could still be opened normaly.

File -> delete wallet -> enter password -> wallet closes as if deleted -> file -> open wallet -> deleted wallet available -> load wallet -> enter password -> wallet loads normally 

2022-11-06 16:08:50,379 WARN [JavaFX Application Thread] c.s.s.i.IOUtils [null:-1] Error overwriting file for deletion recovery test.mv.db
java.io.IOException: The process cannot access the file because another process has locked a portion of the file
	at java.base/java.io.RandomAccessFile.writeBytes(Native Method)
	at java.base/java.io.RandomAccessFile.write(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.0/com.sparrowwallet.sparrow.io.IOUtils.secureDelete(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.0/com.sparrowwallet.sparrow.io.Storage.delete(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@18/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-11-06 16:09:09,767 ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-144] c.s.w.c.m.d.MixSession[xxxxxxxxxxx] [null:-1]  ! connexion lost, reconnecting for a new mix...
2022-11-06 16:11:06,362 WARN [JavaFX Application Thread] c.s.s.i.IOUtils [null:-1] Error overwriting file for deletion recovery test.mv.db
java.io.IOException: The process cannot access the file because another process has locked a portion of the file
	at java.base/java.io.RandomAccessFile.writeBytes(Native Method)
	at java.base/java.io.RandomAccessFile.write(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.0/com.sparrowwallet.sparrow.io.IOUtils.secureDelete(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.0/com.sparrowwallet.sparrow.io.Storage.delete(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@18/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-11-06 16:17:18,576 ERROR [HikariPool-3 connection closer] h2database [null:-1] recovery test:database close
org.h2.message.DbException: IO Exception: "Closing" [90028-214]
	at com.sparrowwallet.merged.module@1.7.0/org.h2.message.DbException.get(Unknown Source)
	at com.sparrowwallet.merged.module@1.7.0/org.h2.mvstore.db.Store.close(Unknown Source)
	at com.sparrowwallet.merged.module@1.7.0/org.h2.engine.Database.closeOpenFilesAndUnlock(Unknown Source)
	at com.sparrowwallet.merged.module@1.7.0/org.h2.engine.Database.closeImpl(Unknown Source)
	at com.sparrowwallet.merged.module@1.7.0/org.h2.engine.Database.close(Unknown Source)
	at com.sparrowwallet.merged.module@1.7.0/org.h2.engine.Database.removeSession(Unknown Source)
	at com.sparrowwallet.merged.module@1.7.0/org.h2.engine.SessionLocal.close(Unknown Source)
	at com.sparrowwallet.merged.module@1.7.0/org.h2.jdbc.JdbcConnection.close(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(Unknown Source)
	at com.zaxxer.hikari@4.0.3/com.zaxxer.hikari.pool.HikariPool.lambda$closeConnection$1(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: IO Exception: "Closing" [90028-214]
	at com.sparrowwallet.merged.module@1.7.0/org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	at com.sparrowwallet.merged.module@1.7.0/org.h2.message.DbException.getJdbcSQLException(Unknown Source)
	... 13 common frames omitted

**Comment by craigraw** [comment]
Thanks for the bug report. Windows has a poor file locking implementation, but I have hopefully worked around that in 7863fb76 by adding a small delay to allow for database compaction before attempting to delete the wallet file. Further, Sparrow will now show an error to the user if the deletion fails, requesting that the file be manually deleted.
