### ISSUE TITLE
Sparrow unable to run hwi under Linux

### ISSUE THREAD

**Issue by qertoip** [sparrowwallet/sparrow#75]
After clicking `[Scan...]` on the "Connected Hardware Wallets" tab I get:

`java.io.IOException: cannot run program "/tmp/hwi-2.0.0-rc....` 

This happens with both running as a user and as root.

I **can** successfully run /tmp/hwi-2.0.0-rc... manually. I used it to `installudevrules`, `enumerate` connected wallets, `pair` BitBox02 etc. So the executable dumped by Sparrow in /tmp/ does work.

It is calling it from Sparrow that does not work, consistently.

I am running the most recent version 1.3. However this is not a new bug. I had it the same weeks ago.

**Comment by craigraw** [comment]
Is there any more information in the lines below that `java.io.IOException`? It would be helpful to see the full exception logging.

**Comment by qertoip** [comment]
Unfortunately, there are no more exception details. This exception is **not** logged to the console. It is only shown in the GUI, without the stacktrace or any details.

**Comment by craigraw** [comment]
Good point, I've committed a minor change that should add logging should enumerate fail. I assume you're running from source - can you give it a try?

**Comment by qertoip** [comment]
I was running the official release 1.3.0.

I did build from the source now.

Surprise: it **does work** from source! While it continues to **not work** when I run official release. Same machine, same Java version.

From source it works well with both `./sparrow` and `build/jpackage/Sparrow/bin/Sparrow`.

**Comment by craigraw** [comment]
Ok, it might be something to do with the release building process.

I've created a standard release build using the current master branch. You can find it here: https://github.com/craigraw/webcam-tester/releases/tag/1.3.0-test

Inside it, you should find a comparable install to the one you used to install the the official release. If it fails again, we will at least have exception logging.

**Comment by qertoip** [comment]
Thanks! I have ran your test build and indeed we now have a full exception on the console:

```
2021-03-13 10:55:05,208 ERROR Error executing hwi-2.0.0-rc.3
java.io.IOException: Cannot run program "/tmp/hwi-2.0.0-rc.3116588634363940435.tmp": error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.0/com.sparrowwallet.sparrow.io.Hwi.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.0/com.sparrowwallet.sparrow.io.Hwi.enumerate(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.0/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.0/com.sparrowwallet.sparrow.io.Hwi$ScheduledEnumerateService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 14 common frames omitted
```

The user Sparrow runs on is the default user 1000:1000:

```
[user@host ~]$ ps aux | grep arrow
user        2016  6.8  4.1 9275176 680920 pts/0  Sl+  10:47   0:20 ./Sparrow/bin/Sparrow
```

The permissions of the hwi executable seem fine:

```
[user@host ~]$ ls -lha /tmp/ | grep hwi
-rwxr--r--  1 user user  16M Mar 13 10:58 hwi-2.0.0-rc.311842942237293761343.tmp
```

In fact even when I run Sparrow as root, I get the very same exception.

**Comment by craigraw** [comment]
I wonder if it would work if the hwi executable had file permissions of executable to all users?

**Comment by qertoip** [comment]
> I wonder if it would work if the hwi executable had file permissions of executable to all users?

Impossible to verify because Sparrow drops a new file every time the `[Scan...]` is clicked.

But honestly I highly doubt it would help - it doesn't work even when Sparrow is being run as root.

Maybe it's something JRE specific like security policy profile / settings?

**Comment by craigraw** [comment]
Figured it out - executable file permissions were being lost during the build process. The bug is solved by running:
```
chmod 775 Sparrow/lib/runtime/lib/jspawnhelper
```

Would be great if you can verify. I've added this command to the build process for future.

**Comment by qertoip** [comment]
After running the command you mentioned the issue is fixed.

Thanks so much!
