### ISSUE TITLE
Error Opening Wallet - Could not decrypt bytes

### ISSUE THREAD

**Issue by jlahtela** [sparrowwallet/sparrow#757]
Hi,

I am having bad issue with Sparrow wallet... or maybe I am just doing something wrong.

I have created new wallet to sparrow where I transfered some Bitcoin.
I did configure it to use my own node trougth TOR.
Then I did mix from UTXOs what created "new wallets to me".

All fine and all looked to work fine. 

Now when I open this wallet after providing wallet pass and BIP39 passprashe get error 3 times:
Error Opening Wallet 
Could not decrypt bytes

Sparrow opens, but there is only "deposit wallet" 3 other wallets are missing.
I tried to open from backup file and I get same error.

On log I can see following:
`2022-11-20 18:37:27,467 ERROR [JavaFX Application Thread] c.s.s.AppController [null:-1] Error opening wallet
com.sparrowwallet.drongo.crypto.KeyCrypterException$InvalidCipherText: Could not decrypt bytes
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.crypto.AESKeyCrypter.decrypt(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.wallet.DeterministicSeed.decrypt(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.wallet.Keystore.decrypt(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.wallet.Wallet.decrypt(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.io.Storage.restorePublicKeysFromSeed(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.AppController.openWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.AppController.openWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.AppController.lambda$openWalletFile$41(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@18/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.EventHelper.fireEvent(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.fireEvent(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$new$4(Unknown Source)
	at javafx.base@18/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase$Listener.invalidated(Unknown Source)
	at javafx.base@18/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task.setState(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.lambda$call$1(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@18/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: pad block corrupted
	at org.bouncycastle.provider/org.bouncycastle.crypto.paddings.PKCS7Padding.padCount(Unknown Source)
	at org.bouncycastle.provider/org.bouncycastle.crypto.paddings.PaddedBufferedBlockCipher.doFinal(Unknown Source)
	... 38 common frames omitted`

**Comment by jlahtela** [comment]
Just for everyone info that I restored from seen (to new wallet) and discovered account (settings -> add account.. -> discover) and it works.

All receive and mix wallets/accounts are fine and balances as those should.

However... what did corrupt original wallet is unknown.

**Comment by craigraw** [comment]
Glad it was resolved. Make sure you've updated Sparrow to the latest version - there was a bug some time back that may have caused this.

**Comment by jlahtela** [comment]
> Glad it was resolved. Make sure you've updated Sparrow to the latest version - there was a bug some time back that may have caused this.

I am running with 1.7.1 what seems to be latest version by site.

If that is the case then bug is not fully fixed.

**Comment by craigraw** [comment]
The bug is fully fixed now. When was this wallet created?

It's possible that this was simply a case of file corruption.

**Comment by jlahtela** [comment]
> The bug is fully fixed now. When was this wallet created?
> 
> It's possible that this was simply a case of file corruption.

Some days ago. It was created as completely new wallet on Sparrow and with current 1.7.1 version.

**Comment by jlahtela** [comment]
There where as well backup of wallet in backup folder. When I opened it it did have same issue.

**Comment by craigraw** [comment]
Can you recall any specific steps you took when creating the original wallet? Changing the password, changing the seed?

**Comment by jlahtela** [comment]
> Can you recall any specific steps you took when creating the original wallet? Changing the password, changing the seed?

Whole process was something like this...
- create wallet on sparrow (new seed)
- made test deposit
- used mix
- changed wallet name
- changed wallet password
(Password manager was used so no possibility of typo)
- deposit more funds
- used mix
- left computer on over night
(Prevent sleep was enabled)
- mix done by morning, exit, shutdown

On evening on same day issue come when opening wallet.

**Comment by craigraw** [comment]
> The bug is fully fixed now.

I was wrong, the bug was not fully fixed. It should now be as of 7f254e76.
