### ISSUE TITLE
IO Error: Cannot connect to hidden service

### ISSUE THREAD

**Issue by datvebi** [sparrowwallet/sparrow#759]
I'm trying to connect to an electrs that others can connect to just fine. This is someone else's server and not on my local network. My server preferences are:

URL: [address].onion
Port: 50001

Nothing else selected and Tor browser is not running (I get the same message with Tor open though).  Every time I test connection, it fails with "cannot connect to hidden service". I've also tried turning on SSL and port 50002. Same message.

Here is the error log:

2022-11-22 12:14:40,678 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
com.sparrowwallet.sparrow.net.ServerException: java.io.IOException: Cannot connect to hidden service
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TcpTransport.connect(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer.connect(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Cannot connect to hidden service
	at netlayer.jpms@0.6.8/org.berndpruenster.netlayer.tor.TorSocketsKt.setup(Unknown Source)
	at netlayer.jpms@0.6.8/org.berndpruenster.netlayer.tor.TorSocketsKt.access$setup(Unknown Source)
	at netlayer.jpms@0.6.8/org.berndpruenster.netlayer.tor.TorSocket.<init>(Unknown Source)
	at netlayer.jpms@0.6.8/org.berndpruenster.netlayer.tor.TorSocket.<init>(Unknown Source)
	at netlayer.jpms@0.6.8/org.berndpruenster.netlayer.tor.TorSocket.<init>(Unknown Source)
	at com.sparrowwallet.sparrow/com.sparrowwallet.sparrow.net.TorTcpTransport.createSocket(Unknown Source)
	... 12 common frames omitted

**Comment by craigraw** [comment]
Was this discussed on the Telegram chat as possibly being a misconfiguration?
