### ISSUE TITLE
Error broadcasting transaction - Ledger Nano & Umbrel full node

### ISSUE THREAD

**Issue by hanster1** [sparrowwallet/sparrow#77]
I recently set up an Umbrel full node and connected the Sparrow wallet using the Umbrel Connect Wallet gui. Sparrow says it's connected, and shows the blue toggle, with "Connected to tcp://... at the current block height.

I construct the transacting, and sign using my ledger without issues. When I click Broadcast Transaction I get "Error broadcasting transaction".

![Screen Shot 2021-03-12 at 3 39 55 PM](https://user-images.githubusercontent.com/39974921/111002005-4ac25380-834a-11eb-8579-dbd8de878adc.png)

The log says the following:
2021-03-12 15:39:39,355 ERROR [JavaFX Application Thread] c.s.s.t.HeadersController [null:-1] Error broadcasting transaction
com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@1.3.0/com.sparrowwallet.sparrow.net.ElectrumServer.broadcastTransaction(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.0/com.sparrowwallet.sparrow.net.ElectrumServer$BroadcastTransactionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.0/com.sparrowwallet.sparrow.net.ElectrumServer$BroadcastTransactionService$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ElectrumServerRpcException: Retries exhausted
	at com.sparrowwallet.sparrow@1.3.0/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.broadcastTransaction(Unknown Source)
	... 11 common frames omitted
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@1.3.0/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	... 12 common frames omitted
Caused by: java.lang.IllegalStateException: Unable parse a JSON response: {"error":"sendrawtransaction RPC error: {\"code\":-25,\"message\":\"bad-txns-inputs-missingorspent\"}","id":103,"jsonrpc":"2.0"}
	at com.sparrowwallet.merged.module@1.3.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeAndConvert(Unknown Source)
	at com.sparrowwallet.merged.module@1.3.0/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.3.0/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.lambda$broadcastTransaction$15(Unknown Source)
	... 13 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.github.arteam.simplejsonrpc.core.domain.ErrorMessage` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('sendrawtransaction RPC error: {"code":-25,"message":"bad-txns-inputs-missingorspent"}')
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.exc.MismatchedInputException.from(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.ObjectMapper._readValue(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.ObjectMapper.readValue(Unknown Source)
	at com.fasterxml.jackson.databind@2.10.1/com.fasterxml.jackson.databind.ObjectMapper.treeToValue(Unknown Source)
	... 16 common frames omitted

**Comment by craigraw** [comment]
Bitcoin Core is giving you the error `"bad-txns-inputs-missingorspent"` on the `sendrawtransaction` RPC call. Hard to debug further without more details, but hopefully this is helpful. 

Also, it seems you have connectivity issues - probably related to Tor. Others were having issues recently too. This might the cause of your broadcast exception, if Sparrow tried twice because it thought the first time had failed (when actually it just didn't get a response over Tor).

**Comment by hanster1** [comment]
Thanks for the great work. And your reply. Seems to be Tor connectivity issues. I can't get Specter Wallet to connect. Sparrow server tests positive though, so maybe I'm wrong. Not sure what to try next. I'll dig around and see if I can find what others have done.

**Comment by hanster1** [comment]
What happens to these dormant transactions that I successfully sign but unsuccessfully broadcast? Is the transaction saved somewhere, or deleted when I close Sparrow?

**Comment by craigraw** [comment]
The transaction can be saved (File > Save Transaction) - for a fully signed transaction this saves a .txn file which can be loaded again in Sparrow and broadcast. Alternatively, use a Tor Browser and broadcast the contents of the file with https://blockstream.info/tx/push - this will offer an even greater level of privacy, since you are not using your own node.

**Comment by hanster1** [comment]
Very helpful. Thanks again.
