### ISSUE TITLE
corrupted wallet file / odd behavior

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#779]
I loaded with wallet with errors many many times over the week, I was now using a backup version.

For some weird reason the wallet ended up loading properly at last while I was documenting this.

The behavior was before was "Wallet load error" popup and all accounts would show but postmix would not.

Can close this issue once ACK

```
2022-12-15 00:13:32,259 ERROR [JavaFX Application Thread] c.s.s.AppController [null:-1] Error opening wallet
java.util.ConcurrentModificationException: null
	at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(Unknown Source)
	at java.base/java.util.TreeMap$KeyIterator.next(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.wallet.WalletNode.copy(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.wallet.Wallet.copy(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.io.Storage.restorePublicKeysFromSeed(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.AppController.openWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.AppController.openWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.1/com.sparrowwallet.sparrow.AppController.lambda$openWalletFile$39(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@18/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.EventHelper.fireEvent(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.fireEvent(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$new$4(Unknown Source)
	at javafx.base@18/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase$Listener.invalidated(Unknown Source)
	at javafx.base@18/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base@18/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task.setState(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.lambda$call$1(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@18/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by craigraw** [comment]
Thread race condition avoided in 064708f0. Should be a slight performance increase too for very large wallets.
