### ISSUE TITLE
[Bug] Error loading PSBT with sigHash: Invalid message length, was 122 not 126

### ISSUE THREAD

**Issue by orenyomtov** [sparrowwallet/sparrow#836]
Loading the following PSBT:
```
cHNidP8BAF4CAAAAATDTbJM6YNaIyTQAYYnxoMVnYC6GCJaYdFIF7UVn74/ZAAAAAAD/////AQjiAQAAAAAAIlEgxcFBesX6LnOTtFsC5dEjSEHj+AnvJH7dTHu6IaFUVKwAAAAAAAEAXgEAAAAB3lpPtenFGl/pCL6O93rbKgeu49AaJ/dXnD+GBM+/r+8AAAAAAP3///8BECcAAAAAAAAiUSDLO43I8TKyXyMFbm8tVxW8yvfhATypHToRz10xNrc3rgAAAAABASsQJwAAAAAAACJRIMs7jcjxMrJfIwVuby1XFbzK9+EBPKkdOhHPXTE2tzeuAQMEgwAAAAAA
```

Throws:
```
Caused by: java.lang.IllegalStateException: Invalid message length, was 122 not 126
```

Coming from:
https://github.com/sparrowwallet/drongo/blob/883b1c95b4e8bd961fb07ff09327d9da4a5bcb9d/src/main/java/com/sparrowwallet/drongo/protocol/Transaction.java#L721

When I generate the same PBST while omitting  `sighashType=SIGHASH_SINGLE | SIGHASH_ANYONECANPAY`, it successfully loads the PSBT:
```
cHNidP8BAF4CAAAAATDTbJM6YNaIyTQAYYnxoMVnYC6GCJaYdFIF7UVn74/ZAAAAAAD/////AQjiAQAAAAAAIlEgxcFBesX6LnOTtFsC5dEjSEHj+AnvJH7dTHu6IaFUVKwAAAAAAAEAXgEAAAAB3lpPtenFGl/pCL6O93rbKgeu49AaJ/dXnD+GBM+/r+8AAAAAAP3///8BECcAAAAAAAAiUSDLO43I8TKyXyMFbm8tVxW8yvfhATypHToRz10xNrc3rgAAAAABASsQJwAAAAAAACJRIMs7jcjxMrJfIwVuby1XFbzK9+EBPKkdOhHPXTE2tzeuAAA=
```

But when I click the Sign button, it throws the same error `Invalid message length, was 122 not 126`:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/168856/218339017-0118e668-e2e6-432d-a48e-6b9bbc8ca417.png">

Signing either PSBT using `bitcoin-cli` works:
```
./bitcoin-cli -datadir=signet walletprocesspsbt "........"
```
Logs:
```
2023-02-12 23:28:50,197 ERROR [JavaFX Application Thread] c.s.s.SparrowWallet [null:-1] Exception in thread "JavaFX Application Thread"
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml@18/javafx.fxml.FXMLLoader$MethodHandler.invoke(Unknown Source)
	at javafx.fxml@18/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@18/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.controls@18/javafx.scene.control.MenuItem.fire(Unknown Source)
	at javafx.controls@18/com.sun.javafx.scene.control.GlobalMenuAdapter.lambda$bindMenuItemProperties$2(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@18/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.controls@18/javafx.scene.control.MenuItem.fire(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassSystemMenu$1.action(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.reflect.Trampoline.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.base@18/com.sun.javafx.reflect.MethodUtil.invoke(Unknown Source)
	at javafx.fxml@18/com.sun.javafx.fxml.MethodHelper.invoke(Unknown Source)
	... 22 common frames omitted
Caused by: java.lang.IllegalStateException: Invalid message length, was 122 not 126
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.protocol.Transaction.hashForTaprootSignature(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.protocol.Transaction.hashForTaprootSignature(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTInput.getHashForSignature(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTInput.verifySignatures(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.verifySignatures(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.verifySignatures(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.2/com.sparrowwallet.sparrow.AppController.addTransactionTab(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.2/com.sparrowwallet.sparrow.AppController.addTransactionTab(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.2/com.sparrowwallet.sparrow.AppController.addTransactionTab(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.2/com.sparrowwallet.sparrow.AppController.addTransactionTab(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.2/com.sparrowwallet.sparrow.AppController.openTransactionFromText(Unknown Source)
	... 29 common frames omitted





2023-02-12 23:43:31,063 WARN [JavaFX Application Thread] c.s.s.t.HeadersController [null:-1] Failed to Sign
java.lang.IllegalStateException: Invalid message length, was 122 not 126
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.protocol.Transaction.hashForTaprootSignature(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.protocol.Transaction.hashForTaprootSignature(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTInput.getHashForSignature(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTInput.sign(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTInput.sign(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.wallet.Wallet.sign(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.2/com.sparrowwallet.sparrow.transaction.HeadersController.signUnencryptedKeystores(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.2/com.sparrowwallet.sparrow.transaction.HeadersController.signSoftwareKeystores(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.2/com.sparrowwallet.sparrow.transaction.HeadersController.signPSBT(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.reflect.Trampoline.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.base@18/com.sun.javafx.reflect.MethodUtil.invoke(Unknown Source)
	at javafx.fxml@18/com.sun.javafx.fxml.MethodHelper.invoke(Unknown Source)
	at javafx.fxml@18/javafx.fxml.FXMLLoader$MethodHandler.invoke(Unknown Source)
	at javafx.fxml@18/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@18/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@18/javafx.scene.Node.fireEvent(Unknown Source)
	at javafx.controls@18/javafx.scene.control.Button.fire(Unknown Source)
	at javafx.controls@18/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at javafx.controls@18/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@18/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@18/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@18/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@18/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.mac.MacView.notifyMouse(Unknown Source)

```

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in https://github.com/sparrowwallet/drongo/commit/22e70fd8e5adce51f3e84254ea4696c24b42e707.

**Comment by orenyomtov** [comment]
Wow incredible quick fix, thanks! When will the fix be released/how can I use the fixed version myself?

**Comment by craigraw** [comment]
You can build from source, but there should also be another release out soon.
