### ISSUE TITLE
Signing Error: Could not parse signed PSBT

### ISSUE THREAD

**Issue by akarve** [sparrowwallet/sparrow#839]
Experiencing a failure to sign in a 2-of-3 multisig setup that worked on the same machine before the most recent update (1.7.2). Device 1 = Sparrow, 2 = SeedSigner, 3 = Trezor.

Similar to #303, but with the following error logs. 2 will complete the txn if 1 signs, but 3 is unable to do so. I am fairly certain that the PSBT is well-formed and that the wallet passphrase for 3 is correct. 3 walks me through the signature and even claims to complete it, but then Sparrow shows the titular error.

```
2023-02-13 23:21:59,299 ERROR [JavaFX Application Thread] c.s.s.c.DevicePane [null:-1] Signing Error: Could not parse signed PSBT
com.sparrowwallet.sparrow.io.SignTransactionException: Could not parse signed PSBT
	at com.sparrowwallet.sparrow@1.7.2/com.sparrowwallet.sparrow.io.Hwi.signPSBT(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.2/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.2/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by craigraw** [comment]
Already reported and fixed (in PR) upstream: https://github.com/bitcoin-core/HWI/issues/661

I am hoping there is another HWI release shortly to include this.

**Comment by rserranon** [comment]
Same issue.

Experiencing a failure to sign in a 2-of-3 multisig setup that worked on the same machine before the most recent update (1.7.2). Device 1 = Coldcard, 2 = Trezor One, 3 = Trezor One. Coldcard signing OK. 

I tried signing first with Trezor and it didn't work either, I also tried with  a tx with just 1 input and two outputs with no luck.

```log
2023-02-19 00:17:10,858 ERROR [JavaFX Application Thread] c.s.s.c.DevicePane [null:-1] Signing Error: Could not parse signed PSBT
com.sparrowwallet.sparrow.io.SignTransactionException: Could not parse signed PSBT
	at com.sparrowwallet.sparrow@1.7.2/com.sparrowwallet.sparrow.io.Hwi.signPSBT(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.2/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.2/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
Caused by: com.sparrowwallet.drongo.psbt.PSBTSignatureException: Partial signature does not verify against provided public key
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTInput.verifySignatures(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.verifySignatures(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.parseInputEntries(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.parse(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.<init>(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.fromString(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.fromString(Unknown Source)

2023-02-19 13:36:12,966 ERROR [JavaFX Application Thread] c.s.s.c.DevicePane [null:-1] Signing Error: Could not parse signed PSBT
com.sparrowwallet.sparrow.io.SignTransactionException: Could not parse signed PSBT
	at com.sparrowwallet.sparrow@1.7.2/com.sparrowwallet.sparrow.io.Hwi.signPSBT(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.2/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.2/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
Caused by: com.sparrowwallet.drongo.psbt.PSBTSignatureException: Partial signature does not verify against provided public key
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTInput.verifySignatures(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.verifySignatures(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.parseInputEntries(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.parse(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.<init>(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.fromString(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.fromString(Unknown Source)
```

**Comment by rserranon** [comment]
> Already reported and fixed (in PR) upstream: [bitcoin-core/HWI#661](https://github.com/bitcoin-core/HWI/issues/661)
> 
> I am hoping there is another HWI release shortly to include this.

in this setup 2 of my keys are Trezor, is there a workaround or should I wait and HODL ;)

**Comment by craigraw** [comment]
The workaround is to revert to v1.7.1, but a new Sparrow release will be out soon. There is a last PR for HWI being finalised before the fix is released there.

**Comment by craigraw** [comment]
HWI has been upgraded to 2.2.1 as https://github.com/sparrowwallet/sparrow/commit/10e751d6e1e8432b0bdb1cf82be9c02d9f325b0a, fixing this issue.
