### ISSUE TITLE
[BUG] Error loading PSBT

### ISSUE THREAD

**Issue by orenyomtov** [sparrowwallet/sparrow#855]
Example PSBT:
```
cHNidP8BAP0xAQIAAAADqnalp2fgsyK0scoHKzqBmqZKUArTl8OXv4M0HTPiMCQAAAAAAP////9iG9VdYJUJak5Dqhtvn7rKfW9IKLIB5tOvRiwmDwxKnQAAAAAA/////6p2padn4LMitLHKBys6gZqmSlAK05fDl7+DNB0z4jAkAQAAAAD/////BOAuAAAAAAAAIlEgyzuNyPEysl8jBW5vLVcVvMr34QE8qR06Ec9dMTa3N66MgQEAAAAAACJRIHE744KXVhVdtW5M0C83rfvgwuQRJpOKDZDeC84gSF9T6AMAAAAAAAAiUSDLO43I8TKyXyMFbm8tVxW8yvfhATypHToRz10xNrc3ruwtAAAAAAAAIlEgyzuNyPEysl8jBW5vLVcVvMr34QE8qR06Ec9dMTa3N64AAAAAAAEAiQIAAAABYhvVXWCVCWpOQ6obb5+6yn1vSCiyAebTr0YsJg8MSp0BAAAAAP////8C6AMAAAAAAAAiUSDLO43I8TKyXyMFbm8tVxW8yvfhATypHToRz10xNrc3rh7dAQAAAAAAIlEgyzuNyPEysl8jBW5vLVcVvMr34QE8qR06Ec9dMTa3N64AAAAAAQEr6AMAAAAAAAAiUSDLO43I8TKyXyMFbm8tVxW8yvfhATypHToRz10xNrc3rgAAAQDNAgAAAAABAWIb1V1glQlqTkOqG2+fusp9b0gosgHm069GLCYPDEqdAQAAAAD/////AugDAAAAAAAAIlEgyzuNyPEysl8jBW5vLVcVvMr34QE8qR06Ec9dMTa3N64e3QEAAAAAACJRIMs7jcjxMrJfIwVuby1XFbzK9+EBPKkdOhHPXTE2tzeuAUBmvQnus2c435MKet1dYUjD19TdmbgIXfeDmJyfXDmSdP1/kcg9gMJ82ZAFSUaqQbgU7WHkc4y9GhxNzX3KT03JAAAAAAEBKx7dAQAAAAAAIlEgyzuNyPEysl8jBW5vLVcVvMr34QE8qR06Ec9dMTa3N64AAAAAAA==
```

Stack trace:
```
2023-02-20 22:40:05,640 ERROR [JavaFX Application Thread] c.s.s.SparrowWallet [SparrowDesktop.java:35] Exception in thread "JavaFX Application Thread"
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml@18/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1857)
	at javafx.fxml@18/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1724)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@18/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.controls@18/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at javafx.controls@18/com.sun.javafx.scene.control.GlobalMenuAdapter.lambda$bindMenuItemProperties$2(GlobalMenuAdapter.java:153)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@18/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.controls@18/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassSystemMenu$1.action(GlassSystemMenu.java:234)
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:116)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:77)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at javafx.base@18/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml@18/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:84)
	at javafx.fxml@18/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1852)
	... 21 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "com.sparrowwallet.drongo.protocol.TransactionOutput.getValue()" because the return value of "java.util.List.get(int)" is null
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.protocol.Transaction.hashForTaprootSignature(Transaction.java:659)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.protocol.Transaction.hashForTaprootSignature(Transaction.java:630)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTInput.getHashForSignature(PSBTInput.java:704)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBTInput.verifySignatures(PSBTInput.java:571)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.verifySignatures(PSBT.java:399)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.psbt.PSBT.verifySignatures(PSBT.java:394)
	at com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.AppController.addTransactionTab(AppController.java:1769)
	at com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.AppController.addTransactionTab(AppController.java:1713)
	at com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.AppController.addTransactionTab(AppController.java:1687)
	at com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.AppController.addTransactionTab(AppController.java:1675)
	at com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.AppController.openTransactionFromText(AppController.java:594)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 28 common frames omitted
```

`bitcoin-cli` does manage to parse and sign the same PSBT:
```
$ ./bitcoin-cli -datadir=signet -rpcwallet=ord walletprocesspsbt "cHNidP8BAP0xAQIAAAADqnalp2fgsyK0scoHKzqBmqZKUArTl8OXv4M0HTPiMCQAAAAAAP////9iG9VdYJUJak5Dqhtvn7rKfW9IKLIB5tOvRiwmDwxKnQAAAAAA/////6p2padn4LMitLHKBys6gZqmSlAK05fDl7+DNB0z4jAkAQAAAAD/////BOAuAAAAAAAAIlEgyzuNyPEysl8jBW5vLVcVvMr34QE8qR06Ec9dMTa3N66MgQEAAAAAACJRIHE744KXVhVdtW5M0C83rfvgwuQRJpOKDZDeC84gSF9T6AMAAAAAAAAiUSDLO43I8TKyXyMFbm8tVxW8yvfhATypHToRz10xNrc3ruwtAAAAAAAAIlEgyzuNyPEysl8jBW5vLVcVvMr34QE8qR06Ec9dMTa3N64AAAAAAAEAiQIAAAABYhvVXWCVCWpOQ6obb5+6yn1vSCiyAebTr0YsJg8MSp0BAAAAAP////8C6AMAAAAAAAAiUSDLO43I8TKyXyMFbm8tVxW8yvfhATypHToRz10xNrc3rh7dAQAAAAAAIlEgyzuNyPEysl8jBW5vLVcVvMr34QE8qR06Ec9dMTa3N64AAAAAAQEr6AMAAAAAAAAiUSDLO43I8TKyXyMFbm8tVxW8yvfhATypHToRz10xNrc3rgAAAQDNAgAAAAABAWIb1V1glQlqTkOqG2+fusp9b0gosgHm069GLCYPDEqdAQAAAAD/////AugDAAAAAAAAIlEgyzuNyPEysl8jBW5vLVcVvMr34QE8qR06Ec9dMTa3N64e3QEAAAAAACJRIMs7jcjxMrJfIwVuby1XFbzK9+EBPKkdOhHPXTE2tzeuAUBmvQnus2c435MKet1dYUjD19TdmbgIXfeDmJyfXDmSdP1/kcg9gMJ82ZAFSUaqQbgU7WHkc4y9GhxNzX3KT03JAAAAAAEBKx7dAQAAAAAAIlEgyzuNyPEysl8jBW5vLVcVvMr34QE8qR06Ec9dMTa3N64AAAAAAA=="
{
  "psbt": "...",
  "complete": true
}
```

**Comment by craigraw** [comment]
The provided PSBT does not appear to be valid. BIP174 states `The Signer should not need any additional data sources, as all necessary information is provided in the PSBT format.` However, I find that neither the `PSBT_IN_NON_WITNESS_UTXO` nor the `PSBT_IN_WITNESS_UTXO` is provided for the second (`#1`)  input. In fact, no fields are provided at all. This means the taproot signature hashing, which requires the value of the UTXO being spent, cannot complete.

**Comment by orenyomtov** [comment]
You're right, my bad, thanks!
