### ISSUE TITLE
Sparrow fails to import electrum wallet

### ISSUE THREAD

**Issue by packrobottom** [sparrowwallet/sparrow#881]
trying to import electrum backup wallet file on Mac OS results in
Cannot invoke "String.length()"because "<parameter1>" is null
<img width="464" alt="Screen Shot 2023-03-02 at 8 23 32 AM" src="https://user-images.githubusercontent.com/4675798/222489581-2bebde69-840a-45b6-b4fc-87248b04fda8.png">

**Comment by craigraw** [comment]
Please add the full exception from the log file (Help menu).

**Comment by packrobottom** [comment]
2023-03-03 07:13:07,056 ERROR [JavaFX Application Thread] c.s.s.c.FileImportPane [null:-1] Error importing file
com.sparrowwallet.sparrow.io.ImportException: Error importing Electrum Wallet
	at com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.io.Electrum.importWallet(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.control.FileWalletImportPane.importFile(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.control.FileImportPane.importFile(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.control.FileImportPane.importFile(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.control.FileImportPane.lambda$createButton$3(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@18/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@18/javafx.scene.Node.fireEvent(Unknown Source)
	at javafx.controls@18/javafx.scene.control.Button.fire(Unknown Source)
	at javafx.controls@18/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at javafx.controls@18/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@18/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@18/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@18/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@18/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.mac.MacView.notifyMouse(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.mac.MacApplication._enterNestedEventLoopImpl(Native Method)
	at javafx.graphics@18/com.sun.glass.ui.mac.MacApplication._enterNestedEventLoop(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.Application.enterNestedEventLoop(Unknown Source)
	at javafx.graphics@18/com.sun.glass.ui.EventLoop.enter(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(Unknown Source)
	at javafx.graphics@18/javafx.stage.Stage.showAndWait(Unknown Source)
	at javafx.controls@18/javafx.scene.control.HeavyweightDialog.showAndWait(Unknown Source)
	at javafx.controls@18/javafx.scene.control.Dialog.showAndWait(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.AppController.importWallet(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.reflect.Trampoline.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.base@18/com.sun.javafx.reflect.MethodUtil.invoke(Unknown Source)
	at javafx.fxml@18/com.sun.javafx.fxml.MethodHelper.invoke(Unknown Source)
	at javafx.fxml@18/javafx.fxml.FXMLLoader$MethodHandler.invoke(Unknown Source)
	at javafx.fxml@18/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@18/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.controls@18/javafx.scene.control.MenuItem.fire(Unknown Source)
	at javafx.controls@18/com.sun.javafx.scene.control.GlobalMenuAdapter.lambda$bindMenuItemProperties$2(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@18/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.controls@18/javafx.scene.control.MenuItem.fire(Unknown Source)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassSystemMenu$1.action(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.protocol.Base58.decode(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.protocol.Base58.decodeChecked(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.ExtendedKey.fromDescriptor(Unknown Source)
	... 106 common frames omitted

**Comment by craigraw** [comment]
It appears that this Electrum wallet file is non-standard. In particular, it contains an xpub field that is empty. Is this a normal BIP32 wallet?

**Comment by packrobottom** [comment]
I just installed electrum on Mac OS and it's the default wallet
added 3 private keys too it etc

**Comment by packrobottom** [comment]
I created a new electrum wallet imported 3 private keys into it saved it exported it and same error.  I'd like to use this app as it has a great interface but I guess it's not ready on Mac yet.  Pity

**Comment by craigraw** [comment]
Sparrow supports HD wallets only, not single private key wallets. You can sweep a private key to any HD wallet though.
