### ISSUE TITLE
Connection failure bitcoin core to regtest

### ISSUE THREAD

**Issue by Blazsoul** [sparrowwallet/sparrow#888]
For some reason, I cannot connect to regtest, but signet local node does work.

bitcoin.conf
```
server=1
daemon=1
regtest=1
prune=1200
```
Sparrow: 1.7.3(Mac)
Bitcoin core: v24.0.1

Log file
```
2023-03-09 03:31:58,071 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
java.lang.NullPointerException: Cannot invoke "String.toCharArray()" because "<parameter1>" is null
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.Utils.hexToBytes(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.protocol.Sha256Hash.wrap(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.net.cormorant.bitcoind.VerboseBlockHeader.getBlockHeader(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.net.cormorant.bitcoind.BitcoindClient.initialize(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.net.cormorant.Cormorant.start(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in 368b24ea. Sparrow now handles empty (zero mined blocks) chains. 

The workaround here is simply to mine the first block in the chain.
