### ISSUE TITLE
[null:-1] Connection errors when using an avahi alias .local name for the Bitcoin RPC on windows 11

### ISSUE THREAD

**Issue by gStart9** [sparrowwallet/sparrow#909]
An embassy user reported a problem connecting to their bitcoin rpc via .local (an avahi alias for the bitcoin rpc service):

```
2023-03-19 10:45:16,900 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error

java.lang.IllegalStateException: I/O error during request processing
                at [simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.ObjectApiBuilder.execute(Unknown](mailto:simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.ObjectApiBuilder.execute(Unknown) Source)
                at [simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.ObjectApiBuilder.invoke(Unknown](mailto:simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.ObjectApiBuilder.invoke(Unknown) Source)
                at jdk.proxy2/jdk.proxy2.$Proxy15.getNetworkInfo(Unknown Source)
                at [com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.net.cormorant.bitcoind.BitcoindClient.initialize(Unknown](mailto:com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.net.cormorant.bitcoind.BitcoindClient.initialize(Unknown) Source)
                at [com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.net.cormorant.Cormorant.start(Unknown](mailto:com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.net.cormorant.Cormorant.start(Unknown) Source)
                at [com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown](mailto:com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown) Source)
                at [com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown](mailto:com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown) Source)
                at [javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown](mailto:javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown) Source)
                at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
                at [javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown](mailto:javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown) Source)
                at java.base/java.security.AccessController.doPrivileged(Unknown Source)
                at [javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown](mailto:javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown) Source)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
                at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.UnknownHostException: reallylonglocalhostname.local
                at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
                at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
                at java.base/java.net.Socket.connect(Unknown Source)
                at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
                at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
                at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
                at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
                at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
                at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
                at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
                at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
                at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
                at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
                at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
                at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
                at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
                at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
                at [com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.net.cormorant.bitcoind.BitcoindTransport.pass(Unknown](mailto:com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.net.cormorant.bitcoind.BitcoindTransport.pass(Unknown) Source)

                ... 15 common frames omitted
```

When attempting to reproduce this on our own windows setup, I got a very similar error:
```
2023-03-20 14:17:48,572 ERROR [pool-5-thread-1] c.s.s.n.c.e.RequestHandler [null:-1] Could not communicate with client socket
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.read(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(Unknown Source)
	at java.base/java.net.Socket$SocketInputStream.read(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.base/java.io.InputStreamReader.read(Unknown Source)
	at java.base/java.io.BufferedReader.fill(Unknown Source)
	at java.base/java.io.BufferedReader.readLine(Unknown Source)
	at java.base/java.io.BufferedReader.readLine(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.3/com.sparrowwallet.sparrow.net.cormorant.electrum.RequestHandler.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Curl "works" from the same windows pc (although maybe I have some rpc syntax wrong, or windows syntax wrong, at least I'm definitely getting a response from the RPC):
```
C:\Users\start9>curl -k --data-binary '{"jsonrpc":"1.0","id":"curltest","method":"getblockchaininfo","params":[]}' -H 'content-type:text/plain;' "https://bitcoin:356kys023ruzaj33yb3@mysuperlongbitcoinrpc.local/"
    {"result":null,"error":{"code":-32700,"message":"Parse error"},"id":null}
```
Same curl works fine from my linux box:
```
curl -k --data-binary '{"jsonrpc":"1.0","id":"curltest","method":"getblockchaininfo","params":[]}' -H 'content-type:text/plain;' "https://bitcoin:356kys023ruzaj33yb3@mysuperlongbitcoinrpc.local/"
{"result":{"chain":"main","blocks":781716,"headers":781716,"bestblockhash":"00000000000000000002943367e86046586e156ed1976d70107e49260c60460e","difficulty":43551722213590.37,"time":1679347298,"mediantime":1679344850,"verificationprogress":0.9999993474460475,"initialblockdownload":false,"chainwork":"0000000000000000000000000000000000000000432eb13f55bd3b92b70feb12","size_on_disk":529164118005,"pruned":false,"warnings":""},"error":null,"id":"curltest"}
```

So we know the .local is resolving and reachable and the username and password is working.

It just seems sparrow isn't.  Are you able to read the tea-leaves to interpret these error messages?

Two things I will note:

1) While other computers such as linux seem to get the ipv4 by default when for instance, pinging mysuperlongbitcoinrpc.local, windows seems to always get the ipv6 local address for some reason:
![image](https://user-images.githubusercontent.com/106188942/226472603-45347a44-2c7c-4707-930f-6d54ae8684e6.png)
It also looks like for some strange reason windows is appending a %19 in there.  I've also seen %28 on the other user's windows computer who is experiencing this problem.  Given that there is a ping response, I assume this is just a UI display bug in windows and probably not related to this problem.

2) This happened on windows while I was setting up and testing the rpc details in Sparrow, in case it matters:
![image](https://user-images.githubusercontent.com/106188942/226473099-4b736f2a-2a1b-4d81-9e11-5a7e84bd614d.png)
I clicked "Allow access".

Thanks

G

**Comment by craigraw** [comment]
This appears to be a network configuration issue.

Firstly, the two errors are actually quite different - one is a name resolution error that occurs before an IP address can be found, and the other is a connection error that occurs after an IP address is found. For the error you are experiencing, it is likely that Java has resolved the `.local` name to an IPv6 address (as does `ping`), and Bitcoin Core is not bound to that address. Can you use the Resolver from https://github.com/sparrowwallet/sparrow/issues/634#issuecomment-1217616898 to test this out? Run with `java Resolver reallylongname.local`.

For the `curl` tests, try running them with `--ipv4` and `--ipv6` - perhaps it defaults to IPv4 if it finds both. Fwiw, I tried the same test on my Windows machine, and the remote `.local` address I used (which resolves to an IPv4 address that Bitcoin Core binds on) works fine.

**Comment by gStart9** [comment]
OK, thanks for the reminder about that Resolver code.

I got my local situation on this test Windows box worked out.  Windows (at least from java) is indeed resolving it to the embassy's local ipv4 address.  I was getting various disconnection errors until I restarted the embassy, so what I was experiencing may be some kind of embassy bug, currently uncharacterized.

Waiting to hear back from our user having the other distinct resolution problem in the wild.

**Comment by craigraw** [comment]
This issue is getting dated now, so closing it off.

**Comment by p-bateman** [comment]
Hey guys!

Just wanted to comment: I am the user described here. I still have the same problem. Sometimes sparrow connects, sometimes it doesn't. I'd say it's about 95% of the time that it does not connect. I tried the ipv4 address thing and it resolves to the local ipv4 address but I still have the problem with the connection.

Firewall shouldn't be an issue either. And if I use the same start 9 node on the same laptop for a connection to Specter it works. But I want to use Sparrow ;)

The general error I am getting is still the "Could not communicate with clietnt socket java.net.SockectException: Connection reset".

**Comment by p-bateman** [comment]
One more note: I am getting the "Connection error java.lang.IllegalStateException: I/O error during request processing"

 from time to time as well. It's the same machine and I'm not changing anything else.

Just one more note:
Connection to a public server works instantly.
