### ISSUE TITLE
Signing Error : Total input amounts less than total output amounts.

### ISSUE THREAD

**Issue by satoshi0770** [sparrowwallet/sparrow#933]
attempting to create a psbt using jade hww, native segwit, with sparrow
after jade signs, ui shows Signing Error : Total input amounts less than total output amounts
here is what error log shows
2023-04-09 12:28:11,458 ERROR [JavaFX Application Thread] c.s.s.c.DevicePane [null:-1] Signing Error: Total input amounts less than total output amounts
com.sparrowwallet.sparrow.io.SignTransactionException: Total input amounts less than total output amounts
	at com.sparrowwallet.sparrow@1.7.4/com.sparrowwallet.sparrow.io.Hwi.signPSBT(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.4/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.4/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

the psbt needs to have higher output than input, this way the other party can fill with their own input
this error does not happen when not using hww and signing from a local wallet

**Comment by craigraw** [comment]
What sighash flag are you using?

**Comment by satoshi0770** [comment]
If im not mistaken it should be sighash single | acp
Im using openordex to create a listing for inscription. It works when using a local wallet on both taproot and native segwit.
Jade doesnt have taproot signing support yet, so i attempted with nativesegwit on jade. And this is error it gave.
Im wondering if its a jade problem ?
Since im attempting to use jade to create the psbt, not finalize it.
