### ISSUE TITLE
Cannot connect to Umbrel node through TOR on 1.7.4 (all releases after 1.7.0)

### ISSUE THREAD

**Issue by 50egtftz** [sparrowwallet/sparrow#941]
OS: Ubuntu 22.04.02

After upgrading to sparrow_1.7.4-1_amd64.deb, I am not able to connect to my node using TOR. 

I get the error message:

> Could not Connect:
> SOCKS server general failure. Check if the proxy server is running.

![Screenshot from 2023-04-12 17-18-23](https://user-images.githubusercontent.com/127372618/231590267-9c65559e-1912-4a57-823e-86f235307999.jpg)

My TOR service seems to be running.

![Screenshot from 2023-04-12 17-12-34](https://user-images.githubusercontent.com/127372618/231588954-25d76b27-4aac-4a5d-aa63-59c685b0ecec.png)

This has been happening with every release after 1.7.0. 

What is puzzling: If I revert to sparrow_1.7.0_amd64.deb, everything is fine again

![Screenshot from 2023-04-12 17-16-26](https://user-images.githubusercontent.com/127372618/231588140-0f31101e-b5bc-4edf-b52a-82a107febe96.jpg)

Here are some extra tries I attempted:

- Toggling the proxy doesn't make a difference.
- Connecting through local network "umbrel.local" works.

Any help would be greatly appreciated. Would love to be able to upgrade my Sparrow wallet!

**Comment by 50egtftz** [comment]
Not sure if this from the log helps:
```

2023-04-12 17:40:11,286 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
com.sparrowwallet.sparrow.net.ProxyServerException: java.net.SocketException: SOCKS server general failure
	at com.sparrowwallet.sparrow@1.7.4/com.sparrowwallet.sparrow.net.TcpTransport.connect(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.4/com.sparrowwallet.sparrow.net.ElectrumServer.connect(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.4/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.4/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: SOCKS server general failure
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.4/com.sparrowwallet.sparrow.net.TcpTransport.createSocket(Unknown Source)
	... 12 common frames omitted
2023-04-12 17:44:24,638 WARN [JavaFX Application Thread] c.s.s.n.Tor [null:-1] Apr 12 17:44:24.000 [warn] Rejecting SOCKS request for anonymous connection to private address [scrubbed].
```

**Comment by craigraw** [comment]
Here is your issue: Rejecting SOCKS request for anonymous connection to private address [scrubbed]. This message is produced by the Tor proxy itself. It sounds like your proxy is unable to route to whatever address you have set for your server, as it considers it a private address.

**Comment by 50egtftz** [comment]
Thank you for replying! 
Is there anything I can do to solve this on my Tor proxy? 
Do you know why the Tor proxy works fine on 1.7.0, but not on subsequent releases?

**Comment by craigraw** [comment]
I don’t know the details of your network setup, so it’s hard to advise. If your server is on your local network, I suggest just using it’s local IP and avoiding Tor.

**Comment by 50egtftz** [comment]
Unfortunately I travel quite a bit and need Tor to access remotely. Appreciate the help though. I wonder if anyone else has the same issue. 
For now I guess I am gonna have to stick to Electrum.

**Comment by craigraw** [comment]
Ok. I'm certain it's something related to your setup, but since you haven't shared any details I can't help further. Closing this off.
