### ISSUE TITLE
Can't connect to local bitcoin core

### ISSUE THREAD

**Issue by duncancmt** [sparrowwallet/sparrow#942]
I have a fresh install of both (pruned) bitcoin core and Sparrow 1.7.4. Attempting to connect to my local bitcoin core gives the following error message, which Googling didn't give any indication what's wrong

```
Cannot invoke "com.sparrowwallet.sparrow.net.cormorant.bitcoind.ListWalletDirResult.wallets()" because "<local3>" is null
```

On I get the following traceback in the logs:

```
2023-04-13 23:54:03,656 ERROR Connection error
java.lang.NullPointerException: Cannot invoke "com.sparrowwallet.sparrow.net.cormorant.bitcoind.ListWalletDirResult.wallets()" because "<local3>" is null
	at com.sparrowwallet.sparrow@1.7.4/com.sparrowwallet.sparrow.net.cormorant.bitcoind.BitcoindClient.initialize(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.4/com.sparrowwallet.sparrow.net.cormorant.Cormorant.start(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.4/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.4/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

I'm at a loss about how to make this work.

**Comment by craigraw** [comment]
What version of Bitcoin Core? Is wallet functionality enabled? Have you checked the Core debug.log?

**Comment by duncancmt** [comment]
> What version of Bitcoin Core?
```
$ bitcoind --version
Bitcoin Core version v24.0.1
```
> Is wallet functionality enabled?

no. I have `disablewallet=1` in my `bitcoin.conf`
> Have you checked the Core debug.log?

no messages except the latest `UpdateTip:`

**Comment by craigraw** [comment]
Ok - you need wallet functionality enabled as Sparrow uses Bitcoin Core's wallet as a backend for tracking transactions when connecting directly to Bitcoin Core.

**Comment by craigraw** [comment]
Error message improved in 432e0642.

**Comment by duncancmt** [comment]
Thanks for your help!

For anyone else who also made a dumb mistake configuring bitcoin core, you also can't have `blocksonly=1` in your `bitcoin.conf`. It prevents Sparrow from loading fee estimates.
