### ISSUE TITLE
Sparrow No Longer Connects to Bitcoin Core

### ISSUE THREAD

**Issue by ibelieveinpup** [sparrowwallet/sparrow#952]
I am running bitcoin core 24.0.1 and am using Sparrow 1.7.6.  Sparrow is able to connect to bitcoin core very sporadically.  I am able to send rpc commands to my node using:

./bitcoin-cli -rpcconnect=192.168.1.202 -rpcport=8332 -rpcuser=user -stdinrpcpass -getinfoRPC password> 
Chain: main
Blocks: 787408
Headers: 787408
Verification progress: 99.9999%
Difficulty: 48712405953118.43

Network: in 0, out 10, total 10
Version: 240001
Time offset (s): 0
Proxies: n/a
Min tx relay fee rate (BTC/kvB): 0.00001000

Wallet: cormorant
Keypool size: 1001
Transaction fee rate (-paytxfee) (BTC/kvB): 0.00000000

Balance: (It gives me my balance)

Warnings: 

./bitcoin-cli -rpcconnect=192.168.1.202 -rpcport=8332 -rpcuser=user -stdinrpcpass getwalletinfo
RPC password> 
{
  "walletname": "cormorant",
  "walletversion": 169900,
  "format": "sqlite",
  "balance": (Shows my balance),
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 3,
  "keypoolsize": 1001,
  "keypoolsize_hd_internal": 0,
  "paytxfee": 0.00000000,
  "private_keys_enabled": false,
  "avoid_reuse": true,
  "scanning": false,
  "descriptors": true,
  "external_signer": false
}

For some reason it is timing out.  The following is the log info:  

2023-04-28 16:45:26,117 WARN [Thread-17] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 34 secs
2023-04-28 16:46:00,168 WARN [Thread-14] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 34 secs
2023-04-28 16:46:34,220 WARN [Thread-17] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 34 secs
2023-04-28 16:47:08,271 WARN [Thread-14] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 34 secs
2023-04-28 16:47:42,322 WARN [Thread-17] c.s.s.n.TcpTransport [null:-1] No response from server, setting read timeout to 34 secs

I have seen another similar thread:

https://github.com/sparrowwallet/sparrow/issues/770

I moved the old sparrow folder, rebooted the node and it works...once.  Then if I disconnect and try to reconnect I get the above timing out messages.

**Comment by craigraw** [comment]
Unless you have `useLegacyCoreWallet` set to `true` in your Sparrow config file, you can ignore the earlier issue - it doesn't apply. 

Is Bitcoin Core running on another PC? You can turn on DEBUG logging (see FAQ) to see which RPC commands are timing out (filter on `BitcoindTransport`).

**Comment by ibelieveinpup** [comment]
Thank you for the reply.  

useLegacyCoreWallet is set to false in my Sparrow config file.

Bitcoin Core is running on a Raspberry Pi 3B+ on my network.  I am able to RPC to it as shown above.  

from debug.log in core nothing appears to be timing out as no errors are reported after Sparrow times out.

**Comment by craigraw** [comment]
Core's debug.log is not particularly helpful for debugging RPC errors.

I again suggest using Sparrow's DEBUG logging, as described in my previous comment.

**Comment by ibelieveinpup** [comment]
Did I not post the log info above?  If I posted the wrong log, which one was I supposed to post?

**Comment by craigraw** [comment]
Sparrow's log (`sparrow.log`) can be found in Sparrow's home folder - see the FAQ for details.

**Comment by ibelieveinpup** [comment]
Okay, thank you.

Here is what I found in sparrow.log for that day.

2023-05-02 18:50:13,732 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
java.lang.IllegalStateException: I/O error during request processing
        at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.ObjectApiBuilder.execute(Unknown Source)
        at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.ObjectApiBuilder.invoke(Unknown Source)
        at jdk.proxy2/jdk.proxy2.$Proxy15.getNetworkInfo(Unknown Source)
        at com.sparrowwallet.sparrow@1.7.6/com.sparrowwallet.sparrow.net.cormorant.bitcoind.BitcoindClient.initialize(Unknown Source)
        at com.sparrowwallet.sparrow@1.7.6/com.sparrowwallet.sparrow.net.cormorant.Cormorant.start(Unknown Source)
        at com.sparrowwallet.sparrow@1.7.6/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
        at com.sparrowwallet.sparrow@1.7.6/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
        at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Unknown Source)
        at java.base/sun.nio.ch.Net.connect(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
        at com.sparrowwallet.sparrow@1.7.6/com.sparrowwallet.sparrow.net.cormorant.bitcoind.BitcoindTransport.pass(Unknown Source)
        ... 15 common frames omitted

**Comment by craigraw** [comment]
Ok, here's the critical line:
```
Caused by: java.net.ConnectException: Connection refused
```

For some reason, the client connection to the Bitcoin Core RPC is being refused. Given your previous comments it sounds like some kind of a network issue, but it's difficult to say more. I can say that the call that is failing is the first call Sparrow makes to Bitcoin Core during initialization. Have you setup Bitcoin Core with the correct `rpcallowip` config?

**Comment by craigraw** [comment]
No response, closing this off.

**Comment by ibelieveinpup** [comment]
Sorry for the slow reply.  I was away for the holiday.  Bitcoin cores seems
to be configured correctly as evidenced by the ability to run rpc calls
from terminal from the same computer that I am running Sparrow on.

**Comment by craigraw** [comment]
Have you setup Bitcoin Core with the correct `rpcallowip` config?

**Comment by craigraw** [comment]
I suspect the cause of the problem here is Sparrow requesting a mempool dump from a low powered server. I'm not sure, but it may be that the RPC interface is simply too bogged down servicing this call to respond to any others. I'll have a think on how this situation can be improved.

**Comment by ibelieveinpup** [comment]
I was wondering if that had something to do with it.  Core is running on a
Raspberry Pi 3B+.

**Comment by craigraw** [comment]
Fixed - see https://github.com/sparrowwallet/sparrow/issues/991#issuecomment-1598891571

**Comment by ibelieveinpup** [comment]
Awesome! Thank you!  Looking forward to that making its way into an
upcoming release.
